import {HEROES,WEAPONS,RELICS,SUPPLIES,BIOMES} from './data.js';
import {clamp,dist,createRng,statsFor,attackDamage,inMeleeArc,segmentHit,rewardChoices,weaponChoices,roomPlan,byHero,byWeapon,meleeTypes} from './rules.js';
const SAVE_KEY='relic-field-v1';
const freshSave=()=>({bank:0,heroes:[],weapons:[],relics:[],supplies:[],runs:0,best:0,wins:0});
export class Game extends EventTarget{
 constructor(){super();this.state='lobby';this.hero=HEROES[0];this.weapon=byWeapon(this.hero.weapon);this.keys=new Set();this.aim={x:630,y:430};this.holding=false;this.muted=true;this.t=0;this.nextId=1;this.save=freshSave();try{const saved=JSON.parse(localStorage.getItem(SAVE_KEY));if(saved&&typeof saved==='object'){for(const k of ['bank','runs','best','wins'])if(Number.isFinite(saved[k])&&saved[k]>=0)this.save[k]=saved[k];for(const k of ['heroes','weapons','relics','supplies'])if(Array.isArray(saved[k]))this.save[k]=[...new Set(saved[k].filter(x=>typeof x==='string'))];}}catch{}this.rng=createRng(42427);this.room=0;this.resetWorld();}
 emit(name,detail={}){this.dispatchEvent(new CustomEvent(name,{detail}));}
 persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(this.save));}catch{this.emit('toast',{text:'浏览器未允许保存，本次远征仍可继续。'});}}
 discover(type,id){if(!this.save[type].includes(id)){this.save[type].push(id);this.persist();this.emit('discovery',{type,id});}}
 selectHero(id){if(this.state!=='lobby')return;this.hero=byHero(id);this.weapon=byWeapon(this.hero.weapon);this.resetWorld();this.emit('refresh');}
 selectWeapon(id){if(this.state!=='lobby')return;this.weapon=byWeapon(id);this.emit('refresh');}
 resetWorld(){this.player={x:452,y:466,radius:17,hp:this.hero.hp,shield:0,angle:-.55,attackCd:0,skillCd:0,dodgeCd:0,dash:0,invuln:0,anim:0,moving:false,buff:0,critBuff:0};this.stats=statsFor(this.hero);this.relics=[];this.enemies=[];this.projectiles=[];this.effects=[];this.particles=[];this.drops=[];this.turrets=[];this.gold=0;this.level=1;this.xp=0;this.nextXp=42;this.pendingLevels=0;this.supplies={tea:2};this.activeSupply='tea';this.chest={x:270,y:540,open:false};this.portal={x:750,y:135};this.roomTime=0;this.roomClear=false;this.wave=0;this.waveDelay=0;this.freezeClock=8;this.combo=0;this.attacks=0;this.hurtCd=0;this.runTime=0;this.hitStop=0;this.boss=null;this.obstacles=[{x:180,y:155,r:25},{x:670,y:725,r:29},{x:745,y:525,r:21},{x:142,y:665,r:22}];this.run={kills:0,treasures:0,damage:0,fragments:0,finished:false};}
 refreshStats(){const old=this.stats.maxhp;this.stats=statsFor(this.hero,this.relics,this.gold);this.stats.maxhp+=(this.level-1)*4;this.stats.damage+=(this.level-1)*.035;if(this.stats.maxhp>old)this.player.hp+=this.stats.maxhp-old;this.player.hp=Math.min(this.player.hp,this.stats.maxhp);}
 start(){this.resetWorld();this.state='running';this.room=0;this.rng=createRng(Date.now()&0xffffffff);this.discover('heroes',this.hero.id);this.discover('weapons',this.weapon.id);this.discover('supplies','tea');this.save.runs++;this.persist();this.enterRoom();this.emit('started');this.emit('refresh');this.emit('toast',{text:'远征开始 · 探索发光宝箱，收集地面掉落'});}
 enterRoom(){this.roomTime=0;this.roomClear=false;this.enemies=[];this.projectiles=[];this.effects=[];this.drops=[];this.turrets=[];this.boss=null;this.wave=0;this.waveDelay=0;this.chest={x:210+this.rng()*160,y:560+this.rng()*70,open:false};this.player.x=430;this.player.y=470;this.player.invuln=1.2;this.player.shield=Math.max(this.player.shield,this.stats.shield);this.player.skillCd=0;this.player.dodgeCd=0;this.state='running';this.spawnWave();this.emit('room');this.emit('refresh');}
 enemy(type,x,y,boss=false){const n=this.room;const data={crawler:{hp:42+8*n,speed:82+3*n,radius:15,damage:9+n},sentry:{hp:49+9*n,speed:43,radius:16,damage:10+n},brute:{hp:100+15*n,speed:58+2*n,radius:23,damage:16+n},leaper:{hp:37+8*n,speed:130+4*n,radius:13,damage:8+n},wisp:{hp:42+8*n,speed:70,radius:14,damage:11+n},mini:{hp:20+4*n,speed:136,radius:10,damage:6+n}}[type]||{};const hp=boss?620+Math.floor(n/3)*320:data.hp;return{id:this.nextId++,type,x,y,px:x,py:y,radius:boss?35:data.radius,hp,maxhp:hp,speed:boss?62:data.speed,damage:boss?23+n:data.damage,boss,cd:1.4+this.rng(),flash:0,slow:0,freeze:0,burn:0,poison:0,dotCd:.5,dead:false,phase:0,anim:this.rng()*6,angle:0,telegraph:null};}
 spawnWave(){const plan=roomPlan(this.room);if(plan.boss){if(this.wave===0){this.boss=this.enemy('boss',640,260,true);this.enemies.push(this.boss);for(let i=0;i<3;i++)this.spawnRandom(i%2?'sentry':'crawler');}this.wave=2;return;}this.wave++;const types=['crawler','sentry','crawler','leaper','brute','wisp'];const count=4+Math.min(3,Math.floor(this.room/2))+(this.wave===2?1:0);for(let i=0;i<count;i++)this.spawnRandom(types[Math.floor(this.rng()*Math.min(types.length,3+this.room))]);if(this.wave>1)this.emit('toast',{text:'第二波 · 遗迹的守卫被惊醒了'});}
 spawnRandom(type){let x,y;for(let i=0;i<20;i++){x=75+this.rng()*745;y=75+this.rng()*745;if(dist({x,y},this.player)>255)break;}const e=this.enemy(type,x,y);this.enemies.push(e);this.burst(x,y,'#b0c088',9);return e;}
 heal(value){this.player.hp=clamp(this.player.hp+value*this.stats.healing,0,this.stats.maxhp);}
 movePlayer(dx,dy){const p=this.player;const x=clamp(p.x+dx,50,846),y=clamp(p.y+dy,50,846);if(!this.obstacles.some(o=>Math.hypot(x-o.x,y-o.y)<o.r+p.radius)){p.x=x;p.y=y;}else{if(!this.obstacles.some(o=>Math.hypot(x-o.x,p.y-o.y)<o.r+p.radius))p.x=x;if(!this.obstacles.some(o=>Math.hypot(p.x-o.x,y-o.y)<o.r+p.radius))p.y=y;}}
 update(dt){this.t+=dt;if(this.state==='lobby'){this.player.angle=-.65+Math.sin(this.t*.22)*.18;return;}if(!['running','cleared'].includes(this.state))return;if(this.hitStop>0){this.hitStop-=dt;return;}const p=this.player,s=this.stats;this.runTime+=dt;this.roomTime+=dt;p.attackCd=Math.max(0,p.attackCd-dt);p.skillCd=Math.max(0,p.skillCd-dt);p.dodgeCd=Math.max(0,p.dodgeCd-dt);p.invuln=Math.max(0,p.invuln-dt);p.anim=Math.max(0,p.anim-dt);p.buff=Math.max(0,p.buff-dt);p.critBuff=Math.max(0,p.critBuff-dt);this.hurtCd=Math.max(0,this.hurtCd-dt);if(s.regen)this.heal(s.regen*dt);
  let sx=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0),sy=(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0)-(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0);let dx=sx+sy,dy=sy-sx;const len=Math.hypot(dx,dy);p.moving=len>0;if(len){dx/=len;dy/=len;}
  if(p.dash>0){p.dash-=dt;this.movePlayer(p.dashX*740*dt,p.dashY*740*dt);if(this.rng()<.6)this.effects.push({type:'ghost',x:p.x,y:p.y,time:.25,max:.25,angle:p.angle});}else if(len)this.movePlayer(dx*s.speed*dt,dy*s.speed*dt);
  const ax=this.aim.x-p.x,ay=this.aim.y-p.y;if(Math.hypot(ax,ay)>10)p.angle=Math.atan2(ay,ax);
  if(this.holding&&this.state==='running')this.attack();
  this.updateEffects(dt);this.updateDrops(dt);this.updateProjectiles(dt);this.updateEnemies(dt);this.updateTurrets(dt);
  if(this.state==='dead'||this.state==='victory')return;
  if(s.counts.frost>=6){this.freezeClock-=dt;if(this.freezeClock<=0){this.freezeClock=8;this.enemies.forEach(e=>e.freeze=1);this.ring(p.x,p.y,800,'#b5e0df',.6);}}
  if(this.pendingLevels>0&&['running','cleared'].includes(this.state)){this.pendingLevels--;this.offerRelics('level');return;}
  if(!this.enemies.some(e=>!e.dead)&&this.state==='running'){if(this.wave<2){this.waveDelay+=dt;if(this.waveDelay>1.2){this.waveDelay=0;this.spawnWave();}}else if(!this.roomClear){this.clearRoom();}}
 }
 attack(copy=false){const p=this.player;if(!copy&&(this.state!=='running'||p.attackCd>0))return;const w=this.weapon,angle=p.angle;const crit=this.rng()<this.stats.crit+(p.critBuff>0?.25:0);let damage=attackDamage(this.hero,w,this.stats,crit)*(p.buff>0?1.5:1)*(copy?.5:1);if(!copy){this.combo=(this.combo+1)%3;this.attacks++;p.attackCd=w.cd/this.stats.attackSpeed;p.anim=.57;this.sound('attack');}
  const tag=w.tag;const color={ember:'#ed9b67',frost:'#b4dee0',storm:'#e0ca79',venom:'#bdd382',echo:'#cdb4df',iron:'#d8dec3'}[tag];
  if(meleeTypes.has(w.type)){let range=w.range;if(w.special==='combo'&&this.combo===0){damage*=2;range*=1.3;}this.effects.push({type:w.type==='spear'?'thrust':w.type==='hammer'?'slam':'slash',x:p.x,y:p.y,angle,range,time:.25,max:.25,color});let hit=0;for(const e of [...this.enemies]){if(e.dead)continue;if(inMeleeArc(p,e,angle,{...w,range})){let d=damage;if(w.special==='tip'&&dist(p,e)>range*.65)d*=1.5;this.hit(e,d,{tag,crit});this.knockback(e,angle,w.type==='hammer'?65:18);hit++;}}if(hit){this.sound('hit');this.hitStop=w.type==='hammer'?.04:.018;}if(w.special==='field')this.effects.push({type:'field',x:p.x+Math.cos(angle)*90,y:p.y+Math.sin(angle)*90,range:105,time:3,max:3,color,tick:0});if(w.special==='echo'&&!copy){const e=this.nearest(p);if(e)this.shootAt(e,angle+Math.PI,damage*.45,'echo',true);}}
  else{let count=w.special==='triple'?3:w.special==='shotgun'?5:w.special==='double'?2:1;count+=this.stats.extraShot;for(let i=0;i<count;i++){const spread=w.special==='shotgun'?.15:.11;this.shoot(angle+(i-(count-1)/2)*spread,damage,w.range,tag,{homing:w.type==='book',pierce:w.special==='pierce'||w.name==='落日'?2:0,explode:w.special==='explode',radius:w.type==='staff'?9:4,speed:w.type==='gun'?630:w.type==='bow'?540:330});}}
  if(!copy&&this.stats.echo&&this.attacks%((this.stats.counts.echo||0)>=6?3:4)===0)this.attack(true);
 }
 shoot(angle,damage,range,tag,opts={}){const p=this.player;this.projectiles.push({id:this.nextId++,x:p.x+Math.cos(angle)*24,y:p.y+Math.sin(angle)*24,vx:Math.cos(angle)*(opts.speed||380),vy:Math.sin(angle)*(opts.speed||380),damage,tag,life:range/(opts.speed||380),radius:opts.radius||6,hostile:false,hitIds:new Set(),...opts});}
 shootAt(target,angle,damage,tag,homing=false){this.shoot(angle,damage,800,tag,{homing,speed:300});}
 nearest(from,max=Infinity){return this.enemies.filter(e=>!e.dead&&dist(e,from)<max).sort((a,b)=>dist(a,from)-dist(b,from))[0];}
 hit(e,damage,{tag='iron',crit=false,secondary=false}={}){if(e.dead||damage<=0)return;e.hp-=damage;e.flash=.13;this.run.damage+=damage;this.particles.push({type:'number',x:e.x,y:e.y-10,vy:-30,time:.75,max:.75,text:Math.round(damage)+(crit?'!':''),color:crit?'#f5d78b':'#e4e8d0'});if(!secondary){if(tag==='ember'||this.stats.burn)e.burn=Math.max(e.burn,3);if(tag==='venom'||this.stats.poison)e.poison=Math.max(e.poison,this.hero.passiveId==='healer'?6:4);if(tag==='frost'||this.stats.slow)e.slow=3;if(tag==='frost'&&this.weapon.type==='hammer')e.freeze=.8;this.heal(damage*this.stats.lifeSteal);let chain=this.stats.chain+(tag==='storm'?1:0);if(chain>0){const targets=this.enemies.filter(o=>!o.dead&&o.id!==e.id&&dist(e,o)<220).sort((a,b)=>dist(e,a)-dist(e,b)).slice(0,chain);for(const target of targets){this.effects.push({type:'lightning',x:e.x,y:e.y,tx:target.x,ty:target.y,time:.18,max:.18,color:'#e2cf89'});this.hit(target,damage*.32,{tag:'storm',secondary:true});}}}
  this.burst(e.x,e.y,tag==='ember'?'#edb074':'#c4d3a3',crit?7:3);if(e.hp<=0)this.kill(e);
 }
 kill(e){if(e.dead)return;e.dead=true;this.run.kills++;this.run.fragments+=e.boss?20:1;this.burst(e.x,e.y,BIOMES[roomPlan(this.room).act].accent,e.boss?45:15);this.drops.push({id:this.nextId++,type:'xp',x:e.x-10,y:e.y,value:e.boss?65:8+(e.type==='brute'?7:0),time:0});this.drops.push({id:this.nextId++,type:'gold',x:e.x+10,y:e.y+9,value:e.boss?40:3+Math.floor(this.rng()*6),time:0});if(this.rng()<.10)this.drops.push({id:this.nextId++,type:'heal',x:e.x,y:e.y+20,value:10,time:0});this.heal(this.stats.killHeal);if(this.hero.passiveId==='reaper'&&this.run.kills%8===0)this.heal(5);if(this.stats.explode){this.ring(e.x,e.y,110,'#efb27c');for(const o of [...this.enemies])if(!o.dead&&dist(e,o)<110)this.hit(o,18,{tag:'ember',secondary:true});}if(e.boss)this.sound('boss');}
 knockback(e,angle,force){if(e.boss)force*=.2;e.x=clamp(e.x+Math.cos(angle)*force,45,850);e.y=clamp(e.y+Math.sin(angle)*force,45,850);}
 hurt(value,source){const p=this.player;if(p.invuln>0||this.hurtCd>0||this.state!=='running')return;let amount=value*(1-this.stats.armor);const absorb=Math.min(p.shield,amount);p.shield-=absorb;amount-=absorb;p.hp-=amount;this.hurtCd=.65;p.invuln=.45;this.emit('hurt');this.sound('hurt');this.burst(p.x,p.y,'#d18b70',12);if(this.stats.thorns){this.ring(p.x,p.y,130,'#cdd4c7');this.enemies.filter(e=>!e.dead&&dist(p,e)<130).forEach(e=>this.hit(e,this.stats.thorns,{secondary:true}));}if(source)this.knockback(p,Math.atan2(p.y-source.y,p.x-source.x),13);if(p.hp<=0){if(this.stats.revive>0){const id=this.relics.find(id=>RELICS.find(r=>r.id===id)?.effect.revive);this.relics=this.relics.filter(r=>r!==id);this.refreshStats();p.hp=this.stats.maxhp*.4;p.invuln=2;this.emit('toast',{text:'遗物唤回了你 · 一次复活机会已消耗'});this.ring(p.x,p.y,200,'#dfd6a1');this.emit('refresh');}else this.finish(false);}}
 dodge(){const p=this.player;if(!['running','cleared'].includes(this.state)||p.dodgeCd>0)return;let sx=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0),sy=(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0)-(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0);let dx=sx+sy,dy=sy-sx;if(!dx&&!dy){dx=Math.cos(p.angle);dy=Math.sin(p.angle);}const l=Math.hypot(dx,dy);p.dashX=dx/l;p.dashY=dy/l;p.dash=.20;p.invuln=.30;p.dodgeCd=1.5*(1-this.stats.dodge);if(this.hero.passiveId==='melee')this.enemies.filter(e=>!e.dead&&dist(p,e)<110).forEach(e=>this.hit(e,15,{tag:'storm',secondary:true}));this.sound('dodge');}
 skill(){const p=this.player;if(this.state!=='running'||p.skillCd>0)return;p.skillCd=this.hero.cooldown*(1-this.stats.cooldown);const mul=this.stats.skillDamage*this.stats.damage;this.ring(p.x,p.y,220,BIOMES[roomPlan(this.room).act].accent,.7);this.sound('skill');switch(this.hero.id){case'ranger':this.enemies.filter(e=>!e.dead&&dist(p,e)<265).forEach(e=>{e.slow=4;this.hit(e,38*mul,{tag:'venom'});});break;case'knight':p.shield+=36;this.enemies.filter(e=>!e.dead&&dist(p,e)<210).forEach(e=>this.hit(e,30*mul,{tag:'iron'}));break;case'witch':this.enemies.filter(e=>!e.dead&&dist(p,e)<280).forEach(e=>this.hit(e,65*mul,{tag:'ember'}));break;case'rogue':{const ox=p.x,oy=p.y;this.movePlayer(Math.cos(p.angle)*230,Math.sin(p.angle)*230);p.invuln=.6;this.effects.push({type:'lightning',x:ox,y:oy,tx:p.x,ty:p.y,time:.5,max:.5,color:'#d5bbdf'});this.enemies.filter(e=>!e.dead&&segmentHit(ox,oy,p.x,p.y,e,40)).forEach(e=>this.hit(e,70*mul,{tag:'echo'}));break;}case'tinker':this.turrets.push({x:p.x,y:p.y,time:8,cd:0,damage:20*mul});break;case'oracle':this.heal(12);this.enemies.filter(e=>!e.dead&&dist(p,e)<320).forEach(e=>{e.freeze=2.5;});break;case'monk':this.enemies.filter(e=>!e.dead&&dist(p,e)<240).forEach(e=>{this.hit(e,80*mul,{tag:'storm'});this.knockback(e,Math.atan2(e.y-p.y,e.x-p.x),100);});break;case'botanist':this.heal(28);this.enemies.filter(e=>!e.dead&&dist(p,e)<300).forEach(e=>this.hit(e,12*mul,{tag:'venom'}));break;case'warden':for(let i=0;i<3;i++)this.shoot(p.angle+(i-1)*.5,45*mul,850,'echo',{homing:true,speed:290});break;case'corsair':{const target=this.nearest(p);if(target)this.hit(target,110*mul,{tag:'storm'});p.critBuff=6;break;}}this.emit('refresh');}
 useSupply(){if(!['running','cleared'].includes(this.state))return;const id=this.activeSupply;if(!this.supplies[id]){this.emit('toast',{text:'没有这件补给了 · 可从房间宝箱获得'});return;}const item=SUPPLIES.find(s=>s.id===id),p=this.player;this.supplies[id]--;switch(item.action){case'heal':this.heal(item.value);break;case'healPercent':this.heal(this.stats.maxhp*item.value);break;case'shield':p.shield+=item.value;break;case'freeze':this.enemies.filter(e=>!e.dead).forEach(e=>e.freeze=item.value);break;case'reset':p.skillCd=0;p.dodgeCd=0;break;case'buff':p.buff=item.value;break;case'magnet':this.drops.forEach(d=>this.collect(d));this.drops=[];break;case'bomb':this.ring(this.aim.x,this.aim.y,180,'#edac76');this.enemies.filter(e=>!e.dead&&dist(e,this.aim)<180).forEach(e=>this.hit(e,item.value,{tag:'ember'}));break;}this.sound('pickup');this.emit('toast',{text:`使用了 ${item.name}`});this.emit('refresh');}
 updateProjectiles(dt){for(const b of this.projectiles){b.life-=dt;if(b.life<=0)continue;const ox=b.x,oy=b.y;if(b.homing&&!b.hostile){const target=this.nearest(b,650);if(target){const speed=Math.hypot(b.vx,b.vy),a=Math.atan2(target.y-b.y,target.x-b.x),factor=Math.min(1,dt*5);b.vx+=(Math.cos(a)*speed-b.vx)*factor;b.vy+=(Math.sin(a)*speed-b.vy)*factor;}}b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<25||b.x>875||b.y<25||b.y>875){b.life=0;continue;}if(b.hostile){if(segmentHit(ox,oy,b.x,b.y,this.player,b.radius)){this.hurt(b.damage,b);b.life=0;}}else{for(const e of [...this.enemies]){if(e.dead||b.hitIds.has(e.id))continue;if(segmentHit(ox,oy,b.x,b.y,e,b.radius)){b.hitIds.add(e.id);this.hit(e,b.damage,{tag:b.tag});if(b.explode){this.ring(b.x,b.y,105,'#e9b37c');this.enemies.filter(o=>!o.dead&&o.id!==e.id&&dist(o,b)<105).forEach(o=>this.hit(o,b.damage*.45,{tag:b.tag,secondary:true}));}if(b.pierce>0)b.pierce--;else b.life=0;this.sound('hit');if(b.life<=0)break;}}}}this.projectiles=this.projectiles.filter(b=>b.life>0);}
 updateEnemies(dt){const p=this.player;for(const e of [...this.enemies]){if(e.dead)continue;e.anim+=dt;e.flash=Math.max(0,e.flash-dt);e.freeze=Math.max(0,e.freeze-dt);e.slow=Math.max(0,e.slow-dt);e.burn=Math.max(0,e.burn-dt);e.poison=Math.max(0,e.poison-dt);e.dotCd-=dt;if(e.dotCd<=0){e.dotCd=.5;const burn=e.burn?5*((this.stats.counts.ember||0)>=3?2:1):0,poison=e.poison?4*((this.stats.counts.venom||0)>=3?2:1):0;if(burn+poison)this.hit(e,burn+poison,{tag:e.burn?'ember':'venom',secondary:true});}if(e.dead||e.freeze>0)continue;e.cd-=dt;e.angle=Math.atan2(p.y-e.y,p.x-e.x);if(e.telegraph){e.telegraph.time-=dt;if(e.telegraph.time<=0){this.enemyAttack(e);e.telegraph=null;e.cd=e.boss?1.9:1.6;}continue;}const d=dist(e,p);let targetDistance=e.type==='sentry'||e.type==='wisp'?260:e.boss?135:48;if(d>targetDistance){const speed=e.speed*(e.slow?(this.hero.id==='oracle'||(this.stats.counts.frost||0)>=3?.35:.5):1);e.x+=Math.cos(e.angle)*speed*dt;e.y+=Math.sin(e.angle)*speed*dt;}else if(d<targetDistance-65&&(e.type==='sentry'||e.type==='wisp')){e.x-=Math.cos(e.angle)*e.speed*dt*.65;e.y-=Math.sin(e.angle)*e.speed*dt*.65;}if(e.cd<=0&&(e.boss||d<(e.type==='sentry'||e.type==='wisp'?650:90))){const mode=e.boss?e.phase%3:e.type==='sentry'||e.type==='wisp'?'shot':'melee';e.telegraph={mode,time:e.boss?.9:.55,max:e.boss?.9:.55,x:p.x,y:p.y,angle:e.angle};}e.x=clamp(e.x,44,852);e.y=clamp(e.y,44,852);}
  // Soft separation keeps groups readable without hiding projectiles or telegraphs.
  const alive=this.enemies.filter(e=>!e.dead);for(let i=0;i<alive.length;i++)for(let j=i+1;j<alive.length;j++){const a=alive[i],b=alive[j],d=dist(a,b),min=a.radius+b.radius+3;if(d<min&&d>.1){const f=(min-d)*.15,dx=(a.x-b.x)/d*f,dy=(a.y-b.y)/d*f;a.x+=dx;a.y+=dy;b.x-=dx;b.y-=dy;}}
 }
 enemyAttack(e){
  const g=e.telegraph;
  if(e.boss){
   const act=roomPlan(this.room).act;e.phase++;
   if(g.mode===0){
    const range=act===1?210:195;this.ring(e.x,e.y,range,act===1?'#e6a26e':'#db8e75',.65);
    if(dist(e,this.player)<range)this.hurt(e.damage*1.25,e);
    if(act===1)this.effects.push({type:'hostileField',x:e.x,y:e.y,range:150,time:3.5,max:3.5,color:'#e6a26e',tick:0,damage:11});
   }else if(g.mode===1){
    const count=act===2?24:act===1?18:16,speed=act===1?220:act===2?200:185;
    for(let i=0;i<count;i++)this.enemyBullet(e,i*Math.PI*2/count,speed,5.5);
   }else{
    const x=e.x,y=e.y;e.x=clamp(g.x,60,838);e.y=clamp(g.y,60,838);
    this.effects.push({type:'lightning',x,y,tx:e.x,ty:e.y,time:.45,max:.45,color:'#d7a282'});
    if(segmentHit(x,y,e.x,e.y,this.player,32))this.hurt(e.damage,e);
    if(act===2)for(let i=0;i<4;i++)this.enemyBullet(e,i*Math.PI/2+Math.PI/4,260,3.5);
   }
   if(e.phase%3===0&&this.enemies.filter(x=>!x.dead).length<7)this.spawnRandom(act===2?'wisp':act===1?'brute':'crawler');
  }else if(g.mode==='shot'){
   this.enemyBullet(e,g.angle,220,4);if(e.type==='wisp'){this.enemyBullet(e,g.angle+.2,190,4);this.enemyBullet(e,g.angle-.2,190,4);}
  }else{this.ring(e.x,e.y,78,'#d98e7b',.3);if(dist(e,this.player)<80)this.hurt(e.damage,e);}
 }
 enemyBullet(e,angle,speed,life){this.projectiles.push({id:this.nextId++,x:e.x,y:e.y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life,radius:e.boss?9:7,hostile:true,damage:e.damage,tag:'enemy'});}
 updateTurrets(dt){for(const t of this.turrets){t.time-=dt;t.cd-=dt;if(t.cd<=0){const target=this.nearest(t,650);if(target){t.cd=.48;const a=Math.atan2(target.y-t.y,target.x-t.x);this.projectiles.push({id:this.nextId++,x:t.x,y:t.y,vx:Math.cos(a)*450,vy:Math.sin(a)*450,damage:t.damage,tag:'iron',life:1.8,radius:5,hostile:false,hitIds:new Set()});}}}this.turrets=this.turrets.filter(t=>t.time>0);}
 updateDrops(dt){for(const d of this.drops){d.time+=dt;const l=dist(d,this.player);if(l<this.stats.magnet){const speed=Math.min(650,200+d.time*15);d.x+=(this.player.x-d.x)/(l||1)*speed*dt;d.y+=(this.player.y-d.y)/(l||1)*speed*dt;}if(dist(d,this.player)<22){this.collect(d);d.collected=true;}}this.drops=this.drops.filter(d=>!d.collected);}
 collect(d){if(d.collected)return;if(d.type==='xp'){this.xp+=Math.round(d.value*this.stats.xp);while(this.xp>=this.nextXp){this.xp-=this.nextXp;this.level++;this.nextXp=Math.round(this.nextXp*1.2);this.pendingLevels++;this.refreshStats();if(this.hero.passiveId==='ember')this.heal(8);}}else if(d.type==='gold'){const value=Math.round(d.value*this.stats.gold);const old=this.gold;this.gold+=value;if(this.hero.passiveId==='collector')this.heal((Math.floor(this.gold/10)-Math.floor(old/10))*4);this.refreshStats();}else this.heal(d.value);this.sound('pickup');d.collected=true;}
 interact(){if(this.state==='cleared'){this.nextRoom();return;}if(this.state!=='running')return;if(!this.chest.open&&dist(this.chest,this.player)<120)this.openChest();else this.emit('toast',{text:this.chest.open?'击败守卫后，按 F 前往下一层。':'靠近金色宝箱，按 F 开启。'});}
 openChest(){if(this.chest.open)return;this.chest.open=true;this.run.treasures++;this.run.fragments+=8;this.gold+=15+this.room*3;const item=SUPPLIES[Math.floor(this.rng()*SUPPLIES.length)];this.supplies[item.id]=(this.supplies[item.id]||0)+1;this.discover('supplies',item.id);this.refreshStats();this.offerWeapons();this.emit('toast',{text:`发现秘匣 · 获得 ${item.name} 与 8 枚遗迹碎片`});}
 offerWeapons(){this.returnState=this.state;this.state='choice';this.choiceKind='weapon';this.currentChoices=weaponChoices(this.weapon.id,this.rng,Math.min(4,3+(this.hero.id==='tinker'?1:0)));this.emit('choice',{kind:'weapon',items:this.currentChoices,source:'chest'});}
 offerRelics(source){const count=Math.min(4,3+this.stats.choice);const options=rewardChoices(this.relics,this.rng,count);if(!options.length){this.heal(25);if(source==='room')this.state='cleared';return;}this.returnState=source==='room'?'cleared':this.state;this.state='choice';this.choiceKind='relic';this.currentChoices=options;this.emit('choice',{kind:'relic',items:options,source});this.sound('level');}
 choose(id){if(this.state!=='choice'||!this.currentChoices?.some(x=>x.id===id))return;if(this.choiceKind==='weapon'){this.weapon=byWeapon(id);this.discover('weapons',id);}else{this.relics.push(id);this.discover('relics',id);this.refreshStats();}this.state=this.returnState;this.holding=false;this.currentChoices=null;this.emit('choice-done');this.emit('refresh');}
 skipWeapon(){if(this.state!=='choice'||this.choiceKind!=='weapon')return;this.state=this.returnState;this.currentChoices=null;this.emit('choice-done');this.emit('refresh');}
 clearRoom(){this.roomClear=true;this.state='cleared';this.run.fragments+=12;this.heal(12);this.drops.forEach(d=>this.collect(d));this.drops=[];this.projectiles=[];this.emit('toast',{text:'区域已净化 · 获得一件遗物，并恢复 12 生命'});this.emit('refresh');this.offerRelics('room');}
 nextRoom(){if(this.state!=='cleared')return;if(!this.chest.open){this.openChest();this.returnState='cleared';return;}if(this.room===8){this.finish(true);return;}this.room++;this.enterRoom();}
 pause(){if(this.state==='running'||this.state==='cleared'){this.beforePause=this.state;this.state='paused';this.holding=false;this.keys.clear();this.emit('paused');}}
 resume(){if(this.state!=='paused')return;this.state=this.beforePause||'running';this.emit('resumed');}
 finish(won){if(this.run.finished)return;this.run.finished=true;this.state=won?'victory':'dead';this.holding=false;this.keys.clear();this.run.award=Math.floor(this.run.fragments*(won?1:.4));this.save.bank+=this.run.award;this.save.best=Math.max(this.save.best,this.room+1);if(won)this.save.wins++;this.persist();this.emit('finished',{won,run:this.run});}
 abandon(){this.finish(false);}
 lobby(){this.state='lobby';this.room=0;this.resetWorld();this.emit('lobby');this.emit('refresh');}
 updateEffects(dt){for(const effect of this.effects){effect.time-=dt;if(effect.type==='field'||effect.type==='hostileField'){effect.tick-=dt;if(effect.tick<=0){effect.tick=.5;if(effect.type==='hostileField'){if(dist(this.player,effect)<effect.range)this.hurt(effect.damage,effect);}else this.enemies.filter(e=>!e.dead&&dist(e,effect)<effect.range).forEach(e=>this.hit(e,8,{tag:'ember',secondary:true}));}}}this.effects=this.effects.filter(e=>e.time>0);for(const p of this.particles){p.time-=dt;p.y+=(p.vy||0)*dt;if(p.type!=='number'){p.x+=(p.vx||0)*dt;p.vy=(p.vy||0)+25*dt;}}this.particles=this.particles.filter(p=>p.time>0);if(this.particles.length>500)this.particles.splice(0,this.particles.length-500);}
 burst(x,y,color,count){for(let i=0;i<count;i++){const a=this.rng()*Math.PI*2,v=20+this.rng()*80;this.particles.push({type:'pixel',x,y,color,vx:Math.cos(a)*v,vy:Math.sin(a)*v-20,time:.3+this.rng()*.45,max:.75});}}
 ring(x,y,range,color,time=.4){this.effects.push({type:'ring',x,y,range,color,time,max:time});}
 sound(type){if(this.muted)return;try{this.audio||=new (window.AudioContext||window.webkitAudioContext)();if(this.audio.state==='suspended')this.audio.resume();const now=this.audio.currentTime,o=this.audio.createOscillator(),g=this.audio.createGain();const frequencies={attack:220,hit:100,pickup:730,hurt:80,dodge:310,skill:480,level:860,boss:140};o.type=type==='hurt'?'sawtooth':'triangle';o.frequency.setValueAtTime(frequencies[type]||300,now);o.frequency.exponentialRampToValueAtTime((frequencies[type]||300)*.55,now+.08);g.gain.setValueAtTime(type==='pickup'?.025:.045,now);g.gain.exponentialRampToValueAtTime(.001,now+.09);o.connect(g);g.connect(this.audio.destination);o.start(now);o.stop(now+.1);}catch{}}
}
