import {HEROES,BIOMES,TAGS} from './data.js';
import {roomPlan,createRng,clamp} from './rules.js';
const rows=['se','sw','ne','nw','e','w','s','n'];
const angles=[Math.PI/4,3*Math.PI/4,-Math.PI/4,-3*Math.PI/4,0,Math.PI,Math.PI/2,-Math.PI/2];
export const SPRITES={};
export async function loadSprites(){await Promise.all(HEROES.flatMap(hero=>['idle','walk','run','attack'].map(cycle=>new Promise(resolve=>{const im=new Image();im.onload=()=>{SPRITES[hero.id+'_'+cycle]=im;resolve();};im.onerror=resolve;im.src=`assets/${hero.id}_${cycle}.png`;}))));}
export function directionRow(angle){const sx=Math.cos(angle)-Math.sin(angle),sy=(Math.cos(angle)+Math.sin(angle))*.527;const a=Math.atan2(sy,sx);let index=0,best=Infinity;for(let i=0;i<8;i++){const diff=Math.abs(Math.atan2(Math.sin(a-angles[i]),Math.cos(a-angles[i])));if(diff<best){best=diff;index=i;}}return index;}
export function portrait(canvas,id,frame=0){const ctx=canvas.getContext('2d');canvas.width=80;canvas.height=88;ctx.clearRect(0,0,80,88);ctx.imageSmoothingEnabled=false;const im=SPRITES[id+'_idle'];if(im)ctx.drawImage(im,frame*80,0,80,88,0,0,80,88);}
export class Renderer{
 constructor(canvas,game){this.canvas=canvas;this.game=game;this.ctx=canvas.getContext('2d',{alpha:false});this.zoom=.7;this.shake=0;this.lastRoom=-1;this.floor=document.createElement('canvas');this.resize();this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas);game.addEventListener('hurt',()=>this.shake=.25);}
 resize(){this.w=this.canvas.clientWidth||800;this.h=this.canvas.clientHeight||600;this.dpr=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.round(this.w*this.dpr);this.canvas.height=Math.round(this.h*this.dpr);this.zoom=Math.min((this.w-52)/1328,(this.h-130)/700,1.35);this.zoom=Math.max(.23,this.zoom);this.cx=this.w/2;this.cy=this.h*.55;this.floor.width=this.canvas.width;this.floor.height=this.canvas.height;this.cacheFloor();}
 project(x,y,z=0){return{x:this.cx+(x-y)*.74*this.zoom,y:this.cy+(x+y-896)*.39*this.zoom-z*this.zoom};}
 unproject(sx,sy){const dx=(sx-this.cx)/(.74*this.zoom),dy=(sy-this.cy)/(.39*this.zoom)+896;return{x:(dx+dy)/2,y:(dy-dx)/2};}
 path(points,fill,stroke=null,width=1){const c=this.ctx;c.beginPath();points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();if(fill){c.fillStyle=fill;c.fill();}if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.stroke();}}
 ellipse(x,y,rx,ry,color){const p=this.project(x,y),c=this.ctx;c.fillStyle=color;c.beginPath();c.ellipse(p.x,p.y,rx*this.zoom,ry*this.zoom,0,0,Math.PI*2);c.fill();}
 prism(x,y,w,d,h,top,left,right,stroke='#23332b',base=0){const b=[this.project(x,y,base),this.project(x+w,y,base),this.project(x+w,y+d,base),this.project(x,y+d,base)],t=[this.project(x,y,h+base),this.project(x+w,y,h+base),this.project(x+w,y+d,h+base),this.project(x,y+d,h+base)];this.path([t[3],t[2],b[2],b[3]],left,stroke);this.path([t[1],t[2],b[2],b[1]],right,stroke);this.path(t,top,stroke);}
 cacheFloor(){if(!this.floor||!this.canvas.width)return;const original=this.ctx;this.ctx=this.floor.getContext('2d',{alpha:false});const c=this.ctx;c.setTransform(this.dpr,0,0,this.dpr,0,0);const biome=BIOMES[roomPlan(this.game.room).act];const rng=createRng(931+this.game.room*1163);c.fillStyle='#18251f';c.fillRect(0,0,this.w,this.h);const gradient=c.createRadialGradient(this.w*.50,this.h*.43,10,this.w*.45,this.h*.55,this.w*.70);gradient.addColorStop(0,this.game.room<3?'#33402c':'#303830');gradient.addColorStop(1,'#16231e');c.fillStyle=gradient;c.fillRect(0,0,this.w,this.h);
  // Silhouettes, dust-lit shafts and a detached stone platform set the scene.
  c.fillStyle='#73846309';this.path([{x:this.w*.14,y:0},{x:this.w*.32,y:0},{x:this.w*.75,y:this.h},{x:this.w*.30,y:this.h}],'#c7cf9810');
  c.save();c.shadowColor='#06110c';c.shadowBlur=40;this.ellipse(448,465,680,305,'#0d1918a8');c.restore();
  const z=38*this.zoom;const left=[this.project(0,896),this.project(896,896),this.project(896,896),this.project(0,896)];left[2]={x:left[2].x,y:left[2].y+z};left[3]={x:left[3].x,y:left[3].y+z};this.path(left,biome.edge);const right=[this.project(896,0),this.project(896,896),this.project(896,896),this.project(896,0)];right[2]={x:right[2].x,y:right[2].y+z};right[3]={x:right[3].x,y:right[3].y+z};this.path(right,'#344036');
  for(let sum=0;sum<28;sum++)for(let x=0;x<14;x++){const y=sum-x;if(y<0||y>=14)continue;const wx=x*64,wy=y*64;const p=[this.project(wx,wy),this.project(wx+64,wy),this.project(wx+64,wy+64),this.project(wx,wy+64)];this.path(p,biome.floor[Math.floor(rng()*4)],'#313d3299',.65);this.path([this.project(wx+2,wy+2),this.project(wx+62,wy+2),this.project(wx+62,wy+62),this.project(wx+2,wy+62)],null,'#72816a25',.5);
    for(let n=0;n<8;n++){const a=wx+3+rng()*58,b=wy+3+rng()*58,pt=this.project(a,b);c.fillStyle=rng()>.5?'#adba861d':'#18291f38';c.fillRect(Math.floor(pt.x),Math.floor(pt.y),Math.max(1,this.zoom*4),Math.max(1,this.zoom*2));}
    if(rng()<.3){const a=wx+rng()*30,b=wy+rng()*40;this.path([this.project(a,b),this.project(a+18,b+5),this.project(a+21,b+18)],null,'#29362e88',1);}
    const edge=x===0||y===0||x===13||y===13;if(edge||rng()<.12){const a=wx+rng()*52,b=wy+rng()*52;this.moss(a,b,8+rng()*10,rng);}
  }
  // Faded circular seal in the middle.
  const center=this.project(450,445);c.strokeStyle='#a9b68b25';c.lineWidth=2*this.zoom;c.beginPath();c.ellipse(center.x,center.y,150*this.zoom,78*this.zoom,0,0,Math.PI*2);c.stroke();c.beginPath();c.ellipse(center.x,center.y,132*this.zoom,68*this.zoom,0,0,Math.PI*2);c.stroke();this.path([this.project(450,330),this.project(560,445),this.project(450,555),this.project(340,445)],null,'#a9b68b28',this.zoom);
  for(let i=0;i<14;i++){const p=this.project(i*64,896),q=this.project(896,i*64);c.strokeStyle='#1b2a2499';c.beginPath();c.moveTo(p.x,p.y);c.lineTo(p.x,p.y+z);c.moveTo(q.x,q.y);c.lineTo(q.x,q.y+z);c.stroke();}
  // Small roots trail below the platform.
  for(let i=0;i<28;i++){const p=this.project(i%2?896:rng()*896,i%2?rng()*896:896);c.fillStyle='#556445';c.fillRect(p.x,p.y+1,2*this.zoom,(8+rng()*25)*this.zoom);}
  this.ctx=original;this.lastRoom=this.game.room;this.makeProps();}
 moss(x,y,size,rng){const c=this.ctx;for(let i=0;i<7;i++){const p=this.project(x+(rng()-.5)*size*2,y+(rng()-.5)*size*2);c.fillStyle=['#667c493d','#8c9d5655','#b2bc7133'][i%3];c.fillRect(p.x,p.y,(3+rng()*8)*this.zoom,(2+rng()*4)*this.zoom);}}
 makeProps(){const rng=createRng(335+this.game.room*21);this.props=[{type:'column',x:180,y:155,h:112,w:39},{type:'column',x:670,y:725,h:82,w:42},{type:'column',x:745,y:525,h:64,w:30},{type:'column',x:142,y:665,h:74,w:34},{type:'arch',x:200,y:18,h:136},{type:'wall',x:15,y:80,h:97,length:260,axis:'y'},{type:'wall',x:430,y:18,h:82,length:300,axis:'x'},{type:'column',x:58,y:425,h:45,w:34},{type:'obelisk',x:817,y:235,h:96},{type:'tree',x:90,y:85,h:115},{type:'tree',x:810,y:800,h:88},{type:'bush',x:53,y:562},{type:'bush',x:545,y:795},{type:'bush',x:817,y:380},{type:'bush',x:380,y:55}];for(let i=0;i<24;i++){const side=i%4;const a=80+rng()*720,b=40+rng()*45;this.props.push({type:'rubble',x:side===0?b:side===1?896-b:a,y:side===2?b:side===3?896-b:a,h:4+rng()*11,w:10+rng()*15});}}
 drawColumn(o){const biome=BIOMES[roomPlan(this.game.room).act],h=o.h,w=o.w;this.ellipse(o.x+w/2,o.y+w/2,w*1.1,w*.5,'#101e1944');this.prism(o.x-7,o.y-7,w+14,w+14,9,'#69705a','#404c3d','#53604c');this.prism(o.x,o.y,w,w,h,'#7b826d','#45533f','#5b6852');for(let y=20;y<h;y+=24){const a=this.project(o.x,o.y+w,y),b=this.project(o.x+w,o.y+w,y),d=this.project(o.x+w,o.y,y);this.path([a,b,d],null,'#293f2f88',1);const t=this.project(o.x+w*.30,o.y+w,y+8);this.path([t,this.project(o.x+w*.30,o.y+w,y+22)],null,'#7d897655',2*this.zoom);}this.prism(o.x-5,o.y-5,w+10,w+10,8,'#89907c','#506049','#637258','#23332b',h);const p=this.project(o.x+w*.5,o.y+w*.6,h+9);this.ctx.fillStyle=biome.accent+'75';this.ctx.fillRect(p.x-6*this.zoom,p.y-3*this.zoom,13*this.zoom,4*this.zoom);for(let i=0;i<4;i++){const a=this.project(o.x+w,o.y+i*10,h-12-i*8);this.ctx.fillStyle='#739450';this.ctx.fillRect(a.x-3*this.zoom,a.y,6*this.zoom,(9+i*4)*this.zoom);}}
 drawWall(o){const length=o.length;for(let i=0;i<length;i+=48){const x=o.x+(o.axis==='x'?i:0),y=o.y+(o.axis==='y'?i:0);const h=o.h-(i>length*.65?30:i>length*.35?16:0);this.prism(x,y,42,42,h,'#7c846d','#45533e','#59654b');for(let k=22;k<h;k+=22)this.path([this.project(x,y+42,k),this.project(x+42,y+42,k),this.project(x+42,y,k)],null,'#2c3d2d88');if(i%96===0)this.bush(x+25,y+34,h);}}
 bush(x,y,z=0){const c=this.ctx;const rng=createRng(Math.floor(x*97+y*53));for(let i=0;i<19;i++){const a=rng()*Math.PI*2,r=5+rng()*27;const p=this.project(x+Math.cos(a)*r,y+Math.sin(a)*r,z+4+rng()*11);c.fillStyle=['#536b3a','#6c8247','#899954','#adba6e'][i%4];c.fillRect(Math.round(p.x),Math.round(p.y),Math.ceil((5+rng()*8)*this.zoom),Math.ceil((3+rng()*6)*this.zoom));}for(let i=0;i<3;i++){const p=this.project(x+i*8,y-i*4,z+9);c.fillStyle='#d3c588';c.fillRect(p.x,p.y,2*this.zoom,3*this.zoom);}}
 drawProp(o){const c=this.ctx;switch(o.type){case'column':this.drawColumn(o);break;case'wall':this.drawWall(o);break;case'arch':this.drawColumn({...o,w:35,h:o.h});this.drawColumn({...o,x:o.x+142,w:35,h:o.h});this.prism(o.x,o.y,177,35,20,'#929881','#5d6a52','#738064','#23332b',o.h);this.prism(o.x+25,o.y-5,130,45,10,'#9ba28b','#58674c','#728161','#23332b',o.h+20);this.bush(o.x+156,o.y+5,o.h+32);break;case'obelisk':this.prism(o.x,o.y,30,30,16,'#646d59','#40533f','#53674e');this.prism(o.x+6,o.y+6,18,18,o.h,'#8a9275','#556849','#6c7b59');{const p=this.project(o.x+15,o.y+26,o.h-26);c.strokeStyle='#c5cda2';c.lineWidth=this.zoom*2;c.beginPath();c.moveTo(p.x,p.y);c.lineTo(p.x-5*this.zoom,p.y+8*this.zoom);c.lineTo(p.x+2*this.zoom,p.y+16*this.zoom);c.stroke();}break;case'bush':this.bush(o.x,o.y);break;case'rubble':this.prism(o.x,o.y,o.w,o.w*.8,o.h,'#788168','#4b5846','#627153');break;case'tree':{const p=this.project(o.x,o.y),top=this.project(o.x,o.y,o.h);c.strokeStyle='#4b5b3d';c.lineWidth=9*this.zoom;c.beginPath();c.moveTo(p.x,p.y);c.lineTo(top.x,top.y);c.stroke();c.lineWidth=4*this.zoom;c.beginPath();c.moveTo(top.x,top.y+20*this.zoom);c.lineTo(top.x-27*this.zoom,top.y-3*this.zoom);c.moveTo(top.x,top.y+32*this.zoom);c.lineTo(top.x+31*this.zoom,top.y+8*this.zoom);c.stroke();this.bush(o.x,o.y,o.h);this.bush(o.x-30,o.y-10,o.h-7);this.bush(o.x+27,o.y+12,o.h-16);break;}}}
 drawChest(){const o=this.game.chest,t=this.game.t,c=this.ctx;this.ellipse(o.x+14,o.y+12,32,14,'#0c191880');if(!o.open){this.ellipse(o.x+15,o.y+14,48+Math.sin(t*3)*4,23,'#cfbf6424');for(let i=0;i<4;i++){const p=this.project(o.x+12+Math.sin(t+i*2)*17,o.y+12+Math.cos(t+i)*15,18+(t*13+i*7)%36);c.fillStyle='#e1cf83';c.fillRect(p.x,p.y,2,2);}}this.prism(o.x,o.y,34,28,27,o.open?'#7c7550':'#ad985d','#776b44','#95844e');this.prism(o.x-2,o.y-2,38,32,o.open?44:32,o.open?'#7c7651':'#c1ac70','#857448','#a29159');const p=this.project(o.x+18,o.y+29,20);c.fillStyle='#e7d18a';c.fillRect(p.x-4*this.zoom,p.y-2*this.zoom,7*this.zoom,8*this.zoom);if(!o.open){const label=this.project(o.x+16,o.y+14,61);c.font=`${Math.max(8,10*this.zoom)}px 'Microsoft YaHei'`;c.textAlign='center';c.fillStyle='#ddcf9c';c.fillText('秘匣',label.x,label.y);}}
 drawPortal(){const g=this.game,o=g.portal,c=this.ctx,t=g.t;this.prism(o.x-28,o.y-28,56,56,10,'#899373','#4f6548','#6d805c');this.prism(o.x-26,o.y-25,10,50,82,'#829274','#536e4e','#698664');this.prism(o.x+18,o.y-25,10,50,82,'#829274','#536e4e','#698664');this.prism(o.x-28,o.y-26,56,13,91,'#a2af8c','#607e59','#7a9570');const p=this.project(o.x,o.y,46);c.save();c.globalAlpha=g.roomClear?.65:.18;c.shadowColor='#cfdaa5';c.shadowBlur=g.roomClear?22:0;c.fillStyle='#b8ca8d';c.beginPath();c.ellipse(p.x,p.y,21*this.zoom,(37+Math.sin(t*2)*2)*this.zoom,0,0,Math.PI*2);c.fill();c.restore();if(g.roomClear){c.fillStyle='#e2e6c7';c.font=`${Math.max(8,10*this.zoom)}px 'Microsoft YaHei'`;c.textAlign='center';c.fillText(g.room===8?'归档出口':'下层入口',p.x,p.y-58*this.zoom);}}
 drawHero(o=this.game.player,alpha=1){const g=this.game,c=this.ctx;const cycle=o.anim>0?'attack':o.dash>0?'run':o.moving?'walk':'idle';const fps=cycle==='attack'?14:cycle==='run'?12:cycle==='walk'?8:5;let frame=cycle==='attack'?clamp(Math.floor((.57-o.anim)*fps),0,7):Math.floor(g.t*fps)%8;const row=directionRow(o.angle),im=SPRITES[g.hero.id+'_'+cycle],p=this.project(o.x,o.y);c.save();c.globalAlpha=alpha;if(o.invuln>0&&Math.floor(g.t*18)%2===0)c.globalAlpha*=.5;this.ellipse(o.x,o.y,24,11,'#0a171889');if(o.shield>0){c.strokeStyle='#bfddd980';c.lineWidth=1.5;c.beginPath();c.ellipse(p.x,p.y-27*this.zoom,27*this.zoom,37*this.zoom,0,0,Math.PI*2);c.stroke();}c.imageSmoothingEnabled=false;if(im)c.drawImage(im,frame*80,row*88,80,88,Math.round(p.x-40*this.zoom),Math.round(p.y-76*this.zoom),Math.round(80*this.zoom),Math.round(88*this.zoom));else{c.fillStyle=g.hero.color;c.fillRect(p.x-8,p.y-26,16,26);}
  // Weapons are independent of the body sprite, allowing all 24 loadouts.
  const w=g.weapon,back=['ne','nw','n'].includes(rows[row]),hand=this.project(o.x+Math.cos(o.angle)*17,o.y+Math.sin(o.angle)*17,28);c.strokeStyle=TAGS[w.tag].color;c.fillStyle=TAGS[w.tag].color;c.lineWidth=2*this.zoom;const ax=Math.cos(o.angle)-Math.sin(o.angle),ay=(Math.cos(o.angle)+Math.sin(o.angle))*.527,angle=Math.atan2(ay,ax);c.translate(hand.x,hand.y);c.rotate(angle);if(w.type==='bow'){c.beginPath();c.arc(0,0,17*this.zoom,-1.3,1.3);c.stroke();c.strokeStyle='#eadcaf';c.beginPath();c.moveTo(5*this.zoom,-16*this.zoom);c.lineTo(5*this.zoom,16*this.zoom);c.stroke();}else if(w.type==='staff'||w.type==='book'){c.rotate(-angle);c.strokeStyle='#9f9874';c.beginPath();c.moveTo(0,12*this.zoom);c.lineTo(0,-27*this.zoom);c.stroke();c.fillStyle=TAGS[w.tag].color;c.fillRect(-4*this.zoom,-31*this.zoom,8*this.zoom,9*this.zoom);}else if(w.type==='hammer'){c.fillRect(0,-1*this.zoom,23*this.zoom,3*this.zoom);c.fillRect(19*this.zoom,-8*this.zoom,11*this.zoom,16*this.zoom);}else if(w.type==='gun'){c.fillRect(0,-3*this.zoom,22*this.zoom,6*this.zoom);c.fillStyle='#6b7358';c.fillRect(3*this.zoom,0,5*this.zoom,9*this.zoom);}else{c.beginPath();c.moveTo(0,0);c.lineTo((w.type==='spear'?40:22)*this.zoom,0);c.stroke();c.fillRect(5*this.zoom,-4*this.zoom,2*this.zoom,8*this.zoom);}c.restore();}
 drawEnemy(e){const g=this.game,c=this.ctx,p=this.project(e.x,e.y),z=this.zoom;const color=e.flash>0?'#eef0dc':e.freeze>0?'#b8d8df':e.boss?BIOMES[roomPlan(g.room).act].bossColor:e.type==='sentry'?'#b5a580':e.type==='wisp'?'#bfb5c9':e.type==='brute'?'#a0ac78':'#9aab71';this.ellipse(e.x,e.y,e.radius*1.3,e.radius*.5,'#12201899');const bob=Math.sin(e.anim*7)*1.8*z;if(e.boss){this.prism(e.x-25,e.y-24,50,48,65,color,'#536344','#778461');this.prism(e.x-34,e.y-16,20,32,77,color,'#4b5b40','#748460');this.prism(e.x+17,e.y-16,20,32,77,color,'#4b5b40','#748460');this.prism(e.x-13,e.y-13,26,26,96,'#b5bd93','#667450','#879767');c.fillStyle='#ede2a3';c.fillRect(p.x-7*z,p.y-85*z,4*z,3*z);c.fillRect(p.x+4*z,p.y-85*z,4*z,3*z);if(g.room<3){this.bush(e.x-27,e.y-8,81);this.bush(e.x+20,e.y+4,82);}else if(g.room<6){c.fillStyle='#e8b173';c.fillRect(p.x-6*z,p.y-46*z,12*z,16*z);}else{c.strokeStyle='#d4c0e5';c.lineWidth=2*z;c.beginPath();c.arc(p.x,p.y-66*z,32*z,g.t,g.t+4.8);c.stroke();}}
  else if(e.type==='wisp'){c.fillStyle=color;c.beginPath();c.ellipse(p.x,p.y-28*z+bob,12*z,17*z,0,0,Math.PI*2);c.fill();c.fillStyle='#e6e1c3';c.fillRect(p.x-5*z,p.y-34*z+bob,3*z,3*z);c.fillRect(p.x+3*z,p.y-34*z+bob,3*z,3*z);c.fillStyle=color+'77';c.fillRect(p.x-5*z,p.y-12*z+bob,10*z,7*z);}
  else{const size=e.radius;this.prism(e.x-size*.7,e.y-size*.7,size*1.4,size*1.4,e.type==='brute'?38:24,color,'#536540','#788757');const hp=this.project(e.x,e.y,e.type==='brute'?38:24);c.fillStyle='#1c2c20';c.fillRect(hp.x-8*z,hp.y-3*z,4*z,3*z);c.fillRect(hp.x+3*z,hp.y-3*z,4*z,3*z);c.fillStyle='#dcd6a0';c.fillRect(hp.x-6*z,hp.y-3*z,2*z,2*z);c.fillRect(hp.x+4*z,hp.y-3*z,2*z,2*z);if(e.type==='sentry'){c.strokeStyle='#c8b894';c.lineWidth=2*z;c.beginPath();c.moveTo(p.x+5*z,p.y-13*z);c.lineTo(p.x+25*z,p.y-39*z);c.stroke();}if(e.type==='leaper'||e.type==='mini'){c.strokeStyle='#87945f';c.lineWidth=2*z;c.beginPath();for(let i=0;i<3;i++){c.moveTo(p.x-9*z,p.y-(7+i*4)*z);c.lineTo(p.x-(17+i*3)*z,p.y+(Math.sin(e.anim*14+i)*4-3)*z);c.moveTo(p.x+9*z,p.y-(7+i*4)*z);c.lineTo(p.x+(17+i*3)*z,p.y+(Math.sin(e.anim*14+i)*4-3)*z);}c.stroke();}}
  if(e.burn||e.poison){c.fillStyle=e.burn?'#e9ad73':'#b6d88d';for(let i=0;i<3;i++){const a=this.project(e.x+Math.sin(g.t*5+i)*12,e.y+Math.cos(g.t*4+i)*12,15+(g.t*25+i*9)%40);c.fillRect(a.x,a.y,3*z,4*z);}}
  if(!e.boss&&e.hp<e.maxhp){const width=32*z;c.fillStyle='#203121';c.fillRect(p.x-width/2,p.y-48*z,width,3*z);c.fillStyle='#c5d39e';c.fillRect(p.x-width/2,p.y-48*z,width*clamp(e.hp/e.maxhp,0,1),3*z);}}
 drawTelegraph(e){if(!e.telegraph||e.dead)return;const c=this.ctx,g=e.telegraph,p=this.project(e.x,e.y),progress=1-g.time/g.max;c.save();c.globalAlpha=.25+.28*progress;c.fillStyle='#d47c63';c.strokeStyle='#e9a487';c.lineWidth=1.3;if(g.mode==='melee'||g.mode===0){c.beginPath();c.ellipse(p.x,p.y,(e.boss?195:78)*this.zoom,(e.boss?195:78)*.527*this.zoom,0,0,Math.PI*2);c.fill();c.stroke();}else if(g.mode===2){const t=this.project(g.x,g.y);c.lineWidth=40*this.zoom;c.beginPath();c.moveTo(p.x,p.y);c.lineTo(t.x,t.y);c.stroke();}else if(g.mode===1){c.beginPath();c.ellipse(p.x,p.y,140*this.zoom,75*this.zoom,0,0,Math.PI*2);c.stroke();}else{const t=this.project(e.x+Math.cos(g.angle)*520,e.y+Math.sin(g.angle)*520);c.beginPath();c.moveTo(p.x,p.y);c.lineTo(t.x,t.y);c.stroke();}c.restore();}
 drawEffects(front=false){const c=this.ctx,g=this.game;for(const e of g.effects){if(e.type==='ghost'){if(front){this.drawHero({...g.player,x:e.x,y:e.y,angle:e.angle,invuln:0,anim:0},e.time/e.max*.22);}continue;}const isFront=['slash','thrust','lightning'].includes(e.type);if(isFront!==front)continue;const p=this.project(e.x,e.y),f=1-e.time/e.max;c.save();c.globalAlpha=Math.min(1,e.time/e.max+.2);c.strokeStyle=e.color;c.fillStyle=e.color;c.lineWidth=2*this.zoom;if(e.type==='ring'||e.type==='slam'||e.type==='field'||e.type==='hostileField'){const r=['field','hostileField'].includes(e.type)?e.range:e.range*(.35+f*.65);c.globalAlpha=['field','hostileField'].includes(e.type)?.16:.40*(1-f);c.beginPath();c.ellipse(p.x,p.y,r*this.zoom,r*.527*this.zoom,0,0,Math.PI*2);if(['field','hostileField'].includes(e.type))c.fill();else c.stroke();if(e.type==='slam'){c.globalAlpha=.15*(1-f);c.fill();}}
  else if(e.type==='lightning'){const target=this.project(e.tx,e.ty,18);c.beginPath();c.moveTo(p.x,p.y-18*this.zoom);for(let i=1;i<6;i++){c.lineTo(p.x+(target.x-p.x)*i/6+(i%2?5:-5)*this.zoom,p.y-18*this.zoom+(target.y-(p.y-18*this.zoom))*i/6);}c.lineTo(target.x,target.y);c.stroke();}
  else if(e.type==='thrust'){const end=this.project(e.x+Math.cos(e.angle)*e.range*f,e.y+Math.sin(e.angle)*e.range*f,21);c.lineWidth=5*this.zoom;c.beginPath();c.moveTo(p.x,p.y-22*this.zoom);c.lineTo(end.x,end.y);c.stroke();}
  else if(e.type==='slash'){c.lineWidth=5*this.zoom;c.beginPath();for(let i=0;i<=20;i++){const a=e.angle-1.25+i/20*2.5,q=this.project(e.x+Math.cos(a)*e.range*(.7+f*.3),e.y+Math.sin(a)*e.range*(.7+f*.3),22);i?c.lineTo(q.x,q.y):c.moveTo(q.x,q.y);}c.stroke();}c.restore();}}
 render(dt){const c=this.ctx,g=this.game;if(this.lastRoom!==g.room)this.cacheFloor();c.setTransform(this.dpr,0,0,this.dpr,0,0);c.imageSmoothingEnabled=false;c.drawImage(this.floor,0,0,this.canvas.width,this.canvas.height,0,0,this.w,this.h);c.save();this.shake=Math.max(0,this.shake-dt);if(this.shake)c.translate(Math.sin(g.t*120)*this.shake*15,Math.cos(g.t*83)*this.shake*10);this.drawEffects(false);for(const e of g.enemies)this.drawTelegraph(e);
  for(const d of g.drops){const p=this.project(d.x,d.y,8+Math.sin(g.t*4+d.id)*2);c.fillStyle=d.type==='gold'?'#d6bf70':d.type==='xp'?'#bbd08c':'#d89179';this.ellipse(d.x,d.y,7,3,'#1b2a1c99');c.save();c.translate(p.x,p.y);c.rotate(Math.PI/4);c.fillRect(-3*this.zoom,-3*this.zoom,6*this.zoom,6*this.zoom);c.restore();}
  const objects=this.props.map(o=>({...o,sort:o.x+o.y}));objects.push({type:'hero',x:g.player.x,y:g.player.y,sort:g.player.x+g.player.y});objects.push({type:'chest',...g.chest,sort:g.chest.x+g.chest.y});objects.push({type:'portal',...g.portal,sort:g.portal.x+g.portal.y});for(const e of g.enemies)if(!e.dead)objects.push({type:'enemy',enemy:e,sort:e.x+e.y});for(const t of g.turrets)objects.push({type:'turret',...t,sort:t.x+t.y});objects.sort((a,b)=>a.sort-b.sort);for(const o of objects){if(o.type==='hero')this.drawHero();else if(o.type==='chest')this.drawChest();else if(o.type==='portal')this.drawPortal();else if(o.type==='enemy')this.drawEnemy(o.enemy);else if(o.type==='turret'){this.prism(o.x-13,o.y-13,26,26,26,'#c2b788','#637057','#859472');const p=this.project(o.x,o.y,34);c.fillStyle='#ddd39e';c.fillRect(p.x-3*this.zoom,p.y-5*this.zoom,6*this.zoom,8*this.zoom);}else this.drawProp(o);}
  for(const b of g.projectiles){const p=this.project(b.x,b.y,17);const color=b.hostile?'#e3a388':TAGS[b.tag]?.color||'#e4dfbc';c.fillStyle=color;c.beginPath();c.arc(p.x,p.y,Math.max(2,b.radius*this.zoom),0,Math.PI*2);c.fill();c.strokeStyle=color+'77';c.lineWidth=Math.max(1,b.radius*this.zoom*.6);c.beginPath();c.moveTo(p.x,p.y);const q=this.project(b.x-b.vx*.04,b.y-b.vy*.04,17);c.lineTo(q.x,q.y);c.stroke();}
  this.drawEffects(true);for(const p of g.particles){const a=this.project(p.x,p.y,p.type==='number'?51:12);c.save();c.globalAlpha=Math.min(1,p.time/p.max*1.7);c.fillStyle=p.color;if(p.type==='number'){c.textAlign='center';c.font=`bold ${Math.max(10,14*this.zoom)}px Georgia`;c.shadowColor='#15251b';c.shadowBlur=2;c.fillText(p.text,a.x,a.y);}else c.fillRect(a.x,a.y,2*this.zoom,2*this.zoom);c.restore();}
  // Ambient floating specks remain subtle and deterministic.
  for(let i=0;i<20;i++){const x=(i*137.4+g.t*(3+i%3))%this.w,y=(i*79.3-g.t*(6+i%4)+this.h*100)%this.h;c.globalAlpha=.12+Math.sin(g.t+i)*.08;c.fillStyle='#d0d4a2';c.fillRect(x,y,i%4===0?2:1,i%4===0?2:1);}c.globalAlpha=1;
  if(g.state==='running'){const p=this.project(g.aim.x,g.aim.y);c.strokeStyle='#ced6ae77';c.lineWidth=1;c.beginPath();c.moveTo(p.x-5,p.y);c.lineTo(p.x+5,p.y);c.moveTo(p.x,p.y-5);c.lineTo(p.x,p.y+5);c.stroke();}
  c.restore();}
}
