import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {HEROES,WEAPONS,RELICS,SUPPLIES,TAGS,RARITIES,SETS} from '../data.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const write=(name,text)=>fs.writeFileSync(path.join(root,'docs',name),text,'utf8');
const table=(headers,rows)=>[headers.join(' | '),headers.map(()=> '---').join(' | '),...rows.map(r=>r.join(' | '))].map(line=>'| '+line+' |').join('\n');
write('CONTENT_CATALOG.md',`# 遗物猎场 · 内容图鉴\n\n此文档由实际游戏数据生成。10 名可玩角色、24 把武器、40 件遗物、8 种补给，均已接入原型。稀有度目前用于内容分级与图鉴展示；原型的奖励抽取尚未按稀有度加权。\n\n## 10 名角色\n\n${table(['角色','定位','生命 / 移速','起始武器','主动技能','基础冷却','天赋'],HEROES.map(h=>[h.name,h.role,`${h.hp} / ${h.speed}`,WEAPONS.find(w=>w.id===h.weapon).name,`${h.skill}：${h.skillText}`,`${h.cooldown}s`,h.passive]))}\n\n## 24 把武器\n\n以下伤害为单次命中基础值，散射、三连、爆炸、回响与状态伤害另计。角色天赋和遗物会改变最终伤害。\n\n${table(['武器','类型','系列','品质','伤害','间隔','距离','攻击特点'],WEAPONS.map(w=>[w.name,w.type,TAGS[w.tag].name,RARITIES[w.rarity],w.damage,w.cd+'s',w.range,w.description]))}\n\n## 40 件遗物\n\n每件遗物本局最多获得一次。护盾类遗物在进入下一房间时补充；复活遗物触发后消耗。组合按遗物件数计算，当前武器不计件数。减伤上限 65%，技能冷却缩短上限 60%，闪避冷却缩短上限 65%，暴击率上限 85%。\n\n${table(['遗物','系列','品质','实际效果'],RELICS.map(r=>[r.name,TAGS[r.tag].name,RARITIES[r.rarity],r.description]))}\n\n## 系列组合\n\n${table(['系列','3 件 / 6 件效果'],Object.entries(SETS).map(([id,text])=>[TAGS[id].name,text]))}\n\n## 8 种补给\n\n每次出发携带两份温苔茶；每个秘匣随机赠送一件补给。点选背包中的补给后按 Q 使用，触屏可点底部 Q 按钮。\n\n${table(['补给','效果'],SUPPLIES.map(s=>[s.name,s.description]))}\n`);
const descriptions={
 ranger:'a compact ruin ranger in a moss-green hood and short cloak, tan leather tunic, ochre trim, dark boots, a square field satchel centred on the back; both hands empty for modular game weapons',
 knight:'a stocky oath knight in slate-silver plate, a rounded full helmet with a short terracotta crest, weathered copper trim, broad shoulders and sturdy boots; both hands empty for modular game weapons',
 witch:'a young ember witch wearing a rust-orange robe and a pointed wide-brim hat, pale gold belt and cuffs, brown boots, a small closed lamp centred at the belt; both hands empty for modular game weapons',
 rogue:'a nimble ruin thief in a charcoal lavender coat, a low eye band and cloth face mask, cream belt, light boots, a symmetric short split cloak; both hands empty for modular game weapons',
 tinker:'a small scrap engineer in a mustard utility coat, brass goggles, desaturated teal gloves, padded boots, a square tool pack centred on the back; both hands empty for modular game weapons',
 oracle:'a frost scholar in a pale teal hood and coat, ivory trim, dark slate boots, a rectangular book pack centred on the back, a calm face; both hands empty for modular game weapons',
 monk:'a sturdy bald stone monk in a warm sand vest, ochre sash, stone-grey hand wraps and simple boots, a heavy but agile stance; both hands empty for modular game weapons',
 botanist:'a cheerful mushroom botanist with a salmon mushroom-cap hat with pale speckles, sage-green coat, cream apron and dark boots, a herb pack centred on the back; both hands empty for modular game weapons',
 warden:'a grave keeper in a deep sea-green hood and face veil, muted violet trim, long split coat, grey boots, a symmetric pale memorial emblem centred on the back; both hands empty for modular game weapons',
 corsair:'a sunken-city hunter with a terracotta head band and coat, cream undershirt, pale ochre belt and brown boots, a short symmetric coat tail; both hands empty for modular game weapons'
};
const cast={_comment:'Prepared from scenario-iso-cycles. Templates only: Scenario MCP was not connected; no model ids, paid calls, jobs or assets were fabricated. Body sprites have empty hands; weapons are separate runtime layers. Original prototype sheets are assets/*.png.',canvas:960,fig_frac:.58,base_frac:.82,frames:8,cycles:['walk','run','idle','attack'],style:'crisp hand-placed 16-bit pixel art, 1px dark forest outline, 24-colour earthy palette, muted moss green and warm parchment accents, soft top-left lighting, compact readable silhouettes',facings:['se','ne','e','s','n'],camera:'isometric',key:'magenta',heroes:{}};
for(const h of HEROES)cast.heroes[h.id]={_name:h.name,character:descriptions[h.id],back:'we see the back of the headwear and coat, and the centred back-pack or emblem',who:h.role+' ruin explorer',pronoun:'They',extra:', coat hems and straps sway subtly',idle:'the chest breathes softly and the coat hem moves by one pixel',attack:'unarmed modular attack pose: pulls the leading arm back, quickly swings or thrusts the empty hands forward in the facing direction, follows through, then returns to the ready pose; do not invent a held weapon',attack_facing:{s:'a head-on empty-hand strike straight toward the viewer; both shoulders remain symmetrical, never turns side-on',n:'an empty-hand strike straight away from the viewer; spine remains centred and the back stays fully visible'},back_view:'the back of the headwear and coat, with any pack or emblem staying centred',notes:'Both hands are empty. Symmetric silhouette and centred equipment allow horizontal mirroring without swapping weapon hands. Game weapons are composited separately.',turn_notes:{e:'A strict right-facing profile; pack appears behind the body on the left of the image.',s:'Exact front view, both shoulders level, empty hands equally visible, face and chest on the vertical centre line.',n:'Exact rear view; the headwear, spine and back-pack or emblem share the same vertical centre line.'},height:64,palette:24,ranges:{walk:[12,34],run:[8,24],idle:[24,66]}};
write('cast.json',JSON.stringify(cast,null,2));
console.log('Generated CONTENT_CATALOG.md and a 10-hero Scenario cast.json.');
