export const WORLD = Object.freeze({
  width: 1600,
  height: 900,
  groundY: -238,
  laneY: -176,
  heroX: -686,
  caveX: 620,
  topY: 338,
  bottomY: -316,
});

export const BALANCE = Object.freeze({
  arrowDamage: 34,
  arrowSpeed: 680,
  shotCooldown: 0.46,
  critChance: 0.08,
  critDamage: 1.85,
  gourdMax: 100,
  gourdRegen: 4.2,
  coinRewardBonus: 0,
});

export const LEVELS = Object.freeze([
  {
    id: 'green-ridge',
    name: '第一关 青藤岭',
    seal: 420,
    waveGap: 2.2,
    reward: { coins: 100, gourd: 35, jade: 1 },
    waves: [
      { delay: 0.8, count: 5, every: 1.15, types: ['shield', 'shield', 'serpent'] },
      { delay: 1.2, count: 7, every: 0.96, types: ['shield', 'serpent', 'drummer'] },
    ],
  },
  {
    id: 'mist-cave',
    name: '第二关 云雾洞',
    seal: 680,
    waveGap: 2,
    reward: { coins: 155, gourd: 50, jade: 2 },
    waves: [
      { delay: 1, count: 7, every: 0.88, types: ['serpent', 'shield', 'scorpion'] },
      { delay: 1, count: 8, every: 0.82, types: ['drummer', 'shield', 'serpent'] },
      { delay: 1.3, count: 5, every: 1.08, types: ['scorpion', 'sorcerer'] },
    ],
  },
  {
    id: 'red-seal',
    name: '第三关 赤符石门',
    seal: 960,
    waveGap: 1.8,
    reward: { coins: 230, gourd: 70, jade: 3 },
    waves: [
      { delay: 0.8, count: 8, every: 0.78, types: ['shield', 'scorpion', 'serpent'] },
      { delay: 1, count: 10, every: 0.68, types: ['drummer', 'serpent', 'shield'] },
      { delay: 1.2, count: 8, every: 0.84, types: ['sorcerer', 'scorpion', 'shield'] },
    ],
  },
]);

export const ENEMY_TYPES = Object.freeze({
  shield: {
    name: '靶甲妖兵',
    hp: 74,
    speed: 43,
    radius: 42,
    leakDamage: 11,
    coin: 16,
    gourd: 5,
    sealDamage: 32,
    scale: 0.94,
    color: '#6f9365',
    sprite: 'walk',
    body: { width: 106, height: 116, y: 2 },
    target: { x: 28, y: 8, size: 58 },
  },
  serpent: {
    name: '蛇影斥候',
    hp: 48,
    speed: 72,
    radius: 34,
    leakDamage: 8,
    coin: 13,
    gourd: 4,
    sealDamage: 24,
    scale: 0.8,
    color: '#6cae93',
    sprite: 'eye',
    body: { width: 104, height: 124, y: 8 },
    target: { x: 23, y: 3, size: 50 },
  },
  drummer: {
    name: '铜鼓妖兵',
    hp: 62,
    speed: 52,
    radius: 38,
    leakDamage: 10,
    coin: 18,
    gourd: 6,
    sealDamage: 30,
    scale: 0.86,
    color: '#bd8a4f',
    sprite: 'walk',
    body: { width: 112, height: 122, y: 3 },
    target: { x: 28, y: 8, size: 56 },
  },
  scorpion: {
    name: '蝎甲卫',
    hp: 118,
    speed: 34,
    radius: 48,
    leakDamage: 17,
    coin: 28,
    gourd: 8,
    sealDamage: 48,
    scale: 1.08,
    color: '#83585b',
    sprite: 'eye',
    body: { width: 126, height: 150, y: 6 },
    target: { x: 35, y: 8, size: 64 },
  },
  sorcerer: {
    name: '蛇府术士',
    hp: 92,
    speed: 39,
    radius: 44,
    leakDamage: 15,
    coin: 32,
    gourd: 10,
    sealDamage: 54,
    scale: 1,
    color: '#7a66a4',
    sprite: 'walk',
    body: { width: 118, height: 130, y: 4 },
    target: { x: 31, y: 12, size: 60 },
  },
});

export const UPGRADES = Object.freeze([
  {
    id: 'bow',
    name: '青藤弓',
    levelName: '弓力',
    description: '每级提高箭矢伤害，四级后可穿透一名敌人。',
    max: 6,
    baseCost: 50,
    growth: 1.55,
  },
  {
    id: 'string',
    name: '金线弦',
    levelName: '弦速',
    description: '提高箭速并缩短开弓间隔。',
    max: 6,
    baseCost: 45,
    growth: 1.48,
  },
  {
    id: 'gourd',
    name: '葫芦气',
    levelName: '气海',
    description: '提高葫芦气上限与回复。',
    max: 6,
    baseCost: 60,
    growth: 1.5,
  },
  {
    id: 'craft',
    name: '符箭匣',
    levelName: '符纹',
    description: '提高会心率和击败奖励。',
    max: 6,
    baseCost: 70,
    growth: 1.58,
  },
]);

export const SKILLS = Object.freeze([
  {
    id: 'dawa',
    name: '大娃',
    title: '震山拳',
    description: '震开前线，造成范围伤害。',
    cost: 28,
    cooldown: 8,
    unlockCost: 0,
    minLevel: 0,
  },
  {
    id: 'erwa',
    name: '二娃',
    title: '千里眼',
    description: '标出弱点，短时间提高会心。',
    cost: 24,
    cooldown: 12,
    unlockCost: 115,
    minLevel: 0,
  },
  {
    id: 'sanwa',
    name: '三娃',
    title: '金刚守',
    description: '护住爷爷，减轻冲阵伤害。',
    cost: 30,
    cooldown: 15,
    unlockCost: 165,
    minLevel: 1,
  },
  {
    id: 'huowa',
    name: '火娃',
    title: '烈焰雨',
    description: '落火焚阵，重创洞前敌军。',
    cost: 42,
    cooldown: 18,
    unlockCost: 240,
    minLevel: 1,
  },
]);
