import {puppeteer,executablePath,gpuArgs,baseURL} from './browser.mjs';
import fs from 'node:fs/promises';import {fileURLToPath} from 'node:url';
const out=fileURLToPath(new URL('../artifacts/',import.meta.url));await fs.mkdir(out,{recursive:true});
const browser=await puppeteer.launch({executablePath,headless:true,args:gpuArgs,defaultViewport:{width:1440,height:960,deviceScaleFactor:1}});
const page=await browser.newPage(),report={};const wait=ms=>new Promise(r=>setTimeout(r,ms));
try{await page.goto(baseURL);await page.waitForFunction(()=>jelly.ready);await wait(1200);
 report.inversion=await page.evaluate(()=>{jelly.options.count=1;jelly.options.pause=true;jelly.resetDice();const d=jelly.dice[0];for(let i=0;i<d.x.length;i+=3)d.x[i]=2*d.center[0]-d.x[i];d.wake();const before=jelly.stats();for(let i=0;i<360;i++)jelly.step(1/120);return{before,after:jelly.stats()}});console.log('INVERSION',JSON.stringify(report.inversion));
 report.collision=await page.evaluate(()=>{jelly.options.count=2;jelly.options.softness=1;jelly.resetDice();const a=jelly.dice[0],b=jelly.dice[1];for(let i=0;i<a.x.length;i+=3)a.x[i]+=.45;for(let i=0;i<b.x.length;i+=3)b.x[i]-=.45;a.wake();b.wake();let min=10,max=0;for(let i=0;i<720;i++){jelly.step(1/120);if(i%30===0){const s=jelly.stats();min=Math.min(min,...s.map(s=>s.minVolume));max=Math.max(max,...s.map(s=>s.maxStrain))}}return{min,max,after:jelly.stats()}});console.log('COLLISION',JSON.stringify(report.collision));
 report.stack=await page.evaluate(()=>{jelly.options.count=2;jelly.options.softness=.65;jelly.resetDice();const a=jelly.dice[0],b=jelly.dice[1],c=Math.cos(.35),s=Math.sin(.35);for(let i=0;i<a.x.length;i+=3){a.x[i]+=.85;const x=b.x[i]-.85,y=b.x[i+1]-.76,z=b.x[i+2]-.3;b.x[i]=.2+c*x-s*y;b.x[i+1]=1.78+s*x+c*y;b.x[i+2]=z}a.wake();b.wake();for(let i=0;i<1800;i++)jelly.step(1/120);return jelly.stats()});console.log('STACK',JSON.stringify(report.stack));
 report.flatStack=await page.evaluate(()=>{jelly.options.count=2;jelly.resetDice();const a=jelly.dice[0],b=jelly.dice[1];for(let i=0;i<a.x.length;i+=3)a.x[i]+=.85;a.frame();a.prev.set(a.x);b.x.set(a.x);for(let i=1;i<b.x.length;i+=3)b.x[i]+=1.14;b.R=a.R.slice();for(let i=0;i<b.cl.length;i++)b.cl[i].r=a.cl[i].r.slice();b.prev.set(b.x);b.wake();for(let i=0;i<1800;i++)jelly.step(1/120);return jelly.stats()});console.log('FLAT STACK',JSON.stringify(report.flatStack));
 await page.evaluate(()=>{jelly.options.count=3;jelly.options.softness=.65;jelly.options.pause=false;jelly.resetDice()});await wait(300);
 const point=await page.evaluate(()=>jelly.project([jelly.dice[0].center[0],jelly.dice[0].center[1]+.48,jelly.dice[0].center[2]]));await page.mouse.move(...point);await page.mouse.down();await page.mouse.move(point[0]+12,point[1]-26,{steps:6});await wait(600);report.gentle=await page.evaluate(()=>({s:jelly.stats(),floor:Math.min(...jelly.dice[0].x.filter((v,i)=>i%3===1))}));await page.screenshot({path:out+'gentle-stretch.png'});
 await page.mouse.move(point[0]+140,point[1]-310,{steps:12});await wait(900);report.firm=await page.evaluate(()=>jelly.stats());await page.screenshot({path:out+'firm-stretch.png'});await page.mouse.up();report.releaseImmediate=await page.evaluate(()=>jelly.stats());
 await page.click('#settings-button');await page.click('#pause');const frozen=await page.evaluate(()=>jelly.dice.map(d=>Array.from(d.x)));await wait(300);report.paused=await page.evaluate(before=>before.every((v,d)=>v.every((p,i)=>p===jelly.dice[d].x[i])),frozen);await page.click('#mesh');await page.screenshot({path:out+'mesh.png'});await page.click('#pause');await page.click('#settings-button');
 await page.setViewport({width:390,height:844,deviceScaleFactor:1,isMobile:true,hasTouch:true});await wait(400);const cdp=await page.createCDPSession();const dist=await page.evaluate(()=>jelly.camera.dist);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:130,y:530},{x:260,y:530}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:100,y:530},{x:290,y:530}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});report.pinch={before:dist,after:await page.evaluate(()=>jelly.camera.dist)};
 await page.evaluate(()=>{jelly.resetDice();jelly.options.pause=false});await wait(250);await page.focus('#scene');await page.keyboard.press('3');await page.keyboard.press('Enter');await wait(150);report.keyboard=await page.evaluate(()=>jelly.stats()[2].sleep===false);await page.keyboard.press('r');await wait(100);report.keyRoll=await page.evaluate(()=>jelly.stats().every(s=>!s.sleep));report.errors=await page.evaluate(()=>jelly.errors);
 const local=await browser.newPage();await local.goto(new URL('../index.html',import.meta.url).href);await local.waitForFunction(()=>jelly.ready);report.fileReady=await local.evaluate(()=>jelly.ready);
}finally{await fs.writeFile(out+'stress.json',JSON.stringify(report,null,2));console.log('REPORT',JSON.stringify(report,null,2));await browser.close()}
if(report.inversion.after.some(s=>s.minVolume<=0)||report.collision.min<=0||report.collision.max>1.49||!report.stack.every(s=>s.sleep&&s.nudges<=2)||!report.flatStack.every(s=>s.sleep)||report.flatStack[1].center[1]<1.4||!report.paused||!report.keyboard||!report.keyRoll||report.errors.length)process.exitCode=1;
