const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || undefined });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto((process.env.YUSHAN_URL || 'http://127.0.0.1:4178/'));
  await page.waitForTimeout(250);
  const position = () => page.locator('#player').evaluate(el => {
    const m = el.transform.baseVal.getItem(0).matrix;
    return { x: m.e, y: m.f };
  });
  const start = await position();
  await page.keyboard.down('ArrowRight');
  await page.waitForTimeout(1200);
  await page.keyboard.up('ArrowRight');
  const moved = await position();
  assert(moved.x > start.x + 60, 'Keyboard moves the player');
  await page.keyboard.press('e');
  await page.waitForSelector('#postcard[open]');
  assert.equal(await page.locator('#card-title').textContent(), '把灯火装进口袋');
  await page.locator('#keep-walking').click();
  assert.match(await page.locator('#journey-label').textContent(), /1 \/ 3/);
  await page.keyboard.down('ArrowUp');
  await page.waitForTimeout(800);
  await page.keyboard.up('ArrowUp');
  const edge = await position();
  assert(edge.y >= 698 + Math.sin(edge.x / 315) * 18 + 38, 'Player cannot enter lake');
  await page.evaluate(() => {
    const s=document.querySelector('#world'),p=s.createSVGPoint();p.x=700;p.y=790;
    const screen=p.matrixTransform(s.getScreenCTM());
    s.dispatchEvent(new PointerEvent('pointerdown',{clientX:screen.x,clientY:screen.y,bubbles:true}));
  });
  await page.waitForTimeout(1700);
  assert(Math.abs((await position()).x-700)<6, 'Click to walk reaches destination');
  await page.locator('[data-toggle="rain"]').click();
  assert.equal(await page.locator('[data-toggle="rain"]').getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator('#player .umbrella').evaluate(el => getComputedStyle(el).display), 'inline');
  assert.notEqual(await page.locator('#rain-layer').evaluate(el => getComputedStyle(el).display), 'none');
  await page.screenshot({ path: 'preview-rain.png' });
  await page.locator('[data-toggle="crowd"]').click();
  assert.equal(await page.locator('[data-npc]:visible').count(), 0);
  await page.locator('[data-toggle="lights"]').click();
  await page.waitForTimeout(70);
  assert.equal(await page.locator('#tower-a-bands').getAttribute('opacity'), '.25');
  await page.locator('[data-toggle="sound"]').click();
  assert.equal(await page.locator('[data-toggle="sound"]').getAttribute('aria-pressed'), 'true');
  await page.locator('[data-toggle="sound"]').click();
  await page.locator('#fullscreen').click();
  assert.equal(await page.evaluate(() => !!document.fullscreenElement), true);
  await page.locator('#fullscreen').click();
  assert.equal(await page.evaluate(() => !!document.fullscreenElement), false);
  await page.locator('#day-toggle').click();
  assert.equal(await page.locator('#scene-time').textContent(), '15:36');
  await page.locator('[data-toggle="rain"]').click();
  await page.screenshot({ path: 'preview-day.png' });
  await page.locator('#day-toggle').click();
  await page.locator('[data-toggle="crowd"]').click();
  await page.locator('[data-toggle="lights"]').click();
  await page.evaluate(() => {
    const s=document.querySelector('#world'),p=s.createSVGPoint();p.x=500;p.y=220;
    const screen=p.matrixTransform(s.getScreenCTM());
    s.dispatchEvent(new PointerEvent('pointerdown',{clientX:screen.x,clientY:screen.y,bubbles:true}));
  });
  assert((await page.locator('#firework-layer rect').count()) >= 32, 'Manual fireworks launch');
  await page.locator('[data-toggle="fireworks"]').click();
  assert.equal(await page.locator('#firework-layer rect').count(), 0);
  await page.locator('[data-toggle="fireworks"]').click();
  await page.reload();
  await page.waitForTimeout(300);
  assert.match(await page.locator('#journey-label').textContent(), /1 \/ 3/);
  await page.screenshot({ path: 'preview-night.png' });
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  mobile.on('pageerror', e => errors.push(e.message));
  await mobile.goto((process.env.YUSHAN_URL || 'http://127.0.0.1:4178/'));
  await mobile.waitForTimeout(300);
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No horizontal overflow on phone');
  const before = await mobile.locator('#player').evaluate(el=>el.transform.baseVal.getItem(0).matrix.e);
  await mobile.locator('[data-dir="right"]').dispatchEvent('pointerdown', { pointerId: 1 });
  await mobile.waitForTimeout(400);
  await mobile.locator('[data-dir="right"]').dispatchEvent('pointerup', { pointerId: 1 });
  assert((await mobile.locator('#player').evaluate(el=>el.transform.baseVal.getItem(0).matrix.e))>before+15, 'Touch control moves player horizontally');
  await mobile.screenshot({ path: 'preview-mobile.png' });
  assert.deepEqual(errors, [], 'No browser errors');
  console.log('PASS: movement, shoreline boundary, landmark collection, saved progress, rain, umbrellas, crowd, red light show, audio toggle, day/night, fireworks, mobile layout and controls.');
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
