export class Audio {
  constructor(enabled=true){this.enabled=enabled;this.ctx=null;this.beat=0;this.tickTime=0;}
  unlock(){if(!this.enabled)return;try{this.ctx=this.ctx||new(window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume();}catch{this.enabled=false;}}
  set(enabled){this.enabled=enabled;if(enabled)this.unlock();}
  tone(frequency,duration=.08,type='sine',volume=.05,endFrequency){if(!this.enabled||!this.ctx||this.ctx.state!=='running')return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(frequency,t);if(endFrequency)o.frequency.exponentialRampToValueAtTime(endFrequency,t+duration);g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.ctx.destination);o.start(t);o.stop(t+duration);}
  noise(duration=.09,volume=.04){if(!this.enabled||!this.ctx)return;const t=this.ctx.currentTime,buffer=this.ctx.createBuffer(1,this.ctx.sampleRate*duration,this.ctx.sampleRate),d=buffer.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);const s=this.ctx.createBufferSource(),g=this.ctx.createGain();g.gain.value=volume;s.buffer=buffer;s.connect(g);g.connect(this.ctx.destination);s.start(t);}
  event(type){switch(type){case'shot':this.noise(.045,.025);this.tone(150,.035,'triangle',.025,60);break;case'kill':this.tone(540,.07,'sine',.04,900);break;case'gate':case'pickup':[523,659,784].forEach((n,i)=>setTimeout(()=>this.tone(n,.17,'sine',.05),i*70));break;case'hurt':this.noise(.18,.11);this.tone(130,.2,'sawtooth',.04,55);break;case'ability':this.tone(200,.5,'sawtooth',.04,1000);break;case'jump':this.tone(260,.15,'sine',.04,650);break;case'warning':this.tone(350,.25,'square',.02,180);break;case'slam':this.noise(.25,.08);this.tone(85,.3,'triangle',.06,30);break;case'won':[523,659,784,1047].forEach((n,i)=>setTimeout(()=>this.tone(n,.35,'triangle',.07),i*120));break;case'lost':this.tone(300,.5,'triangle',.05,90);break;}}
  update(dt,active){if(!active||!this.enabled)return;this.tickTime-=dt;if(this.tickTime>0)return;this.tickTime=.27;const notes=[130.81,130.81,155.56,174.61,130.81,196,174.61,155.56];this.tone(notes[this.beat%8],.19,'triangle',.017);if(this.beat%2===0)this.tone(52,.08,'sine',.04,32);this.beat++;}
}
