import './style.css';
import { demoText, eventText } from './locale.js';
import { createIcons, Box, Search, ChevronDown, ChevronRight, ArrowUpRight, Truck, Clock3, Bell, Plus, Minus, RotateCcw, RotateCw, House, LocateFixed, X, Layers3, Package, ChartNoAxesCombined, Settings2, Play, Pause, Maximize, Snowflake, ArrowRight, Check, Forklift, BatteryCharging, MapPin, CircleHelp, Download, Upload, CheckCheck, Navigation, LayoutGrid, ArrowDownToLine, ArrowUpFromLine, CheckCircle2, AlertTriangle, Radio, Warehouse, ClipboardList, SlidersHorizontal, Crosshair } from 'lucide';
import { WarehouseStore, SITES, PRODUCTS, CARRIERS, STATUS, KEY, seedState, totalStock, activeShipments, availableStock, reservedStock, product } from './store.js';
import { WarehouseScene } from './scene.js';

const icons={Box,Search,ChevronDown,ChevronRight,ArrowUpRight,Truck,Clock3,Bell,Plus,Minus,RotateCcw,RotateCw,House,LocateFixed,X,Layers3,Package,ChartNoAxesCombined,Settings2,Play,Pause,Maximize,Snowflake,ArrowRight,Check,Forklift,BatteryCharging,MapPin,CircleHelp,Download,Upload,CheckCheck,Navigation,LayoutGrid,ArrowDownToLine,ArrowUpFromLine,CheckCircle2,AlertTriangle,Radio,Warehouse,ClipboardList,SlidersHorizontal,Crosshair};
const icon=(name,cls='')=>`<i data-lucide="${name}" class="${cls}" aria-hidden="true"></i>`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nf=n=>Math.round(n).toLocaleString('zh-CN');
const time=t=>`${String(Math.floor(t/3600)%24).padStart(2,'0')}:${String(Math.floor(t/60)%60).padStart(2,'0')}`;
const cssColor=n=>`#${n.toString(16).padStart(6,'0')}`;
const badge=status=>`<span class="badge ${status}">${STATUS[status]||esc(status)}</span>`;
const bar=(value,color='')=>`<div class="bar ${color}"><span style="width:${Math.max(0,Math.min(100,value))}%"></span></div>`;
const btn=(action,label,ico,cls='button',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${ico?icon(ico):''}${label}</button>`;
const iconBtn=(action,label,ico,extra='')=>`<button class="icon-btn" title="${label}" aria-label="${label}" data-action="${action}" ${extra}>${icon(ico)}</button>`;
let initial,loadFailed=false;try{const raw=localStorage.getItem(KEY);if(raw)initial=JSON.parse(raw);}catch{loadFailed=true;}
let store;try{store=new WarehouseStore(initial);}catch{store=new WarehouseStore();loadFailed=true;}
let state=store.state, selection={kind:'site',id:state.siteId}, fleetTab='docks', scene, overlay=null, searchTimer, lastSite=null, toastTimer;
const root=document.querySelector('#app');
root.innerHTML=`
 <div id="scene" class="scene"><div class="loading"><span class="brand-cube"></span><b>正在准备你的物流世界</b><span>仓流智控 · 让仓储运营一目了然</span></div></div>
 <header class="topbar">
  <button class="brand" data-action="home" aria-label="仓流智控首页"><span class="brand-cube"></span><strong>仓流智控</strong></button>
  <div class="search-wrap"><label class="searchbox">${icon('search')}<input id="global-search" aria-label="搜索园区、车辆、货物或运输单" placeholder="搜索园区、车辆、货物、运输单…" autocomplete="off"><kbd>/</kbd></label><div id="search-results" class="search-results" hidden></div></div>
  <div class="topbar-right"><div class="site-picker"><span class="site-code" id="site-code">WH-01</span><select id="site-select" aria-label="切换园区">${SITES.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}</select>${icon('chevron-down')}</div>
  <button class="live" data-action="pause" title="暂停或继续模拟"><span class="status-dot"></span><span id="live-label">运行中</span><b id="clock">09:40</b></button>
  <button class="icon-btn notification-button" data-action="notifications" title="通知" aria-label="通知">${icon('bell')}<span id="notification-dot"></span></button>
  <span class="header-divider"></span><button class="profile" data-action="settings"><span class="avatar">陈</span><span><b>陈安</b><small>运营管理员</small></span>${icon('chevron-down')}</button></div>
 </header>
 <nav class="side-nav" aria-label="主要功能">
  <div class="nav-top">${iconBtn('overview','园区总览','layout-grid')}${iconBtn('inventory','库存管理','package')}${iconBtn('shipments','运输订单','truck')}${iconBtn('fleet','叉车管理','forklift')}${iconBtn('reports','运营报表','chart-no-axes-combined')}</div>
  <div class="nav-bottom">${iconBtn('help','操作指南','circle-help')}${iconBtn('settings','设置与存档','settings-2')}</div>
 </nav>
 <main class="workspace" aria-label="仓储运营工作台">
  <section id="stats" class="stats" aria-label="园区核心指标"></section>
  <div class="world-title"><span class="eyebrow">仓储运营，一目了然</span><h1 id="world-title">河畔物流中心</h1><p id="world-subtitle">河畔物流中心 <span> / </span> 城市配送仓</p><div class="world-actions">${btn('drive-demo','运行车辆演示','play','button subtle')}</div></div>
  <div class="view-toolbar">${iconBtn('zoom-in','放大','plus')}${iconBtn('zoom-out','缩小','minus')}<span></span>${iconBtn('rotate-left','向左旋转','rotate-ccw')}${iconBtn('rotate-right','向右旋转','rotate-cw')}${iconBtn('top-view','俯视图','layers-3')}${iconBtn('home','重置视角','house')}</div>
  <aside id="detail" class="detail panel" aria-label="选中对象详情"></aside>
  <div class="scene-hint"><span>${icon('crosshair')} 拖动旋转</span><span>右键平移</span><span>滚轮缩放</span><span class="hint-click">点击场景探索</span></div>
  <section id="tracking" class="tracking panel" aria-label="运输进度"></section>
  <section class="fleet panel" aria-label="作业资源"><header class="fleet-header"><div class="segmented"><button data-tab="docks" class="active">月台 <span id="dock-count"></span></button><button data-tab="forks">叉车 <span id="fork-count"></span></button><button data-tab="trucks">卡车 <span id="truck-count"></span></button></div>${iconBtn('shipments','展开运输订单','arrow-up-right')}</header><div id="fleet-rows" class="fleet-rows"></div></section>
 </main>
 <footer class="statusbar"><span><i class="status-dot"></i><span id="save-status">本地演示 · 自动保存</span></span><div class="sim-controls"><span>模拟速度</span>${btn('speed','1×',null,'speed-button','data-speed="1"')}${btn('speed','5×',null,'speed-button','data-speed="5"')}${btn('speed','15×',null,'speed-button','data-speed="15"')}<button data-action="pause" id="pause-button" class="icon-btn" title="暂停模拟" aria-label="暂停模拟">${icon('pause')}</button></div><span class="footer-right">5 个园区 <span class="sep">/</span> <span id="active-total"></span> 单作业</span></footer>
 <div id="tooltip" class="tooltip" hidden></div><div id="toast" class="toast" role="status" aria-live="polite" hidden></div>
 <div id="popover" class="popover panel" hidden></div>
 <dialog id="modal" aria-labelledby="modal-title"><div id="modal-content"></div></dialog>
 <input id="import-file" type="file" accept="application/json,.json" hidden>
`;
const $=s=>document.querySelector(s);const drawIcons=()=>createIcons({icons,attrs:{'stroke-width':1.65}});
function toast(message,error=false){const el=$('#toast');el.innerHTML=`${icon(error?'alert-triangle':'check-circle-2')}<span>${esc(message)}</span>`;el.classList.toggle('error',error);el.hidden=false;drawIcons();clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,4500);}
function doAction(fn){try{return fn();}catch(e){toast(e.message,true);return null;}}
function select(kind,id,focus=false){selection={kind,id};if(kind==='site'&&id!==state.siteId)store.changeSite(id);scene?.select(`${kind}:${id}`);if(focus)scene?.focus(kind,id);renderDetail();renderTracking();drawIcons();}
function changeSite(id){selection={kind:'site',id};store.changeSite(id);$('#global-search').value='';$('#search-results').hidden=true;}
function metric(ico,label,value,sub,extra){return `<article class="metric"><span class="metric-icon">${icon(ico)}</span><div><span class="metric-label">${label}</span><div class="metric-number">${value}<small>${extra}</small></div><p>${sub}</p></div></article>`;}
function renderStats(){const cfg=SITES.find(s=>s.id===state.siteId),stock=totalStock(state,cfg.id),active=activeShipments(state,cfg.id),onSite=active.filter(s=>s.status!=='transit').length;
 $('#stats').innerHTML=metric('box','当前库存',nf(stock),`托盘 · 总容量 ${nf(cfg.capacity)}`,`${Math.round(stock/cfg.capacity*100)}% 使用率`)+metric('truck','园区车辆',onSite,`${active.filter(s=>s.status==='transit').length} 辆运输中 · ${cfg.id}`,`${active.filter(s=>s.status==='queued').length} 待调度`)+metric('clock-3','准时交付率',`${cfg.onTime}%`,'近 30 日 · 演示基线',`${icon('arrow-up-right')} 0.4%`);
 $('#world-title').textContent=cfg.name;$('#world-subtitle').innerHTML=`${cfg.type} <span>/</span> ${cfg.id}`;$('#site-code').textContent=cfg.id;$('#site-select').value=cfg.id;
}
function detailHeader(ico,kicker,title,sub,focus=true){return `<header class="detail-header"><div class="detail-symbol">${icon(ico)}</div><div class="detail-title"><span class="eyebrow">${esc(kicker)}</span><h2>${esc(title)}</h2><p>${esc(sub)}</p></div>${focus?iconBtn('focus','在场景中定位','locate-fixed'):''}${selection.kind!=='site'?iconBtn('overview','返回园区概览','x'):''}</header>`;}
function kv(label,value){return `<div class="kv"><span>${label}</span><b>${value}</b></div>`;}
function productRow(item){const p=product(item.productId),low=item.qty<item.min;return `<button class="inventory-row" data-select="product" data-id="${p.id}"><span class="package-icon" style="--package-color:${cssColor(p.color)}">${icon('package')}</span><span>${p.name}</span><b>${nf(item.qty)}</b><span class="badge ${low?'warning':'success'}">${low?'低库存':'充足'}</span></button>`;}
function renderDetail(){const cfg=SITES.find(s=>s.id===state.siteId),site=state.sites[cfg.id],stock=totalStock(state,cfg.id),active=activeShipments(state,cfg.id);let html='';
 if(selection.kind==='site'){
  html=detailHeader('warehouse',`${cfg.type} · ${cfg.id}`,cfg.name,cfg.address)+`<div class="detail-body"><div class="operation-status"><span class="badge success"><i class="status-dot"></i>运营正常</span><span>${active.filter(s=>s.dock).length} 辆作业 · ${active.filter(s=>s.status==='transit').length} 辆在途</span></div><div class="mini-stats"><div><small>仓储容量</small><b>${nf(stock)}<em> / ${nf(cfg.capacity)}</em></b>${bar(stock/cfg.capacity*100)}</div><div><small>月台占用</small><b>${active.filter(s=>s.dock).length}<em> / ${cfg.docks} 月台</em></b>${bar(active.filter(s=>s.dock).length/cfg.docks*100,'green')}</div><div><small>今日出库</small><b>${site.outbound}<em> 车次</em></b></div><div><small>今日上架</small><b>${site.putaway}<em> 托盘</em></b></div></div><div class="section-label"><h3>库存概览</h3>${btn('inventory','全部库存','arrow-up-right','text-button')}</div><div class="inventory-list">${site.inventory.map(productRow).join('')}</div><div class="section-label"><h3>叉车作业</h3><small>${site.forks.filter(f=>f.status==='working').length} / ${site.forks.length} 运行中</small></div><div class="compact-forks">${site.forks.slice(0,3).map(f=>`<button data-select="fork" data-id="${f.id}" class="compact-fork"><b>${f.id}</b><span>${STATUS[f.status]}</span>${bar(f.battery,f.battery<30?'amber':'green')}<small>${Math.round(f.battery)}%</small></button>`).join('')}</div><div class="detail-footer">${btn('new-shipment','新建运输单','plus','button primary')}${btn('inventory','管理库存','package','button subtle')}</div></div>`;
 }else if(selection.kind==='truck'){
  const sh=state.shipments.find(s=>s.id===selection.id);if(!sh){selection={kind:'site',id:state.siteId};return renderDetail();}
  html=detailHeader('truck',CARRIERS[sh.carrier].name,sh.truckId,`${sh.direction==='inbound'?'入库接收':'出库运输'} · ${sh.id}`,!['delivered','cancelled'].includes(sh.status))+`<div class="detail-body"><div class="operation-status">${badge(sh.status)}<span>${sh.dock?`月台 ${sh.dock}`:'园区运输网络'}</span></div>${bar(sh.progress*100,'green')}<div class="progress-caption"><span>当前阶段</span><b>${Math.round(sh.progress*100)}%</b></div><div class="kv-list">${kv('运输单',`<span class="blue">#${esc(sh.id)}</span>`)}${kv('客户',esc(demoText(sh.customer)))}${kv('目的地',esc(demoText(sh.destination)))}${kv('行驶速度',`${((state.paused?0:sh.motion?.speed||0)*3.6).toFixed(1)} 千米/时`)}${kv('当前动作',sh.motion?.waiting?'通道让行':sh.motion&&sh.pose?.reverse?'倒车入位':STATUS[sh.status])}${kv('货品',product(sh.productId).name)}${kv('装载数量',`${sh.qty} 托盘 · ${(sh.qty*product(sh.productId).weight/100).toFixed(1)} 吨`)}${kv('作业月台',sh.dock?`${cfg.id} / 月台 ${sh.dock}`:'—')}${kv('作业叉车',sh.forkId||'—')}${kv('预计完成',sh.status==='queued'?'等待调度':['delivered','cancelled'].includes(sh.status)?STATUS[sh.status]:`${sh.motion?Math.ceil((sh.motion.length-sh.motion.distance)/sh.motion.cruise)+' 模拟秒':sh.status==='transit'?Math.ceil((1-sh.progress)*sh.travelSeconds)+' 模拟秒':'已搬运 '+(sh.handled||0)+' / '+sh.qty+' 托盘'}`)}</div><div class="detail-footer">${sh.status==='queued'?btn('dispatch','分配月台与叉车','navigation','button primary',`data-id="${sh.id}"`):["delivered","cancelled"].includes(sh.status)?btn('new-shipment','创建下一单','plus','button primary'):btn('follow','跟随车辆','locate-fixed','button primary')}${['queued','arriving','loading'].includes(sh.status)?btn('cancel-shipment','取消运输',null,'button subtle',`data-id="${sh.id}"`):''}</div></div>`;
 }else if(selection.kind==='fork'){
  const f=site.forks.find(f=>f.id===selection.id);if(!f)return select('site',cfg.id);const job=state.shipments.find(s=>s.id===f.jobId);
  html=detailHeader('forklift',`电动叉车 · ${cfg.id}`,f.id,'额定载重 2.5 吨 · 电动平衡重式')+`<div class="detail-body"><div class="operation-status">${badge(f.status)}<span>${f.status==='working'?'正在执行运输任务':'可在调度时分配任务'}</span></div><div class="battery-block">${icon('battery-charging')}<div><small>当前电量</small><strong>${Math.round(f.battery)}<em>%</em></strong></div>${bar(f.battery,f.battery<30?'amber':'green')}</div><div class="kv-list">${kv('当前任务',job?esc(job.id):'暂无任务')}${kv('作业月台',job?.dock?`月台 ${job.dock}`:'—')}${kv('今日搬运',`${f.moves} 托盘`)}${kv('当前速度',`${((state.paused?0:f.motion?.speed||0)*3.6).toFixed(1)} 千米/时`)}${kv('所属园区',cfg.name)}</div><div class="detail-footer">${['working','reserved'].includes(f.status)?btn('select-job','查看运输任务','arrow-up-right','button primary',`data-id="${job.id}"`):f.status==='returning'?btn('follow','跟随返程','navigation','button primary'):btn('charge-fork',f.status==='charging'?'结束充电':'返回充电','battery-charging','button primary',`data-id="${f.id}"`)}${btn('follow','跟随叉车','locate-fixed','button subtle')}</div></div>`;
 }else if(selection.kind==='product'){
  const item=site.inventory.find(i=>i.productId===selection.id);if(!item)return select('site',cfg.id);const p=product(item.productId),available=availableStock(state,cfg.id,p.id),reserved=reservedStock(state,cfg.id,p.id);
  html=detailHeader('package',`货物 · SKU-${p.id.toUpperCase()}`,p.name,p.description)+`<div class="detail-body"><div class="product-preview" style="--package-color:${cssColor(p.color)}">${icon('package')}<span>托盘货物 · ${p.name}</span></div><div class="operation-status"><span class="badge ${item.qty<item.min?'warning':'success'}">${item.qty<item.min?'低于安全库存':'库存健康'}</span><span>${cfg.id} · 暂存区</span></div><div class="kv-list">${kv('现有库存',`${nf(item.qty)} 托盘`)}${kv('可用库存',`${nf(available)} 托盘`)}${kv('运输预留',`${nf(reserved)} 托盘`)}${kv('安全库存',`${item.min} 托盘`)}${kv('库位',`${cfg.id} · STG-${String(cfg.products.indexOf(p.id)+1).padStart(2,'0')}`)}${kv('管理方式','托盘汇总库存')}</div><div class="detail-footer">${btn('replenish','补充库存','plus','button primary',`data-product="${p.id}"`)}${btn('new-shipment','创建出库','arrow-up-from-line','button subtle',`data-product="${p.id}"`)}</div></div>`;
 }else if(selection.kind==='dock'){
  const sh=active.find(s=>s.dock===Number(selection.id));html=detailHeader('warehouse',`${cfg.id} · 装卸月台`,`月台 ${selection.id}`,cfg.name)+`<div class="detail-body"><div class="operation-status"><span class="badge ${sh?'loading':'success'}">${sh?'正在作业':'可用月台'}</span></div><div class="kv-list">${kv('车辆',sh?sh.truckId:'未分配')}${kv('运输单',sh?sh.id:'—')}${kv('叉车',sh?sh.forkId:'—')}${kv('能力','标准装卸 · 40 英尺')}</div>${sh?bar(sh.progress*100,'green'):''}<div class="detail-footer">${sh?btn('select-job','查看运输任务','arrow-up-right','button primary',`data-id="${sh.id}"`):btn('shipments','分配待调度车辆','plus','button primary')}</div></div>`;
 }
 const scroll=$('#detail').scrollTop;$('#detail').innerHTML=html;$('#detail').scrollTop=scroll;
}
function renderFleet(){const cfg=SITES.find(s=>s.id===state.siteId),active=activeShipments(state,cfg.id),forks=state.sites[cfg.id].forks;
 $('#dock-count').textContent=`${active.filter(s=>s.dock).length}/${cfg.docks}`;$('#fork-count').textContent=`${forks.filter(f=>f.status==='working').length}/${forks.length}`;$('#truck-count').textContent=active.length;
 document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===fleetTab));let html='';
 if(fleetTab==='docks')html=Array.from({length:cfg.docks},(_,i)=>{const sh=active.find(s=>s.dock===i+1);return `<button class="fleet-row" data-select="${sh?'truck':'dock'}" data-id="${sh?sh.id:i+1}"><span class="row-id"><b>月台 ${i+1}</b><small>${cfg.id}</small></span><span class="row-main">${sh?`<i class="tiny-dot" style="background:${cssColor(CARRIERS[sh.carrier].color)}"></i>${sh.truckId}`:'暂无车辆'}</span>${sh?badge(sh.status):'<span class="badge idle">可用</span>'}<span class="row-progress">${sh?bar(sh.progress*100,'green'):'—'}<small>${sh?`${Math.floor(sh.progress*sh.qty)}/${sh.qty}`:''}</small></span>${icon('chevron-right')}</button>`;}).join('');
 if(fleetTab==='forks')html=forks.map(f=>`<button class="fleet-row" data-select="fork" data-id="${f.id}"><span class="row-id"><b>${f.id}</b><small>电动叉车</small></span><span class="row-main">${f.jobId||'暂无任务'}</span>${badge(f.status)}<span class="row-progress">${bar(f.battery,f.battery<30?'amber':'green')}<small>${Math.round(f.battery)}%</small></span>${icon('chevron-right')}</button>`).join('');
 if(fleetTab==='trucks')html=active.map(sh=>`<button class="fleet-row" data-select="truck" data-id="${sh.id}"><span class="row-id"><b>${sh.truckId}</b><small>${CARRIERS[sh.carrier].name}</small></span><span class="row-main">${sh.dock?`月台 ${sh.dock}`:sh.status==='queued'?'等待分配':sh.status==='departing'?'驶向出口':'园区外道路'}</span>${badge(sh.status)}<span class="row-progress">${bar(sh.progress*100,'green')}<small>${Math.round(sh.progress*100)}%</small></span>${icon('chevron-right')}</button>`).join('')||'<div class="empty compact">所有车辆作业已完成</div>';
 const scroll=$('#fleet-rows').scrollTop;$('#fleet-rows').innerHTML=html;$('#fleet-rows').scrollTop=scroll;
}
function renderTracking(){let sh;if(selection.kind==='truck')sh=state.shipments.find(s=>s.id===selection.id);else if(selection.kind==='fork'){const f=state.sites[state.siteId].forks.find(f=>f.id===selection.id);sh=state.shipments.find(s=>s.id===f?.jobId);}sh??=activeShipments(state,state.siteId)[0]||state.shipments.find(s=>s.siteId===state.siteId&&s.status==='delivered');
 if(!sh){$('#tracking').innerHTML=`<div class="empty">${icon('truck')}<b>暂无运输任务</b>${btn('new-shipment','创建第一单','plus','text-button')}</div>`;return;}
 const stage={queued:0,arriving:1,loading:2,departing:3,transit:3,unloading:2,delivered:5,cancelled:-1}[sh.status];const labels=sh.direction==='inbound'?['订单确认','驶入月台','卸货入库','驶离园区','入库完成']:['订单确认','驶入月台','装车作业','在途运输','交付签收'];const stages=['clipboard-list','package','box','truck','check'];
 $('#tracking').innerHTML=`<div class="tracking-main"><header><h3>${icon('truck')}运输进度 <span>全程运输跟踪</span></h3><small>${esc(sh.truckId)} · ${CARRIERS[sh.carrier].name}</small></header><div class="timeline">${labels.map((label,i)=>`<div class="timeline-step ${i<stage?'done':''} ${i===stage?'current':''}"><span class="step-circle">${icon(i<stage?'check':stages[i])}</span><b>${label}</b><small>${i<stage?(sh.timeline?.[i]!=null?time(sh.timeline[i]):'已完成'):i===stage?`${Math.round(sh.progress*100)}%`:'待完成'}</small></div>`).join('')}</div></div><button class="shipment-card" data-select="truck" data-id="${sh.id}"><span class="truck-tile">${icon('truck')}</span><span><b>#${esc(sh.id)}</b><small>至 ${esc(demoText(sh.destination))}</small>${badge(sh.status)}<small>${esc(sh.siteId)} ${sh.dock?`· 月台 ${sh.dock}`:''} · ${sh.qty} 托盘</small></span>${icon('chevron-right')}</button>`;
}
function render(){const focused=document.activeElement;const focusData=focused?.closest('#detail, #tracking, #fleet-rows')&&focused.tagName==='BUTTON'?{...focused.dataset}:null;state=store.state;if(lastSite!==state.siteId){lastSite=state.siteId;selection={kind:'site',id:state.siteId};scene?.build(state);}else scene?.sync(state);renderStats();renderDetail();renderFleet();renderTracking();$('#clock').textContent=time(state.clock);$('#live-label').textContent=state.paused?'已暂停':'运行中';$('.live').classList.toggle('is-paused',state.paused);$('#pause-button').innerHTML=icon(state.paused?'play':'pause');$('#pause-button').setAttribute('aria-label',state.paused?'继续模拟':'暂停模拟');$('#pause-button').title=state.paused?'继续模拟':'暂停模拟';$('#notification-dot').hidden=!state.events.some(e=>!e.read);$('#active-total').textContent=state.shipments.filter(s=>!['delivered','cancelled'].includes(s.status)).length;document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===state.speed));if(overlay==='notifications')renderNotifications();drawIcons();if(focusData){const button=[...document.querySelectorAll('#detail button, #tracking button, #fleet-rows button')].find(el=>Object.entries(focusData).every(([k,v])=>el.dataset[k]===v));button?.focus({preventScroll:true});}}
function modal(title,kicker,body,wide=false){const el=$('#modal');overlay='modal';el.className=wide?'wide':'';$('#modal-content').innerHTML=`<header class="modal-header"><div><span class="eyebrow">${kicker}</span><h2 id="modal-title">${title}</h2></div>${iconBtn('close-modal','关闭','x')}</header>${body}`;if(!el.open)el.showModal();drawIcons();}
function closeModal(){$('#modal').close();overlay=null;}
function newShipment(preset){const cfg=SITES.find(s=>s.id===state.siteId);modal('新建运输单',`${cfg.id} / ${cfg.name}`,`<form id="shipment-form" class="form"><div class="form-intro">创建运输任务后，为车辆分配月台与叉车，即可在场景中查看作业过程。</div><div class="form-grid"><label>运输类型<select name="direction" required><option value="outbound">出库配送</option><option value="inbound">入库接收</option></select></label><label>承运商<select name="carrier">${CARRIERS.map((c,i)=>`<option value="${i}">${c.name}</option>`).join('')}</select></label><label class="span-2">货物<select name="productId" required>${cfg.products.map(id=>`<option value="${id}" ${id===preset?'selected':''}>${product(id).name} · 可用 ${availableStock(state,cfg.id,id)} 托盘</option>`).join('')}</select></label><label>数量（托盘）<input name="qty" type="number" min="1" max="1000" step="1" value="6" required></label><label>客户名称<input name="customer" value="阿特拉斯零售" maxlength="100" required></label><label class="span-2">目的地 / 入库来源<input name="destination" value="宾夕法尼亚州费城" maxlength="150" required></label></div><div id="form-error" class="form-error" role="alert"></div><footer class="form-footer">${btn('close-modal','取消',null,'button subtle','type="button"')}<button class="button primary" type="submit">${icon('plus')}创建运输单</button></footer></form>`);}
function dispatchDialog(id){const sh=state.shipments.find(s=>s.id===id);if(!sh)return;const cfg=SITES.find(s=>s.id===sh.siteId);const used=new Set(activeShipments(state,sh.siteId).map(s=>s.dock));const docks=Array.from({length:cfg.docks},(_,i)=>i+1).filter(d=>!used.has(d));const forks=state.sites[sh.siteId].forks.filter(f=>f.status==='idle'&&f.battery>=20);modal('分配作业资源',sh.id,`<form id="dispatch-form" data-id="${sh.id}" class="form"><div class="form-intro">${esc(sh.truckId)} · ${sh.qty} 托盘 ${product(sh.productId).name}</div><div class="form-grid"><label>可用月台<select name="dock" required>${docks.length?docks.map(d=>`<option value="${d}">月台 ${d}</option>`).join(''):'<option value="">暂无可用月台</option>'}</select></label><label>可用叉车<select name="fork" required>${forks.length?forks.map(f=>`<option value="${f.id}">${f.id} · 电量 ${Math.round(f.battery)}%</option>`).join(''):'<option value="">暂无可用叉车</option>'}</select></label></div>${!docks.length||!forks.length?'<p class="form-intro warning-text">资源忙碌中。关闭窗口并等待现有作业结束，或将模拟速度调至 15×。</p>':''}<div id="form-error" class="form-error" role="alert"></div><footer class="form-footer">${btn('close-modal','稍后分配',null,'button subtle','type="button"')}<button class="button primary" type="submit" ${!docks.length||!forks.length?'disabled':''}>${icon('navigation')}开始作业</button></footer></form>`);}
function inventoryDialog(){const cfg=SITES.find(s=>s.id===state.siteId);modal('库存管理',`${cfg.id} / 库存管理`, `<div class="modal-toolbar"><span>${cfg.cn} · ${nf(totalStock(state,cfg.id))} 托盘</span>${btn('export-csv','导出表格','download','button subtle')}</div><div class="table-wrap"><table><thead><tr><th>货物</th><th>实际库存</th><th>可用库存</th><th>预留</th><th>安全库存</th><th>操作</th></tr></thead><tbody>${state.sites[cfg.id].inventory.map(i=>`<tr><td><b>${product(i.productId).name}</b><small>SKU-${i.productId.toUpperCase()}</small></td><td>${nf(i.qty)} ${i.qty<i.min?'<span class="badge warning">偏低</span>':''}</td><td>${nf(availableStock(state,cfg.id,i.productId))}</td><td>${reservedStock(state,cfg.id,i.productId)}</td><td>${i.min}</td><td>${btn('replenish','补货','plus','text-button',`data-product="${i.productId}"`)}</td></tr>`).join('')}</tbody></table></div><div class="modal-note">库存以托盘为单位。预留数量在运输单取消时释放；出库装车完成后从实际库存扣除。</div>`,true);}
function replenishDialog(id){const p=product(id);modal('补充库存',`SKU-${id.toUpperCase()}`,`<form id="replenish-form" class="form" data-product="${id}"><div class="form-intro">${p.name} · ${SITES.find(s=>s.id===state.siteId).cn}</div><label>新增托盘数量<input name="qty" type="number" min="1" max="4200" step="1" value="50" required></label><div id="form-error" class="form-error" role="alert"></div><footer class="form-footer">${btn('close-modal','取消',null,'button subtle','type="button"')}<button type="submit" class="button primary">${icon('check')}确认补货</button></footer></form>`);}
function shipmentsDialog(filter='all'){const list=state.shipments.filter(s=>s.siteId===state.siteId&&(filter==='all'||(filter==='active'?!['delivered','cancelled'].includes(s.status):s.status===filter)));modal('运输订单',`${state.siteId} / 运输订单`, `<div class="modal-toolbar"><div class="filter-tabs">${[['all','全部'],['active','进行中'],['queued','待调度'],['delivered','已完成']].map(([value,label])=>`<button class="${filter===value?'active':''}" data-action="filter-shipments" data-filter="${value}">${label}</button>`).join('')}</div>${btn('new-shipment','新建运输单','plus','button primary')}</div><div class="table-wrap"><table><thead><tr><th>运输单 / 车辆</th><th>货物 / 数量</th><th>目的地</th><th>状态</th><th>操作</th></tr></thead><tbody>${list.map(sh=>`<tr><td><b>#${esc(sh.id)}</b><small>${esc(sh.truckId)} · ${CARRIERS[sh.carrier].name}</small></td><td>${product(sh.productId).name}<small>${sh.qty} 托盘 · ${sh.direction==='inbound'?'入库':'出库'}</small></td><td>${esc(demoText(sh.destination))}</td><td>${badge(sh.status)}</td><td>${sh.status==='queued'?btn('dispatch','调度','navigation','text-button',`data-id="${sh.id}"`):btn('open-truck','查看','arrow-up-right','text-button',`data-id="${sh.id}"`)}</td></tr>`).join('')||'<tr><td colspan="5"><div class="empty">当前筛选下暂无运输单</div></td></tr>'}</tbody></table></div><div class="modal-note">列表为打开时的快照。详情与场景会随模拟实时更新。</div>`,true);}
function fleetDialog(){modal('叉车管理',`${state.siteId} / 叉车管理`,`<div class="fleet-cards">${state.sites[state.siteId].forks.map(f=>`<article><span class="fork-illustration">${icon('forklift')}</span><div><h3>${f.id}</h3>${badge(f.status)}</div>${bar(f.battery,f.battery<30?'amber':'green')}<p>电量 ${Math.round(f.battery)}% · 已搬运 ${f.moves} 托盘</p>${btn('open-fork','查看叉车','locate-fixed','button subtle',`data-id="${f.id}"`)}</article>`).join('')}</div>`,true);}
function reportsDialog(){const max=Math.max(...SITES.map(s=>totalStock(state,s.id)));modal('园区运营报表','运营统计 / 全部园区',`<div class="report-summary"><div><small>全部园区库存</small><b>${nf(SITES.reduce((n,s)=>n+totalStock(state,s.id),0))}</b><span>托盘</span></div><div><small>今日累计出库</small><b>${SITES.reduce((n,s)=>n+state.sites[s.id].outbound,0)}</b><span>车次</span></div><div><small>完成运输单</small><b>${state.shipments.filter(s=>s.status==='delivered').length}</b><span>本次模拟</span></div></div><div class="report-chart"><h3>各园区库存与容量</h3>${SITES.map(s=>`<div class="report-row"><span>${s.name}<small>${s.type}</small></span><div><div class="report-track"><span style="width:${totalStock(state,s.id)/s.capacity*100}%"></span></div></div><b>${nf(totalStock(state,s.id))}<small>/ ${nf(s.capacity)}</small></b></div>`).join('')}</div><div class="modal-note">报表来自当前本地模拟状态；准时率采用预置演示基线。${btn('export-csv','导出库存明细','download','text-button')}</div>`,true);}
function settingsDialog(){modal('工作台设置','工作台 / 偏好设置',`<div class="settings-body"><div class="settings-group">${[['labels','场景定位标记','显示货物上方的蓝色定位标记'],['shadows','柔和阴影','开启物体投影，增强空间层次'],['autoRotate','自动环绕','让镜头缓慢环绕仓库']].map(([key,label,desc])=>`<label class="setting"><span><b>${label}</b><small>${desc}</small></span><input type="checkbox" data-setting="${key}" ${state.settings[key]?'checked':''}></label>`).join('')}</div><h3>存档与数据</h3><p class="muted">所有数据保存在当前浏览器，可导出存档文件后在其他设备导入。</p><div class="settings-buttons">${btn('export-json','导出存档','download','button subtle')}${btn('import-json','导入存档','upload','button subtle')}${btn('reset-confirm','重置演示','rotate-ccw','button subtle danger')}</div></div>`);}
function helpDialog(){modal('把仓库，放在你的掌心','欢迎使用仓流智控',`<div class="help-body"><p>一个可实际操作的三维仓储调度沙盘。5 个园区各自拥有独立库存、月台、叉车和车辆。</p><div class="help-steps"><div><b>01</b><span><strong>探索园区</strong>点击右上方切换园区，拖动场景旋转、滚轮缩放、右键平移。点击货盘、叉车或卡车，查看右侧详情。</span></div><div><b>02</b><span><strong>创建运输任务</strong>点击「新建运输单」，选择出库或入库、货物数量及目的地。出库数量会先预留。</span></div><div><b>03</b><span><strong>分配资源，观察流转</strong>为运输单分配空闲月台与叉车。装卸、车辆、库存与运输进度同步变化，可用 15× 加速。</span></div></div><div class="shortcuts"><span><kbd>/</kbd> 搜索</span><span><kbd>空格键</kbd> 暂停 / 继续</span><span><kbd>H</kbd> 重置视角</span><span><kbd>退出键</kbd> 关闭弹窗</span></div><p class="muted">本项目使用本地演示数据，无需账号或外部服务。点击右下方速度按钮可控制整个园区模拟。</p></div>`);}
function renderNotifications(){const el=$('#popover');el.innerHTML=`<header><h3>运营动态</h3>${btn('read-notifications','全部已读','check-check','text-button')}</header><div class="event-list">${state.events.slice(0,15).map(ev=>`<article class="event ${ev.read?'read':''}"><span class="event-icon ${ev.kind}">${icon(ev.kind==='warning'?'alert-triangle':ev.kind==='success'?'check-circle-2':'radio')}</span><div><p>${esc(eventText(ev.text))}</p><small>${time(ev.time)} · ${ev.read?'已读':'新动态'}</small></div></article>`).join('')}</div>`;drawIcons();}
function download(name,content,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportCsv(){const rows=[['园区编号','园区名称','商品','实际库存(托盘)','可用库存(托盘)','安全库存']];for(const cfg of SITES)for(const i of state.sites[cfg.id].inventory)rows.push([cfg.id,cfg.name,product(i.productId).name,i.qty,availableStock(state,cfg.id,i.productId),i.min]);download('仓流智控-库存明细.csv','\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8');toast('库存明细已导出');}
const actions={
 'home':()=>{scene?.home();select('site',state.siteId);},'overview':()=>select('site',state.siteId),'zoom-in':()=>scene?.zoom(1.2),'zoom-out':()=>scene?.zoom(1/1.2),'rotate-left':()=>scene?.rotate(-1),'rotate-right':()=>scene?.rotate(1),'top-view':()=>scene?.top(),'focus':()=>scene?.focus(selection.kind,selection.id),'follow':()=>scene?.follow(selection.kind,selection.id),
 'drive-demo':()=>{const cfg=SITES.find(s=>s.id===state.siteId),site=state.sites[state.siteId];let sh=activeShipments(state,state.siteId).find(s=>s.demo);if(!sh){const used=new Set(activeShipments(state,state.siteId).map(s=>s.dock));const dock=Array.from({length:cfg.docks},(_,i)=>i+1).find(d=>!used.has(d));const fork=site.forks.find(f=>f.status==='idle'&&f.battery>=20)||site.forks.find(f=>f.status==='charging'&&f.battery>=20);if(!dock||!fork){store.setSimulation({paused:false});throw Error('现有车辆正在作业，模拟已继续；资源空闲后可添加演示车辆');}if(fork.status==='charging')store.chargeFork(cfg.id,fork.id);const item=site.inventory.find(i=>availableStock(state,cfg.id,i.productId)>=2);if(!item)throw Error('没有足够的演示库存');sh=store.createShipment({siteId:cfg.id,productId:item.productId,qty:2,direction:'outbound',carrier:0,customer:'车辆行驶演示',destination:'新泽西州纽瓦克市'});sh.demo=true;store.dispatch(sh.id,dock,fork.id);}store.setSimulation({paused:false,speed:1});scene?.home();select('truck',sh.id);toast('车辆开始进场：转弯 → 倒车入位 → 叉车搬运 → 驶离');},
 'pause':()=>store.setSimulation({paused:!state.paused}),'speed':el=>store.setSimulation({speed:Number(el.dataset.speed)}),
 'inventory':inventoryDialog,'shipments':()=>shipmentsDialog(),'fleet':fleetDialog,'reports':reportsDialog,'settings':settingsDialog,'help':helpDialog,
 'new-shipment':el=>newShipment(el.dataset.product),'dispatch':el=>dispatchDialog(el.dataset.id),'replenish':el=>replenishDialog(el.dataset.product),
 'select-job':el=>select('truck',el.dataset.id,true),'open-truck':el=>{closeModal();select('truck',el.dataset.id,true);},'open-fork':el=>{closeModal();select('fork',el.dataset.id,true);},
 'charge-fork':el=>{store.chargeFork(state.siteId,el.dataset.id);toast('叉车充电状态已更新');},'cancel-shipment':el=>{const id=el.dataset.id;modal('取消这笔运输？',id,`<div class="form"><p>取消后，将释放预留库存、叉车和月台。已完成的出库运输无法取消。</p><footer class="form-footer">${btn('close-modal','保留运输单',null,'button subtle')}${btn('confirm-cancel','确认取消',null,'button primary',`data-id="${id}"`)}</footer></div>`);},'confirm-cancel':el=>{store.cancelShipment(el.dataset.id);closeModal();toast('运输单已取消，资源已释放');},
 'close-modal':closeModal,'filter-shipments':el=>shipmentsDialog(el.dataset.filter),
 'notifications':()=>{const el=$('#popover');el.hidden=!el.hidden;overlay=el.hidden?null:'notifications';if(!el.hidden)renderNotifications();},'read-notifications':()=>store.markRead(),
 'export-csv':exportCsv,'export-json':()=>{download('仓流智控-存档.json',JSON.stringify(state,null,2),'application/json');toast('存档已导出');},'import-json':()=>$('#import-file').click(),
 'reset-confirm':()=>modal('重置演示数据？','重置 / 本地数据',`<div class="form"><p>这会恢复最初的 5 个园区及运输任务。建议先导出存档，以便随时恢复。</p><footer class="form-footer">${btn('export-json','先导出存档','download','button subtle')}${btn('reset','确认重置',null,'button primary')}</footer></div>`),
 'reset':()=>{store.reset();store.save(localStorage);closeModal();toast('演示已重置');}
};
root.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.action)doAction(()=>actions[button.dataset.action]?.(button));if(button.dataset.select)select(button.dataset.select,button.dataset.id);if(button.dataset.tab){fleetTab=button.dataset.tab;renderFleet();drawIcons();}});
$('#site-select').addEventListener('change',e=>changeSite(e.target.value));
$('#modal').addEventListener('close',()=>overlay=null);$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const rect=$('#modal').getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)closeModal();}});
root.addEventListener('change',e=>{if(e.target.dataset.setting)store.setSetting(e.target.dataset.setting,e.target.checked);});
root.addEventListener('submit',e=>{e.preventDefault();const form=e.target,data=Object.fromEntries(new FormData(form));try{if(form.id==='shipment-form'){const sh=store.createShipment(data);closeModal();select('truck',sh.id);toast('运输单已创建，请分配作业资源');dispatchDialog(sh.id);}if(form.id==='dispatch-form'){store.dispatch(form.dataset.id,data.dock,data.fork);closeModal();select('truck',form.dataset.id,true);toast('调度成功，车辆正沿园区道路驶向月台');store.setSimulation({paused:false});}if(form.id==='replenish-form'){store.replenish(state.siteId,form.dataset.product,data.qty);closeModal();select('product',form.dataset.product);toast(`已补货 ${data.qty} 托盘`);}}catch(error){const el=$('#form-error');if(el)el.textContent=error.message;else toast(error.message,true);}});
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2_000_000)throw Error('存档文件不能超过 2 兆字节');const data=JSON.parse(await file.text());store.restore(data);store.save(localStorage);closeModal();toast('存档已恢复');}catch(error){toast(error instanceof SyntaxError?'导入失败：存档格式不正确，请选择导出的存档文件':`导入失败：${error.message}`,true);}e.target.value='';});
function search(query){const q=query.trim().toLowerCase(),el=$('#search-results');if(!q){el.hidden=true;return;}const result=[];for(const site of SITES){if(`${site.id} ${site.name} ${site.en}`.toLowerCase().includes(q))result.push({kind:'site',id:site.id,siteId:site.id,label:site.name,sub:site.type,ico:'warehouse'});for(const i of state.sites[site.id].inventory){const p=product(i.productId);if(`${p.id} ${p.name} ${p.en}`.toLowerCase().includes(q))result.push({kind:'product',id:p.id,siteId:site.id,label:p.name,sub:`${site.id} · ${site.cn}`,ico:'package'});}for(const f of state.sites[site.id].forks)if(f.id.toLowerCase().includes(q))result.push({kind:'fork',id:f.id,siteId:site.id,label:f.id,sub:site.name,ico:'forklift'});}for(const sh of state.shipments)if(`${sh.id} ${sh.truckId} ${demoText(sh.destination)} ${demoText(sh.customer)} ${sh.destination} ${sh.customer}`.toLowerCase().includes(q))result.push({kind:'truck',id:sh.id,siteId:sh.siteId,label:`${sh.truckId} · ${sh.id}`,sub:`${demoText(sh.destination)} · ${STATUS[sh.status]}`,ico:'truck'});el.hidden=false;el.innerHTML=`<div class="search-caption">搜索结果 <span>${result.length}</span></div>${result.slice(0,12).map(r=>`<button class="search-result" data-search-kind="${r.kind}" data-search-id="${esc(r.id)}" data-search-site="${r.siteId}">${icon(r.ico)}<span><b>${esc(r.label)}</b><small>${esc(r.sub)}</small></span>${icon('arrow-up-right')}</button>`).join('')||'<div class="empty compact">没有找到匹配结果</div>'}`;drawIcons();}
$('#global-search').addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>search(e.target.value),100);});
$('#global-search').addEventListener('keydown',e=>{if(e.key==='ArrowDown'){$('#search-results button')?.focus();e.preventDefault();}if(e.key==='Enter')$('#search-results button')?.click();if(e.key==='Escape')$('#search-results').hidden=true;});
$('#search-results').addEventListener('click',e=>{const b=e.target.closest('[data-search-kind]');if(!b)return;if(state.siteId!==b.dataset.searchSite)changeSite(b.dataset.searchSite);select(b.dataset.searchKind,b.dataset.searchId,true);$('#search-results').hidden=true;$('#global-search').value='';});
$('#search-results').addEventListener('keydown',e=>{const buttons=[...$('#search-results').querySelectorAll('button')],i=buttons.indexOf(document.activeElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();buttons[(i+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}});
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.search-wrap'))$('#search-results').hidden=true;if(!e.target.closest('#popover')&&!e.target.closest('[data-action="notifications"]')){$('#popover').hidden=true;if(overlay==='notifications')overlay=null;}});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||$('#modal').open)return;if(e.key==='/'){e.preventDefault();$('#global-search').focus();}if(e.code==='Space'){e.preventDefault();store.setSimulation({paused:!state.paused});}if(e.key.toLowerCase()==='h')scene?.home();if(e.key==='Escape'){$('#search-results').hidden=true;$('#popover').hidden=true;overlay=null;}});
try{scene=new WarehouseScene($('#scene'),{onSelect:(kind,id)=>select(kind,id),onHover:(entity,x,y)=>{const el=$('#tooltip');el.hidden=!entity;if(entity){el.textContent=entity.label;el.style.left=`${Math.min(x+14,innerWidth-240)}px`;el.style.top=`${Math.max(70,y-40)}px`;}}});scene.build(state);$('.loading')?.remove();}catch(error){$('.loading').innerHTML=`${icon('alert-triangle')}<b>三维场景暂时无法加载</b><span>请使用支持三维图形的现代浏览器。库存与调度功能仍可使用。</span>`;console.error(error);}
$('#scene').addEventListener('scene-error',e=>toast(e.detail,true));
let lastPaint=0;store.subscribe((_,reason)=>{const now=performance.now();if(reason!=='tick'||now-lastPaint>180||store.state.paused){lastPaint=now;render();}else{state=store.state;if(scene)scene.state=state;}});render();
setInterval(()=>store.tick(.05),50);setInterval(()=>{const ok=store.save(localStorage);$('#save-status').textContent=ok?'本地演示 · 已自动保存':'本地存储不可用 · 请导出存档';},4000);
window.addEventListener('pagehide',()=>store.save(localStorage));
if(loadFailed)toast('未能读取原有存档，已载入初始演示数据',true);
