import test from 'node:test';
import assert from 'node:assert/strict';
import {STATIONS,CONTRACTS,newGame,railPath,planTrack,buildTrack,removeTrack,setRoute,buyTrain,upgradeTrain,repairTrain,claimContract,tick,restore,key,isRiver,blocked} from '../model.js';
const station=id=>STATIONS.find(s=>s.id===id);
function connect(s,a,b,bridge=true){const p=planTrack(s,station(a),station(b),bridge);assert.equal(p.error,undefined);const r=buildTrack(s,p);assert.equal(r.ok,true);return p;}
function advance(s,seconds){const events=[];for(let i=0;i<seconds*10;i++)events.push(...tick(s,.1));return events;}
test('initial network connects two towns, first train actually delivers and earns revenue',()=>{const s=newGame();assert.equal(railPath(s,station('pine'),station('canyon')).length,12);const events=advance(s,20);assert.ok(events.some(e=>e.type==='delivery'&&e.to==='canyon'&&e.good==='grain'));assert.ok(s.money>6800);assert.ok(s.revenue>=450);assert.ok(s.deliveries>=6);});
test('track plans avoid building footprints and account for construction costs',()=>{const s=newGame();const p=connect(s,'canyon','forest');assert.ok(p.fresh.length>0);assert.equal(p.price,p.fresh.length*60);assert.equal(s.money,6800-p.price);assert.ok(p.path.every(([x,z])=>!blocked(x,z)));assert.ok(railPath(s,station('forest'),station('canyon')));});
test('river cannot be crossed by ordinary track; bridges connect both banks',()=>{const s=newGame();s.money=100000;assert.match(planTrack(s,station('canyon'),station('mine'),false).error,/跨河/);const p=connect(s,'canyon','mine');assert.ok(p.bridges>0);assert.equal(p.price,p.fresh.filter(([x,z])=>!isRiver(x,z)).length*60+p.bridges*240);assert.ok(railPath(s,station('canyon'),station('mine')));});
test('insufficient construction funds leave money and rail map unchanged',()=>{const s=newGame();const p=planTrack(s,station('canyon'),station('forest'));s.money=0;const before=JSON.stringify(s);assert.ok(buildTrack(s,p).error);assert.equal(JSON.stringify(s),before);});
test('active tracks and station tracks are protected; unused spur can be removed',()=>{const s=newGame();assert.ok(removeTrack(s,-5,1).error);assert.ok(removeTrack(s,0,1).error);s.tracks[key(1,1)]='rail';assert.equal(removeTrack(s,1,1).refund,30);assert.equal(s.tracks[key(1,1)],undefined);});
test('route rejects disconnected, same-station, and incompatible station pairs',()=>{const s=newGame(),t=s.trains[0];assert.ok(setRoute(s,t,'pine','mine').error);assert.ok(setRoute(s,t,'pine','pine').error);s.money=100000;connect(s,'pine','ranch');assert.ok(setRoute(s,t,'pine','ranch').error);assert.ok(setRoute(s,t,'invalid','mine').error);});
test('wood deliveries progress a real contract, one-time reward cannot be claimed twice',()=>{const s=newGame();connect(s,'canyon','forest');setRoute(s,s.trains[0],'forest','canyon');advance(s,240);assert.ok(s.contracts.wood>=12);const before=s.money;assert.equal(claimContract(s,'wood').reward,2200);assert.equal(s.money,before+2200);assert.ok(claimContract(s,'wood').error);assert.ok(claimContract(s,'ore').error);});
test('purchase, upgrade, capacity, and repairs enforce costs and limits',()=>{const s=newGame();const first=buyTrain(s);assert.equal(first.ok,true);assert.equal(s.money,5000);assert.equal(buyTrain(s).ok,true);assert.equal(s.money,2600);const t=s.trains[0];assert.equal(upgradeTrain(s,t).ok,true);assert.equal(t.level,2);assert.ok(upgradeTrain(s,t).error);t.condition=80;assert.equal(repairTrain(s,t).price,160);assert.equal(t.condition,100);s.money=100000;while(s.trains.length<6)assert.equal(buyTrain(s).ok,true);assert.ok(buyTrain(s).error);});
test('zero time freezes all economic simulation and stock never exceeds capacity',()=>{const s=newGame(),before=JSON.stringify(s);tick(s,0);assert.equal(JSON.stringify(s),before);advance(s,500);assert.ok(Object.values(s.stocks).every(n=>n>=0&&n<=80));});
test('all three contracts and all six stations form a reachable completion loop',()=>{const s=newGame();s.money=30000;connect(s,'canyon','forest');connect(s,'canyon','ranch');connect(s,'ranch','mine');connect(s,'mine','silver');setRoute(s,s.trains[0],'forest','canyon');assert.ok(buyTrain(s,'ranch','mine').ok);assert.ok(buyTrain(s,'mine','silver').ok);advance(s,900);for(const c of CONTRACTS){assert.ok(s.contracts[c.id]>=c.amount,`${c.id} deliveries`);assert.ok(claimContract(s,c.id).ok);}const events=tick(s,.1);assert.ok(s.won);assert.equal(events.filter(e=>e.type==='win').length,1);assert.equal(tick(s,.1).filter(e=>e.type==='win').length,0);});
test('save round-trip preserves trains and routes and rejects corrupt saves',()=>{const s=newGame();advance(s,19);assert.deepEqual(restore(JSON.stringify(s)),s);assert.equal(restore('broken'),null);assert.equal(restore('{"version":1}'),null);const bad=structuredClone(s);bad.trains[0].from='missing';assert.equal(restore(bad),null);const bad2=structuredClone(s);bad2.money=-4;assert.equal(restore(bad2),null);});
