'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {DestroyGame,drawWeapon,WEAPONS} from '@/lib/game';
type Room={code:string;id:string;token:string};
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),game=useRef<any>(null),roomRef=useRef<Room|null>(null),pending=useRef<any[]>([]),round=useRef(-1),since=useRef(0),currentMap=useRef('demo');const [panel,setPanel]=useState('title'),[url,setUrl]=useState(''),[code,setCode]=useState(''),[name,setName]=useState('玩家'),[room,setRoom]=useState<Room|null>(null),[roomInfo,setRoomInfo]=useState<any>(null),[players,setPlayers]=useState<any[]>([]),[ui,setUI]=useState<any>({weapon:0,progress:0}),[background,setBackground]=useState('cities'),[sound,setSound]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[embedTheme,setEmbedTheme]=useState('dark'),[embed,setEmbed]=useState(''),[connected,setConnected]=useState(true);const panelRef=useRef('title'),nameRef=useRef(name),actions=useRef<any>({});
useEffect(()=>{panelRef.current=panel;if(game.current){game.current.menu=['title','lobby','loading'].includes(panel);game.current.paused=!roomRef.current&&panel!=='';}},[panel]);useEffect(()=>{nameRef.current=name;},[name]);
useEffect(()=>{const g:any=new DestroyGame(canvas.current,(data:any)=>setUI((old:any)=>({...old,...data})),(event:any)=>{if(roomRef.current)pending.current.push(event)});game.current=g;g.onPause=(force:boolean)=>{if(panelRef.current===''){setPanel('pause');}else if(panelRef.current==='pause'&&!force)setPanel('');};g.onComplete=()=>{if(!roomRef.current)setPanel('complete')};const saved=localStorage.getItem('destroy-preferences');if(saved)try{const prefs=JSON.parse(saved);g.bg=prefs.background||'cities';g.sound=prefs.sound!==false;setBackground(g.bg);setSound(g.sound);}catch{}const params=new URLSearchParams(location.search);if(params.get('room')){setCode(params.get('room')!);const stored=sessionStorage.getItem('destroy-room-'+params.get('room'));if(stored)try{const session=JSON.parse(stored);roomRef.current=session;setRoom(session);setPanel('lobby');}catch{}}else if(params.get('map')){actions.current.start(params.get('map'));}return()=>g.destroy();},[]);
useEffect(()=>{if(!room)return;let active=true,timer:ReturnType<typeof setTimeout>;const sync=async()=>{try{const sent=pending.current.splice(0,12);const data=await api({action:'sync',...room,name:nameRef.current,state:game.current.state(),round:round.current,events:sent,since:since.current});if(!active)return;setConnected(true);setRoomInfo(data.room);setPlayers(data.players);const me=data.players.find((p:any)=>p.id===room.id);if(me){game.current.p.color=me.color;setUI((old:any)=>({...old,health:me.health,kills:me.kills}));}game.current.remote=data.players.filter((p:any)=>p.id!==room.id);if(data.room.round!==round.current&&data.room.phase!=='lobby'){round.current=data.room.round;since.current=0;pending.current=[];await loadMap(data.room.map);if(!active)return;setPanel('');}for(const e of data.events){since.current=Math.max(since.current,e.id);if(e.data.respawn){if(e.player===room.id){game.current.p.x=200+Math.random()*800;game.current.p.y=150;game.current.p.vy=0;setNotice('你已重生');}continue;}if(e.player!==room.id)game.current.blast(e.data.x,e.data.y,e.data.r,e.data.kind,false,e.data.seed);}if(data.room.phase==='over')setPanel('over');}catch(e){if(active){setConnected(false);setError(e instanceof Error&&/[\u4e00-\u9fff]/.test(e.message)?e.message:'连接中断，请稍后重试');}}if(active)timer=setTimeout(sync,350);};sync();return()=>{active=false;clearTimeout(timer)};},[room]);
useEffect(()=>{localStorage.setItem('destroy-preferences',JSON.stringify({background,sound}));if(game.current){game.current.bg=background;game.current.sound=sound;}},[background,sound]);
useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3000);return()=>clearTimeout(t)},[notice]);
useEffect(()=>{if(panel==='embed'){setEmbed(`<a href="${location.origin}/?from=badge" target="_blank" rel="noopener"><img src="${location.origin}/badge-${embedTheme}.svg" width="180" height="40" alt="摧毁这个网页" /></a>`);}},[panel,embedTheme]);
async function api(data:any){const r=await fetch('/api/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'房间暂不可用，请重试');return d;}
async function capture(value:string){setBusy('正在截取公开网页…');const r=await fetch('/api/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:value})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);return d.id;}
async function loadMap(map:string){currentMap.current=map;setBusy(map==='demo'||map==='wiki'?'正在切分网页…':'正在加载截图…');await game.current.loadMap(map,['demo','wiki'].includes(map)?undefined:'/api/map?id='+map);setUI((v:any)=>({...v,progress:0}));setBusy('');}
async function start(map:string='url'){setError('');setBusy('正在准备关卡…');setPanel('loading');try{const id=map==='url'?await capture(url):map;await loadMap(id);setPanel('');requestAnimationFrame(()=>canvas.current?.focus());game.current.ensureAudio();if(!roomRef.current)history.replaceState(null,'','?map='+id);}catch(e){setError(e instanceof Error&&/[\u4e00-\u9fff]/.test(e.message)?e.message:'无法打开此网页，请稍后重试');setPanel('title');}finally{setBusy('');}}
actions.current.start=start;
async function join(create=false){setBusy(create?'正在创建房间…':'正在加入房间…');setError('');try{const d=await api({action:create?'create':'join',name,code});const r={code:d.code,id:d.id,token:d.token};roomRef.current=r;setRoom(r);round.current=-1;since.current=0;sessionStorage.setItem('destroy-room-'+r.code,JSON.stringify(r));history.replaceState(null,'','?room='+r.code);setPanel('lobby');}catch(e){setError(e instanceof Error&&/[\u4e00-\u9fff]/.test(e.message)?e.message:'无法加入房间，请检查房间码');}finally{setBusy('');}}
async function leave(){const r=roomRef.current;if(r){await api({action:'leave',...r}).catch(()=>{});sessionStorage.removeItem('destroy-room-'+r.code);}roomRef.current=null;setRoom(null);setRoomInfo(null);setPlayers([]);game.current.remote=[];round.current=-1;pending.current=[];history.replaceState(null,'','/');setPanel('title');setError('');}
async function startMatch(map:string){setBusy('正在准备对局…');setError('');try{const id=map==='url'?await capture(url):map;await api({action:'start',...room,name,map:id});}catch(e){setError(e instanceof Error&&/[\u4e00-\u9fff]/.test(e.message)?e.message:'无法开始对局，请重试');}finally{setBusy('');}}
async function copy(text:string,message='已复制'){try{await navigator.clipboard.writeText(text);setNotice(message);}catch{setNotice('请手动复制：'+text);}}
async function share(){const link=location.origin+(room?'/?room='+room.code:panel==='title'?'/':'/?map='+currentMap.current);await copy(link,'链接已复制');}
function touch(key:string,on:boolean){game.current?.touch(key,on)}
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const abort=new AbortController();context.registerTool({name:'read_game_state',description:'读取当前网页破坏游戏的状态',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({map:currentMap.current,weapon:WEAPONS[game.current?.weapon||0],progress:game.current?.area||0,room:roomRef.current?.code||null,panel:panelRef.current})},{signal:abort.signal});context.registerTool({name:'start_demo_game',description:'开始或重新开始内置网页破坏演示',inputSchema:{type:'object',properties:{map:{type:'string',enum:['demo','wiki']}},required:['map'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!['demo','wiki'].includes(input?.map))throw new Error('请选择演示网页或维基百科示例');if(roomRef.current)throw new Error('请先退出多人房间');await actions.current.start(input.map);return{map:input.map,started:true};}},{signal:abort.signal});return()=>abort.abort()},[]);
const openGame=!['title','lobby','loading'].includes(panel),host=roomInfo?.host===room?.id;
return <main className="game-app"><header className="topbar"><strong>摧毁任意网页</strong><span className="byline">Pixel Lab <a href="https://destroy.spritefusion.com/" target="_blank" rel="noreferrer">原版网站 ↗</a></span><div className="top-actions"><button onClick={share}>{openGame?'分享此关卡':'分享'}</button>{openGame&&!room&&<button onClick={()=>{setPanel('title');setNotice('请在下方创建或加入房间')}}>多人对战</button>}<button onClick={()=>setPanel('about')} aria-label="关于与素材来源">?</button></div></header><section className="stage" aria-label="网页破坏游戏"><canvas ref={canvas} tabIndex={0} aria-label="游戏画布。A、D 移动，空格键跳跃或飞行，鼠标瞄准并射击，右键投掷手雷，数字键 1 至 0 切换武器，Esc 暂停。" />
{openGame&&<><div className="progress-box" aria-label={`已摧毁 ${ui.progress}%`}><div><i style={{width:ui.progress+'%'}} /></div><b>{ui.progress}%</b></div><button className="pause-button" onClick={()=>setPanel('pause')} aria-label="暂停游戏">Ⅱ</button><div className="weapons" aria-label="武器">{WEAPONS.map((w,i)=><button key={w} title={w} aria-label={(i+1)%10+' '+w} className={ui.weapon===i?'selected':''} onClick={()=>{game.current.setWeapon(i);canvas.current?.focus()}}><small>{(i+1)%10}</small><Weapon index={i}/></button>)}<button title="手雷" aria-label="投掷手雷" onClick={()=>game.current.grenade()}><small>RMB</small><Weapon index={10}/></button></div><div className="weapon-name">{WEAPONS[ui.weapon]}</div><div className="quick-hint"><kbd>A D</kbd> 移动　<kbd>Space</kbd> 跳跃 · 长按飞行　<kbd>鼠标</kbd> 射击　<kbd>Esc</kbd> 暂停</div><div className="touch-controls"><div className="touch-move">{[['KeyA','◀'],['KeyD','▶'],['KeyS','▼']].map(([key,label])=><button key={key} aria-label={({'KeyA':'向左移动','KeyD':'向右移动','KeyS':'向下穿过平台','Space':'跳跃或飞行','grenade':'投掷手雷','fire':'射击'} as Record<string,string>)[key]} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);touch(key,true)}} onPointerUp={()=>touch(key,false)} onPointerCancel={()=>touch(key,false)}>{label}</button>)}</div><div className="touch-shoot">{[['Space','↑'],['grenade','◉'],['fire','射击']].map(([key,label])=><button key={key} aria-label={({'KeyA':'向左移动','KeyD':'向右移动','KeyS':'向下穿过平台','Space':'跳跃或飞行','grenade':'投掷手雷','fire':'射击'} as Record<string,string>)[key]} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);touch(key,true)}} onPointerUp={()=>touch(key,false)} onPointerCancel={()=>touch(key,false)}>{label}</button>)}</div></div></>}
{room&&openGame&&<><div className="health">{ui.kills||0} 次击败 <span>生命 {ui.health??100}</span><i style={{width:(ui.health??100)+'%'}}/></div><button className="score-toggle" onClick={()=>setUI((v:any)=>({...v,scoreboard:!v.scoreboard}))}>排行榜 · 先达 10 次击败者胜</button>{ui.scoreboard&&<div className="scoreboard">{players.map(p=><div key={p.id} style={{color:p.color}}>{p.name} <b>{p.kills}</b></div>)}</div>}{!connected&&<div className="connection">连接已断开，正在重连…</div>}</>}
</section>
<Dialog open={!!panel} onOpenChange={open=>{if(!open&&!['title','loading','lobby'].includes(panel))setPanel('')}}><DialogContent className={'pixel-window '+(panel==='pause'?'pause-window':'')} showCloseButton={false} onEscapeKeyDown={e=>{if(['title','loading','lobby'].includes(panel))e.preventDefault()}} onPointerDownOutside={e=>e.preventDefault()}>{!['title','loading','lobby'].includes(panel)&&<button className="dialog-close" aria-label="关闭" onClick={()=>setPanel('')}>×</button>}<DialogTitle className="window-title">{({title:'Pixel Lab 出品',pause:'已暂停',embed:'嵌入你的网站',lobby:'多人对战 · '+room?.code,complete:'网页已摧毁',over:'对局结束',about:'关于此复刻版本',loading:currentMap.current==='demo'?'演示网页':'网页截图'} as any)[panel]||'摧毁任意网页'}</DialogTitle><DialogDescription className="sr-only">网页破坏沙盒的操作和设置</DialogDescription><div className="window-body">
{panel==='title'&&<><h1>摧毁任意网页</h1><p className="subtitle">输入网址，把整个网页砸个粉碎。</p><form className="url-form" onSubmit={e=>{e.preventDefault();start()}}><div className="url-input"><span>https://</span><input aria-label="网页地址" placeholder="wikipedia.org" value={url} onChange={e=>setUrl(e.target.value)} required /></div><button type="submit" disabled={!!busy}>⚡ 摧毁</button></form><div className="try-line"><span>试试</span><button onClick={()=>start('demo')}>演示网页</button><button onClick={()=>start('wiki')}>维基百科</button></div><p className="caption">点击“摧毁”后，公开网址将发送至 thum.io，生成 1200 × 1200 截图。不支持私密页面、登录凭据或带查询参数的网址。</p><div className="multiplayer-title">多人对战</div><div className="room-form"><button onClick={()=>join(true)} disabled={!!busy}>创建房间</button><input aria-label="房间码" placeholder="房间码" maxLength={6} value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button onClick={()=>join()} disabled={!!busy||code.length!==6}>加入</button></div><button className="minor" onClick={()=>setPanel('embed')}>嵌入你的网站</button><div className="instructions-short"><span><kbd>A</kbd> <kbd>D</kbd> 移动</span><span><kbd>Space</kbd> 跳跃 · 长按飞行</span><span>◧ 射击</span><span>◨ 手雷</span></div><button className="text-link" onClick={()=>setPanel('about')}>独立复刻 · 素材来源与版本差异</button></>}
{panel==='loading'&&<div className="loading"><p>{busy||'正在加载…'}</p><div className="loading-bar"><i/></div><p className="caption">公开网页截图最长可能需要 45 秒</p></div>}
{panel==='pause'&&<><div className="three-buttons"><button onClick={()=>setPanel('')}>继续游戏</button>{!room&&<><button onClick={()=>start(currentMap.current)}>重置网页</button><button onClick={()=>{setPanel('title');history.replaceState(null,'','/')}}>更换网页</button></>}{room&&<button onClick={leave}>退出房间</button>}</div><button className="minor" onClick={()=>setPanel('embed')}>嵌入你的网站</button><div className="weapon-showcase">{[1,2,3,4,6].map(i=><button key={i} aria-label={'选择武器：'+WEAPONS[i]} onClick={()=>{game.current.setWeapon(i);setPanel('')}}><Weapon index={i}/></button>)}</div><p className="setting-label">背景</p><div className="three-buttons">{[['mountain','黄昏山景'],['sunny','晴日海岸'],['cities','霓虹城市']].map(([key,label])=><button className={background===key?'active':''} key={key} onClick={()=>setBackground(key)}>{label}</button>)}</div><p className="setting-label">音效</p><div className="two-buttons"><button className={sound?'active':''} onClick={()=>{game.current.ensureAudio();setSound(true)}}>开启</button><button className={!sound?'active':''} onClick={()=>setSound(false)}>关闭</button></div><div className="controls-list"><span>A D / 方向键</span><span>左右移动</span><span>空格 / W</span><span>跳跃；空中再次按下翻转；长按飞行</span><span>S</span><span>向下穿过平台</span><span>鼠标</span><span>瞄准，按住左键连续射击</span><span>鼠标右键</span><span>投掷手雷</span><span>1–0 / 滚轮</span><span>切换武器</span><span>无人机</span><span>再次射击，命令无人机俯冲</span></div>{room&&<p className="caption">打开菜单时，多人对局仍会继续。</p>}</>}
{panel==='embed'&&<><p>在你的网站上放置一个摧毁按钮。</p><div className={'badge-preview '+embedTheme}><button>摧毁这个网页</button></div><div className="two-buttons"><button className={embedTheme==='dark'?'active':''} onClick={()=>setEmbedTheme('dark')}>深色</button><button className={embedTheme==='light'?'active':''} onClick={()=>setEmbedTheme('light')}>浅色</button></div><textarea aria-label="嵌入代码" readOnly value={embed}/><button className="wide" onClick={()=>copy(embed,'嵌入代码已复制')}>复制代码</button><p className="caption">此网站为私密网站，访客需要先获得访问权限，才能使用嵌入按钮。</p><button onClick={()=>setPanel(ui.progress>0?'pause':'title')}>返回</button></>}
{panel==='lobby'&&<><div className="invite"><input aria-label="邀请链接" readOnly value={typeof location==='undefined'?'':location.origin+'/?room='+room?.code}/><button onClick={share}>复制邀请链接</button></div><label className="name-field">昵称<input aria-label="你的昵称" value={name} maxLength={20} onChange={e=>setName(e.target.value)}/></label><div className="player-list">{players.map(p=><p key={p.id}><i style={{background:p.color}}/>{p.name}<span>{p.id===room?.id?'你 · ':''}{p.id===roomInfo?.host?'房主':''}</span></p>)}</div>{host?<><form className="url-form" onSubmit={e=>{e.preventDefault();startMatch('url')}}><div className="url-input"><span>https://</span><input aria-label="对战网页地址" placeholder="wikipedia.org" value={url} onChange={e=>setUrl(e.target.value)}/></div><button disabled={!!busy}>⚡ 开始</button></form><div className="try-line"><span>试试</span><button disabled={!!busy} onClick={()=>startMatch('demo')}>演示网页</button><button disabled={!!busy} onClick={()=>startMatch('wiki')}>维基百科</button></div></>:<p>正在等待房主选择网页。</p>}<p className="caption">最多 4 人，率先击败对手 10 次获胜。受邀玩家需要获得此私密网站的访问权限。公开网页截图由 thum.io 提供。</p><button onClick={leave}>退出房间</button></>}
{panel==='complete'&&<><div className="complete-score">100%</div><h2>全部摧毁，一个像素也不留。</h2><div className="two-buttons"><button onClick={()=>setPanel('')}>继续破坏</button><button onClick={()=>setPanel('title')}>换个网页继续</button></div><button className="minor" onClick={()=>setPanel('embed')}>嵌入你的网站</button></>}
{panel==='over'&&<><h2>{players.find(p=>p.id===roomInfo?.winner)?.name||'玩家'} 获胜！</h2><p>{roomInfo?.winner===room?.id?'恭喜，你赢得了这场对局！':'本局失利，再来一局吧。'}</p><div className="player-list">{players.slice().sort((a,b)=>b.kills-a.kills).map(p=><p key={p.id}>{p.name}<b>{p.kills} 次击败</b></p>)}</div>{host?<div className="two-buttons"><button onClick={()=>startMatch(currentMap.current)}>再来一局</button><button onClick={()=>setPanel('lobby')}>更换网页</button></div>:<p>正在等待房主开始下一局。</p>}<button onClick={leave}>退出房间</button></>}
{panel==='about'&&<><h2>为破坏而生</h2><p>这是一个独立实现的可玩复刻版本，灵感来自 <a href="https://destroy.spritefusion.com/" target="_blank" rel="noreferrer">Sprite Fusion 的原版游戏</a>。角色动画、武器、特效和音效均为独立实现。</p><p className="caption">与原版的差异：角色美术和物理效果独立实现；公开网页使用 1200 × 1200 截图，并产生像素碎片，不包含原版对文字和布局的语义切割。内置页面支持文字碎片。多人模式通过定时同步房间状态实现。网页截图受 thum.io 服务状态和免费额度限制。</p><p className="caption">黄昏山景（Mountain at Dusk）：Luis Zuno / ansimuz，CC0。城市视差背景（City Parallax）：Gustavo Saraiva，CC0。<a href="https://opengameart.org/content/ocean-background" target="_blank" rel="noreferrer">海洋背景（Ocean Background），作者 KnoblePersona</a>, <a href="https://creativecommons.org/licenses/by/3.0/" target="_blank" rel="noreferrer">CC BY 3.0</a>（仅缩放，未修改内容）。Silkscreen 字体：SIL 开放字体许可证。维基百科示例：依据 CC BY-SA 改编。</p><a className="text-link" href="/ATTRIBUTION.txt" target="_blank">完整素材来源与许可证</a><button className="wide" onClick={()=>setPanel(currentMap.current&&ui.progress>0?'pause':'title')}>返回</button></>}
{busy&&panel!=='loading'&&<p className="status">{busy}</p>}{error&&<p className="error" role="alert">{error}</p>}
</div></DialogContent></Dialog>{notice&&<div className="toast" role="status">{notice}</div>}<output className="sr-only" aria-live="off">当前武器：{WEAPONS[ui.weapon]}。摧毁进度：{ui.progress}%。位置：{ui.x}, {ui.y}。粒子数：{ui.particles||0}.</output></main>}
function Weapon({index}:{index:number}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current!.getContext('2d')!;c.clearRect(0,0,92,45);drawWeapon(c,46,21,index,index===10?1.1:1);},[index]);return <canvas ref={ref} width={92} height={45} aria-hidden="true"/>;}
