import * as T from './vendor/three.module.min.js';
import {Simulation,V,arc,tangent,toward,clamp,UPGRADES} from './core.js';
import {createPlanet,BIOMES} from './worlds.js';
import {createPlayer,createEnemy} from './actors.js';
const $=s=>document.querySelector(s),sim=new Simulation(),canvas=$('#game'),overlay=$('#overlay');
const state={autoAim:true,muted:true,paused:false,mapMode:'new',keys:new Set(),fire:false,mouse:{x:0,y:0,active:false},touch:{x:0,y:0,fire:false,dash:false},transition:null,lastPhase:'title',upgradeChoices:[],time:0,loaded:0,maxLoaded:0,disposals:0,notice:0,started:false};
let renderer;try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(error){$('#loading').innerHTML='<div class="error-screen"><h2>无法开启 3D 图形</h2><p>此浏览器未提供 WebGL 2。请开启浏览器硬件加速，或使用支持 WebGL 2 的 Chrome / Edge / Safari。</p><button class="primary" onclick="location.reload()">重新尝试</button></div>';throw error;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.14;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene(),camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.1,800);scene.background=new T.Color('#071129');
scene.add(new T.HemisphereLight(0xafdfff,0x304b57,2.15));scene.add(new T.AmbientLight(0x8499c9,.65));const sun=new T.DirectionalLight(0xffeed3,3.2);sun.position.set(-25,45,22);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:25,bottom:-25,near:1,far:120});sun.shadow.bias=-.0005;sun.shadow.normalBias=.025;scene.add(sun);const rim=new T.DirectionalLight(0x73a7ff,1.8);rim.position.set(20,-10,-25);scene.add(rim);
const bg=new T.Group();scene.add(bg);const starGeom=new T.BufferGeometry(),starPos=[],starColors=[];for(let i=0;i<2200;i++){const n=V(Math.random()-.5,Math.random()-.5,Math.random()-.5).normalize().multiplyScalar(170+Math.random()*110);starPos.push(n.x,n.y,n.z);const c=new T.Color().setHSL(.53+Math.random()*.22,.25,.55+Math.random()*.45);starColors.push(c.r,c.g,c.b)}starGeom.setAttribute('position',new T.Float32BufferAttribute(starPos,3));starGeom.setAttribute('color',new T.Float32BufferAttribute(starColors,3));bg.add(new T.Points(starGeom,new T.PointsMaterial({size:.3,vertexColors:true,transparent:true,opacity:.8,sizeAttenuation:true,depthWrite:false})));
const sky=new T.Mesh(new T.SphereGeometry(340,32,24),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{time:{value:0}},vertexShader:'varying vec3 v;void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 v;uniform float time;void main(){vec3 n=normalize(v);float w=sin(n.x*4.+n.y*5.)*.45+sin(n.z*7.-n.y*3.)*.22;float b=pow(max(0.,1.-abs(n.y*.95+n.x*.2+w*.2)),10.);vec3 c=vec3(.014,.025,.070)+b*mix(vec3(.04,.05,.10),vec3(.065,.015,.10),n.x*.5+.5);gl_FragColor=vec4(c,1.);}'}));bg.add(sky);
let world=null,nextWorld=null,player=createPlayer(T);scene.add(player.group);const enemyViews=new Map(),bulletViews=new Map();const effects=[];const particleGeo=new T.IcosahedronGeometry(.09,0),particleMats=[new T.MeshBasicMaterial({color:0x93ffe0}),new T.MeshBasicMaterial({color:0xffcf7c}),new T.MeshBasicMaterial({color:0xff8871})];const bulletGeo=new T.SphereGeometry(.1,8,6),bulletMats=[new T.MeshBasicMaterial({color:0xb7ffe8}),new T.MeshBasicMaterial({color:0xff8260})];const ringGeo=new T.TorusGeometry(.7,.025,8,48),ringMat=new T.MeshBasicMaterial({color:0xa7ffcf,transparent:true,opacity:.8});const aimRing=new T.Mesh(ringGeo,ringMat);scene.add(aimRing);aimRing.visible=false;
function loadPlanet(i){const p=createPlanet(T,i,987+i*731);scene.add(p.group);state.loaded++;state.maxLoaded=Math.max(state.maxLoaded,state.loaded);if(state.loaded>2)throw Error('Planet budget exceeded');return p;}
function unloadPlanet(p){if(!p)return;scene.remove(p.group);p.dispose();state.loaded--;state.disposals++}
function clearActors(){for(const v of enemyViews.values()){scene.remove(v.group);v.dispose()}enemyViews.clear();for(const v of bulletViews.values())scene.remove(v);bulletViews.clear();for(const e of effects)scene.remove(e.mesh);effects.length=0;}
function replacePlanet(i){clearActors();unloadPlanet(nextWorld);nextWorld=null;unloadPlanet(world);world=loadPlanet(i);}
function pose(group,n,forward,height=0,p=world){group.position.copy(n).multiplyScalar(p.surfaceHeight(n)+height).add(p.group.position);const f=tangent(forward,n),r=new T.Vector3().crossVectors(n,f).normalize(),m=new T.Matrix4().makeBasis(r,n,f);group.quaternion.setFromRotationMatrix(m)}
let audio;function sound(type){if(state.muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);const now=audio.currentTime;const map={shoot:[540,250,.055,.024],hit:[180,90,.05,.02],kill:[420,850,.12,.035],hurt:[140,50,.2,.04],dash:[280,1100,.2,.025],clear:[440,900,.4,.045],wave:[220,440,.22,.026],land:[180,500,.25,.035]};const [a,b,d,v]=map[type]||map.hit;o.type=type==='shoot'?'triangle':'sine';o.frequency.setValueAtTime(a,now);o.frequency.exponentialRampToValueAtTime(b,now+d);g.gain.setValueAtTime(v,now);g.gain.exponentialRampToValueAtTime(.001,now+d);o.start();o.stop(now+d)}catch{}}
function burst(n,count=12,color=0){const origin=n.clone().multiplyScalar(world.surfaceHeight(n)+.7);for(let i=0;i<count&&effects.length<160;i++){const mesh=new T.Mesh(particleGeo,particleMats[color]);mesh.position.copy(origin);scene.add(mesh);effects.push({mesh,v:V(Math.random()-.5,Math.random()-.5,Math.random()-.5).multiplyScalar(4).addScaledVector(n,2),life:.45+Math.random()*.35,max:.8});}}
function notify(title,sub='',duration=2.4){$('#notification').innerHTML=`${title}${sub?`<small>${sub}</small>`:''}`;$('#notification').classList.add('show');state.notice=duration;}
function screen(html){overlay.innerHTML=`<section class="screen center-screen">${html}</section>`;$('#crosshair').classList.add('hidden')}
function setUI(){const active=sim.phase!=='title';$('#hud').classList.toggle('hidden',!active);$('#bottom').classList.toggle('hidden',!active||state.paused);$('#touch').classList.toggle('hidden',!active||state.paused||!matchMedia('(pointer:coarse)').matches||sim.phase!=='playing');$('#pause').style.visibility=active?'visible':'hidden';$('#biome-note').classList.toggle('hidden',!active||state.paused||sim.phase!=='playing');const b=BIOMES[sim.level];$('#planet-name').textContent=b.name;$('#planet-index').textContent=`PLANET 0${sim.level+1} / 05`;$('#biome-note').textContent=['花丛间游走，冲刺穿过敌群','水面可涉过，沿河岸寻找射击角度','冰面惯性较强，提前转向与刹停','树冠下穿行，保持距离逐个击破','熔岩会灼伤，红光预示喷发'][sim.level];}
function start(level=0){state.started=true;state.paused=false;state.keys.clear();state.fire=false;state.touch.fire=false;if(state.transition){state.transition=null;unloadPlanet(nextWorld);nextWorld=null}sim.start(level);replacePlanet(level);overlay.innerHTML='';cameraSnap();setUI();notify(BIOMES[level].name,'击退三波敌人，开启下一段航程',3);sound('land');}
function showUpgrade(){state.upgradeChoices=sim.choices();screen(`<span class="eyebrow">PLANET CLEARED</span><h2>让星光成为你的力量</h2><p class="subtitle">${BIOMES[sim.level].name}已清理 · 生命回复 18<br>选择一项强化，本次航程持续生效</p><div class="upgrade-grid">${state.upgradeChoices.map((u,i)=>`<button class="upgrade-card" data-upgrade="${u.id}"><span class="upgrade-icon">${u.icon}</span><small>${u.tag} · ${i+1}</small><h3>${u.name}</h3><p>${u.desc}</p></button>`).join('')}</div><p class="subtitle">已获得 ${sim.upgrades.length} 项强化</p>`);setUI()}
function selectUpgrade(id){if(!sim.applyUpgrade(id))return;sound('clear');if(sim.phase==='won')showEnd(true);else showMap('route')}
function showMap(mode='new'){state.mapMode=mode;if(mode==='new'&&sim.phase==='playing'){state.paused=true;state.keys.clear()}screen(`<span class="eyebrow">STAR CHART</span><h2>${mode==='route'?'下一颗星球，由你选择':'选择起始星球'}</h2><p class="subtitle">${mode==='route'?'强化与生命将随你继续航行':'从任意星球开启新航程，装备与生命重置'}</p><div class="map-grid">${BIOMES.map((b,i)=>`<button class="map-card" data-planet="${i}" ${mode==='route'&&sim.visited.includes(i)?'disabled':''}><div class="map-orb" style="--planet:${b.color||['#74c883','#57c7da','#9cddf6','#42a684','#ef8755'][i]}"><span>${['✿','≈','❄','♧','♨'][i]}</span></div><small>0${i+1}</small><h3>${b.name}</h3><p>${['草地 · 花海 · 柔和丘陵','河道 · 沙洲 · 水晶涟漪','冰川 · 雪脊 · 惯性滑行','森林 · 菌菇 · 浓密树冠','火山 · 熔岩 · 周期喷发'][i]}</p>${mode==='route'&&sim.visited.includes(i)?'<em>已清理</em>':''}</button>`).join('')}</div>${mode==='new'?'<button class="plain-button" id="map-back">返回</button>':''}`);setUI()}
function launch(i){if(sim.phase!=='route'||sim.visited.includes(i)||state.transition)return;clearActors();nextWorld=loadPlanet(i);nextWorld.group.position.set(48,-8,-65);state.transition={t:0,duration:4.6,index:i,from:sim.player.n.clone().multiplyScalar(world.surfaceHeight(sim.player.n)+.2),to:nextWorld.group.position.clone().add(V(0,14.1,0)),cameraFrom:camera.position.clone(),upFrom:camera.up.clone()};sim.phase='transition';overlay.innerHTML='';notify('点火，跃向下一颗星','目的地 · '+BIOMES[i].name,4.2);setUI()}
function pause(){if(sim.phase!=='playing')return;state.paused=!state.paused;state.keys.clear();state.fire=false;state.touch.fire=false;state.touch.dash=false;state.touch.x=state.touch.y=0;if(state.paused)screen(`<span class="eyebrow">TAKE A BREATH</span><h2>星空会等你</h2><p class="subtitle">${BIOMES[sim.level].name} · 第 ${Math.max(1,sim.wave)} 波 · ${sim.enemies.length} 个敌人</p><div class="hint-grid"><p><kbd>W A S D</kbd>沿球面移动</p><p><kbd>鼠标 / 空格</kbd>持续射击</p><p><kbd>Shift</kbd>无敌冲刺</p><p><kbd>Q / E</kbd>转动跟随视角</p></div><button class="primary" id="resume">继续冒险 <span>✦</span></button><button class="secondary" id="new-route">重新选择星球</button><p class="subtitle" style="margin-top:20px">${state.autoAim?'辅助瞄准已开启，优先锁定附近敌人':'辅助瞄准已关闭，用鼠标指向地面瞄准'}<br>剩余敌人的方向会显示在画面边缘</p>`);else overlay.innerHTML='';setUI()}
function showEnd(win){state.fire=false;screen(`<span class="eyebrow">${win?'CONSTELLATION COMPLETE':'SIGNAL LOST'}</span><h2>${win?'整片星空，为你闪耀':'旅途还没有结束'}</h2><p class="subtitle">${win?'五颗星球已全部净化，带着星光凯旋吧':'调整走位，试试不同的强化组合'}</p><div class="stats-summary"><span><b>${sim.visited.length}</b>清理星球</span><span><b>${sim.kills}</b>击破敌人</span><span><b>${sim.upgrades.length}</b>获得强化</span></div><button class="primary" id="restart">再来一场 <span>✦</span></button><button class="secondary" id="new-route">选择起始星球</button>`);setUI()}
let cameraReady=false;function cameraSnap(){cameraReady=false;updateCamera(1)}
function updateCamera(dt){const p=sim.player,n=p.n,f=sim.camForward;const target=n.clone().multiplyScalar(world.surfaceHeight(n)+.85).addScaledVector(f,2.5);const desired=n.clone().multiplyScalar(24).addScaledVector(f,-12.5);if(!cameraReady){camera.position.copy(desired);camera.up.copy(n);cameraReady=true}else{camera.position.lerp(desired,1-Math.exp(-dt*5.5));camera.up.lerp(n,1-Math.exp(-dt*8)).normalize()}camera.lookAt(target)}
const raycaster=new T.Raycaster(),mouseNdc=new T.Vector2();function mouseAim(){if(!state.mouse.active||state.autoAim)return null;mouseNdc.set(state.mouse.x/innerWidth*2-1,-state.mouse.y/innerHeight*2+1);raycaster.setFromCamera(mouseNdc,camera);const point=raycaster.ray.intersectSphere(new T.Sphere(V(),14.2),V());return point?toward(sim.player.n,point.normalize()):null}
function animateTransition(dt){const tr=state.transition;if(!tr)return;player.group.visible=true;tr.t+=dt;const p=clamp(tr.t/tr.duration,0,1),q=p*p*(3-2*p);const mid=tr.from.clone().lerp(tr.to,.5).add(V(0,20,0));const pos=tr.from.clone().multiplyScalar((1-q)**2).addScaledVector(mid,2*(1-q)*q).addScaledVector(tr.to,q*q);player.group.position.copy(pos);player.group.rotation.set(q*Math.PI*2,0,-q*Math.PI*.2);player.animate(dt,state.time,{moving:1,dashing:true,shooting:false,hurt:false});const desired=pos.clone().add(V(0,11,20));camera.position.lerp(desired,1-Math.exp(-dt*3));camera.up.lerp(V(0,1,0),1-Math.exp(-dt*3)).normalize();camera.lookAt(pos.clone().lerp(tr.to,.18));if(Math.random()<.7&&effects.length<160){const mesh=new T.Mesh(particleGeo,particleMats[Math.random()<.5?0:1]);mesh.position.copy(pos).add(V(Math.random()-.5,Math.random()-.5,Math.random()-.5));scene.add(mesh);effects.push({mesh,v:V(0,-1,2),life:.6,max:.6})}if(p>=1){unloadPlanet(world);world=nextWorld;nextWorld=null;world.group.position.set(0,0,0);state.transition=null;sim.beginLevel(tr.index);cameraSnap();setUI();notify(BIOMES[tr.index].name,'着陆成功 · 准备迎战',2.5);sound('land')}}
function renderActors(dt){const p=sim.player;pose(player.group,p.n,state.fire||state.touch.fire||state.keys.has('Space')?p.aim:p.forward,Math.sin(state.time*8)*.02);player.group.visible=!(p.invuln>0&&Math.floor(state.time*18)%2===0&&p.dash<=0);player.animate(dt,state.time,{moving:Math.min(1,p.velocity.length()/sim.stats.speed),shooting:p.shotCd>sim.stats.interval-.09,dashing:p.dash>0,hurt:p.invuln>.65});const ids=new Set(sim.enemies.map(e=>e.id));for(const [id,v]of enemyViews){if(!ids.has(id)){scene.remove(v.group);v.dispose();enemyViews.delete(id)}}for(const e of sim.enemies){let v=enemyViews.get(e.id);if(!v){v=createEnemy(T,e.type);scene.add(v.group);enemyViews.set(e.id,v)}pose(v.group,e.n,e.forward,.02);v.animate(dt,state.time,{moving:true,attacking:e.charge||e.cooldown<.2,hurt:e.flash>0});v.group.scale.setScalar(e.flash>0?1.09:1)}const bids=new Set(sim.bullets.map(b=>b.id));for(const[id,v]of bulletViews){if(!bids.has(id)){scene.remove(v);bulletViews.delete(id)}}for(const b of sim.bullets){let m=bulletViews.get(b.id);if(!m){m=new T.Mesh(bulletGeo,bulletMats[b.enemy?1:0]);scene.add(m);bulletViews.set(b.id,m)}pose(m,b.n,b.dir,.75);m.scale.set(b.enemy?2:1,b.enemy?2:1,b.enemy?2:3.3)}let nearest=null,d=100;for(const e of sim.enemies){let a=arc(p.n,e.n);if(a<d){d=a;nearest=e}}aimRing.visible=sim.phase==='playing'&&!!nearest&&d<12&&state.autoAim;if(aimRing.visible){aimRing.position.copy(nearest.n).multiplyScalar(world.surfaceHeight(nearest.n)+.15);aimRing.quaternion.setFromUnitVectors(V(0,0,1),nearest.n);aimRing.scale.setScalar(nearest.type==='brute'?1.4:1)}const indicator=$('#target-indicator');if(nearest&&sim.phase==='playing'&&!state.paused){const v=nearest.n.clone().multiplyScalar(15).project(camera);const behind=p.n.dot(nearest.n)<.25;const off=behind||Math.abs(v.x)>.82||Math.abs(v.y)>.65;if(off){const dir=toward(p.n,nearest.n),r=new T.Vector3().crossVectors(sim.camForward,p.n).normalize();const a=Math.atan2(dir.dot(r),dir.dot(sim.camForward));const x=innerWidth*.5+Math.sin(a)*innerWidth*.37,y=innerHeight*.51-Math.cos(a)*innerHeight*.29;indicator.style.left=x+'px';indicator.style.top=y+'px';indicator.innerHTML=`<div style="transform:rotate(${a}rad)">▲</div><span>敌人 · ${Math.round(d)}m</span>`;indicator.classList.remove('hidden')}else indicator.classList.add('hidden')}else indicator.classList.add('hidden');}
function hud(){const p=sim.player;$('#hp-text').textContent=`${Math.ceil(p.hp)} / ${sim.stats.maxHp}`;$('#hp-fill').style.width=`${p.hp/sim.stats.maxHp*100}%`;$('#hp-fill').style.background=p.hp/sim.stats.maxHp<.3?'linear-gradient(90deg,#ed657a,#ffa686)':'';$('#wave').textContent=`第 ${Math.max(1,sim.wave)} / 3 波`;$('#enemy-count').textContent=sim.enemies.length?`剩余 ${sim.enemies.length} 个敌人`:sim.phase==='playing'?'下一波即将抵达':'星球已清理';$('#dash-label').textContent=p.dashCd>0?`冲刺 ${p.dashCd.toFixed(1)}s`:'冲刺就绪';$('#dash-fill').style.width=`${(1-p.dashCd/sim.stats.dashCooldown)*100}%`;$('#visited').textContent=`${sim.visited.length} / 5`;$('#kills').textContent=sim.kills;}
function events(){while(sim.events.length){const e=sim.events.shift();if(e.type==='wave'){notify(`第 ${e.wave} 波`,e.wave===3?'最后一波 · 清理所有敌人':'敌群已抵达星球',1.8);sound('wave')}if(e.type==='hurt'){$('#damage').style.opacity='.8';setTimeout(()=>$('#damage').style.opacity='0',130);sound('hurt')}if(e.type==='kill'){burst(e.n,e.enemy==='brute'?20:12,1);sound('kill')}if(e.type==='hit'){burst(e.n,3,0);sound('hit')}if(e.type==='shoot'||e.type==='dash')sound(e.type);if(e.type==='clear'){notify('星球净化完成','选择你的下一项强化',2);sound('clear');showUpgrade()}if(e.type==='dead')showEnd(false)}}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.8))}window.addEventListener('resize',resize);
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&!e.repeat)pause();if(e.code==='KeyM'&&!e.repeat)toggleSound();if(sim.phase==='upgrade'&&/Digit[123]/.test(e.code))selectUpgrade(state.upgradeChoices[+e.code.slice(-1)-1]?.id);state.keys.add(e.code)});window.addEventListener('keyup',e=>state.keys.delete(e.code));window.addEventListener('blur',()=>{state.keys.clear();state.fire=false;state.touch.fire=false;if(sim.phase==='playing'&&!state.paused)pause()});canvas.addEventListener('pointerdown',e=>{if(e.button===0){state.fire=true;state.mouse.active=true;state.mouse.x=e.clientX;state.mouse.y=e.clientY;canvas.setPointerCapture(e.pointerId)}});window.addEventListener('pointerup',()=>{state.fire=false;state.touch.fire=false;state.touch.dash=false});canvas.addEventListener('pointermove',e=>{state.mouse.x=e.clientX;state.mouse.y=e.clientY;state.mouse.active=true;$('#crosshair').style.left=e.clientX+'px';$('#crosshair').style.top=e.clientY+'px'});canvas.addEventListener('contextmenu',e=>e.preventDefault());function toggleSound(){state.muted=!state.muted;$('#sound').style.color=state.muted?'#a1b0cf':'#80f5d6';$('#sound').setAttribute('aria-label',state.muted?'开启音效':'关闭音效');sound('land')}
$('#sound').onclick=toggleSound;$('#pause').onclick=pause;$('#home').onclick=e=>{e.preventDefault();pause()};$('#auto').onclick=()=>{state.autoAim=!state.autoAim;$('#auto').textContent=`辅助瞄准 · ${state.autoAim?'开':'关'}`;$('#auto').classList.toggle('active',state.autoAim);notify(state.autoAim?'辅助瞄准已开启':'手动瞄准','按住鼠标或空格射击',1.5)};
overlay.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.id==='start'||el.id==='restart')start(0);if(el.id==='choose-start'||el.id==='new-route')showMap('new');if(el.id==='resume')pause();if(el.dataset.upgrade)selectUpgrade(el.dataset.upgrade);if(el.dataset.planet!==undefined){const i=+el.dataset.planet;if(state.mapMode==='route')launch(i);else start(i)}if(el.id==='map-back'){if(sim.phase==='playing'){state.paused=false;pause()}else if(sim.phase==='dead'||sim.phase==='won'){showEnd(sim.phase==='won')}else location.reload()}});
let joyId=null,joyOrigin;$('#joystick').addEventListener('pointerdown',e=>{joyId=e.pointerId;$('#joystick').setPointerCapture(e.pointerId);const r=$('#joystick').getBoundingClientRect();joyOrigin={x:r.left+r.width/2,y:r.top+r.height/2};joyMove(e)});function joyMove(e){if(e.pointerId!==joyId)return;let x=(e.clientX-joyOrigin.x)/42,y=(e.clientY-joyOrigin.y)/42;const l=Math.hypot(x,y);if(l>1){x/=l;y/=l}state.touch.x=x;state.touch.y=-y;$('#stick').style.transform=`translate(${x*34}px,${y*34}px)`}$('#joystick').addEventListener('pointermove',joyMove);function joyEnd(){joyId=null;state.touch.x=state.touch.y=0;$('#stick').style.transform=''}$('#joystick').addEventListener('pointerup',joyEnd);$('#joystick').addEventListener('pointercancel',joyEnd);$('#touch-fire').addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();state.touch.fire=true;$('#touch-fire').setPointerCapture(e.pointerId)});$('#touch-fire').addEventListener('pointerup',()=>state.touch.fire=false);$('#touch-dash').addEventListener('pointerdown',e=>{e.preventDefault();state.touch.dash=true});
world=loadPlanet(0);pose(player.group,sim.player.n,sim.player.forward);setUI();$('#loading').classList.add('hidden');let prev=performance.now();function frame(now){const dt=Math.min((now-prev)/1000,.04);prev=now;state.time+=dt;if(!state.paused){world?.update(dt,state.time);nextWorld?.update(dt,state.time);if(state.transition)animateTransition(dt);else if(sim.phase==='title'){player.group.visible=true;player.animate(dt,state.time,{moving:false,shooting:false,dashing:false,hurt:false});pose(player.group,sim.player.n,V(-.6,0,1));const mobile=innerWidth<600;camera.position.set(mobile?8:26,27,31);camera.up.set(0,1,0);camera.lookAt(mobile?V(0,1,0):V(-10,1,0));world.group.rotation.y=Math.sin(state.time*.09)*.08;}else{world.group.rotation.y=0;if(sim.phase==='playing'){const k=state.keys;sim.update(dt,{x:(k.has('KeyD')||k.has('ArrowRight')?1:0)-(k.has('KeyA')||k.has('ArrowLeft')?1:0)+state.touch.x,y:(k.has('KeyW')||k.has('ArrowUp')?1:0)-(k.has('KeyS')||k.has('ArrowDown')?1:0)+state.touch.y,turn:(k.has('KeyE')?1:0)-(k.has('KeyQ')?1:0),fire:state.fire||state.touch.fire||k.has('Space'),dash:k.has('ShiftLeft')||k.has('ShiftRight')||state.touch.dash,autoAim:state.autoAim,aim:mouseAim()});const hazard=world.hazard?.(sim.player.n,state.time)||0;if(hazard>0&&sim.player.invuln<=0){sim.damage(8*hazard);notify('熔岩灼伤','冲刺离开橙红色熔岩区域',1.1)}events()}renderActors(dt);updateCamera(dt);hud()}}
 for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;e.mesh.position.addScaledVector(e.v,dt);e.v.multiplyScalar(1-dt*2);e.mesh.scale.setScalar(Math.max(0,e.life/e.max));if(e.life<=0){scene.remove(e.mesh);effects.splice(i,1)}}if(state.notice>0){state.notice-=dt;if(state.notice<=0)$('#notification').classList.remove('show')}$('#crosshair').classList.toggle('hidden',sim.phase!=='playing'||state.paused||state.autoAim||!state.mouse.active);renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);
const snapshot=()=>({...sim.snapshot(),paused:state.paused,loadedPlanets:state.loaded,maximumLoadedPlanets:state.maxLoaded,disposedPlanets:state.disposals,enemyModels:enemyViews.size,projectileModels:bulletViews.size,renderer:renderer.info.memory,autoAim:state.autoAim});window.starbloom={snapshot,start,pause,openMap:()=>showMap('new')};const context=document.modelContext;if(context?.registerTool){try{context.registerTool({name:'read_game_status',description:'Read the current visible run, combat and loaded-planet status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>snapshot()});context.registerTool({name:'start_planet_run',description:'Start a new run from a chosen planet, resetting the existing run. Planet is 1 through 5.',inputSchema:{type:'object',properties:{planet:{type:'integer',minimum:1,maximum:5}},required:['planet'],additionalProperties:false},execute:({planet})=>{if(!Number.isInteger(planet)||planet<1||planet>5)throw Error('planet must be 1–5');start(planet-1);return snapshot()}})}catch(e){console.warn('Game tools unavailable',e)}}
window.addEventListener('pagehide',()=>{clearActors();unloadPlanet(world);unloadPlanet(nextWorld);player.dispose();particleGeo.dispose();particleMats.forEach(m=>m.dispose());bulletGeo.dispose();bulletMats.forEach(m=>m.dispose());ringGeo.dispose();ringMat.dispose();starGeom.dispose();renderer.dispose()},{once:true});
