import {test} from 'node:test';
import assert from 'node:assert/strict';
import {WarehouseStore,seedState,validateState,totalStock,availableStock,SITES} from '../src/store.js';
import {arrivalMotion,departureMotion,sampleMotion,dockPose} from '../src/traffic.js';
const request={siteId:'WH-01',productId:'box',qty:2,direction:'outbound',customer:'Test Customer',destination:'Newark, NJ',carrier:0};
function idleStore(){const s=seedState();s.shipments=[];s.events=[];for(const site of Object.values(s.sites))for(const f of site.forks){f.status='idle';f.jobId=null;f.battery=80;}return new WarehouseStore(s);}
function until(store,predicate,limit=5000){for(let i=0;i<limit&&!predicate();i++)store.tick(.5);assert.ok(predicate(),'simulation did not reach expected state');}
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);

test('all five seeded sites and upgraded legacy saves are valid',()=>{const s=new WarehouseStore();assert.equal(SITES.length,5);assert.doesNotThrow(()=>validateState(s.state));assert.ok(s.state.sites['WH-01'].forks[0].motion);});
test('truck travels to a reserved dock before the forklift can load it',()=>{const s=idleStore(),sh=s.createShipment(request);const before=totalStock(s.state,'WH-01'),start={...sh.pose};s.dispatch(sh.id,1,'FL-01');assert.equal(sh.status,'arriving');assert.equal(s.state.sites['WH-01'].forks[0].status,'reserved');s.tick(5);assert.ok(distance(start,sh.pose)>2);assert.equal(sh.handled,0);assert.equal(totalStock(s.state,'WH-01'),before);until(s,()=>sh.status==='loading');assert.ok(distance(sh.pose,dockPose(SITES[0],1))<.001);assert.equal(s.state.sites['WH-01'].forks[0].status,'working');assert.doesNotThrow(()=>validateState(s.state));});
test('outbound inventory changes only after actual forklift delivery; truck exits before transit',()=>{const s=idleStore(),before=totalStock(s.state,'WH-01'),available=availableStock(s.state,'WH-01','box');const sh=s.createShipment(request);assert.equal(availableStock(s.state,'WH-01','box'),available-2);s.dispatch(sh.id,1,'FL-01');until(s,()=>sh.status==='departing');assert.equal(sh.handled,2);assert.equal(totalStock(s.state,'WH-01'),before-2);assert.equal(sh.dock,1,'dock is reserved until the truck leaves');assert.equal(sh.forkId,null);const start={...sh.pose};s.tick(1);assert.ok(distance(start,sh.pose)>0);until(s,()=>sh.status==='transit');assert.equal(sh.dock,null);assert.ok(sh.pose.x>SITES[0].w/2+16);until(s,()=>sh.status==='delivered');assert.equal(totalStock(s.state,'WH-01'),before-2);assert.doesNotThrow(()=>validateState(s.state));});
test('inbound adds stock exactly once and releases capacity reservation when unloading ends',()=>{const s=idleStore(),before=totalStock(s.state,'WH-01');const sh=s.createShipment({...request,direction:'inbound'});s.dispatch(sh.id,1,'FL-01');until(s,()=>sh.status==='departing');assert.equal(totalStock(s.state,'WH-01'),before+2);assert.doesNotThrow(()=>validateState(s.state));until(s,()=>sh.status==='delivered');for(let i=0;i<20;i++)s.tick(5);assert.equal(totalStock(s.state,'WH-01'),before+2);});
test('forklift travels across the yard, carries a pallet, and returns without teleporting',()=>{const s=idleStore(),sh=s.createShipment({...request,qty:1});s.dispatch(sh.id,1,'FL-01');const f=s.state.sites['WH-01'].forks[0],home={...f.pose};until(s,()=>f.carrying);assert.ok(distance(home,f.pose)>15);until(s,()=>f.status==='returning');assert.equal(f.carrying,false);const start={...f.pose};s.tick(.5);assert.ok(distance(start,f.pose)<1.1);until(s,()=>f.status==='idle');assert.ok(distance(home,f.pose)<.001);});
test('shared truck lane serializes arrivals and resumes waiting vehicles',()=>{const s=idleStore(),a=s.createShipment(request),b=s.createShipment(request);s.dispatch(a.id,1,'FL-01');s.dispatch(b.id,2,'FL-02');s.tick(1);assert.ok(a.motion.waiting!==b.motion.waiting);assert.equal([a,b].filter(sh=>sh.motion.speed>0).length,1);until(s,()=>a.status==='delivered'&&b.status==='delivered');assert.doesNotThrow(()=>validateState(s.state));});
test('reservation and cancellation release stock and resource ownership',()=>{const s=idleStore(),available=availableStock(s.state,'WH-01','box'),sh=s.createShipment({...request,qty:available});assert.throws(()=>s.createShipment(request),/库存不足/);s.dispatch(sh.id,1,'FL-01');s.cancelShipment(sh.id);s.tick(.5);assert.equal(availableStock(s.state,'WH-01','box'),available);assert.equal(s.state.sites['WH-01'].forks[0].jobId,null);assert.equal(sh.dock,null);assert.doesNotThrow(()=>validateState(s.state));});
test('reserved docks, working forklifts and charging forklifts cannot be double-booked',()=>{const s=idleStore(),a=s.createShipment(request),b=s.createShipment(request);s.dispatch(a.id,1,'FL-01');assert.throws(()=>s.dispatch(b.id,1,'FL-02'),/月台/);assert.throws(()=>s.dispatch(b.id,2,'FL-01'),/叉车/);s.chargeFork('WH-01','FL-02');assert.throws(()=>s.dispatch(b.id,2,'FL-02'),/叉车/);});
test('incoming capacity cannot be consumed by another arrival or replenishment',()=>{const s=idleStore(),space=1800-totalStock(s.state,'WH-01');s.createShipment({...request,qty:space,direction:'inbound'});assert.throws(()=>s.createShipment({...request,direction:'inbound'}),/容量/);assert.throws(()=>s.replenish('WH-01','box',1),/容量/);});
test('pause freezes physical position, clock and work; speed affects motion',()=>{const s=idleStore(),sh=s.createShipment(request);s.dispatch(sh.id);s.setSimulation({paused:true});const before=JSON.stringify(s.state);s.tick(1);assert.equal(JSON.stringify(s.state),before);s.setSimulation({paused:false,speed:15});const clock=s.state.clock;s.tick(1);assert.ok(Math.abs(s.state.clock-clock-15)<1e-6);assert.ok(sh.motion.distance>15);});
test('mid-turn export/import retains exact vehicle position and future route',()=>{const s=idleStore(),sh=s.createShipment(request);s.dispatch(sh.id);s.tick(5);const data=JSON.parse(JSON.stringify(s.state)),loaded=new WarehouseStore(data);assert.deepEqual(loaded.state.shipments[0].pose,sh.pose);s.tick(5);loaded.tick(5);assert.deepEqual(loaded.state.shipments[0].pose,sh.pose);const invalid=structuredClone(data);invalid.shipments[0].motion.points[0].x=null;const before=JSON.stringify(loaded.state);assert.throws(()=>loaded.restore(invalid));assert.equal(JSON.stringify(loaded.state),before);});
test('invalid quantity does not create an order',()=>{const s=idleStore();for(const qty of [0,-1,NaN,1.5,Infinity])assert.throws(()=>s.createShipment({...request,qty}));assert.equal(s.state.shipments.length,0);});
test('all five sites finish without deadlock and conserve pallet inventory',()=>{const s=new WarehouseStore();const before=SITES.reduce((n,c)=>n+totalStock(s.state,c.id),0),incoming=s.state.shipments.filter(s=>s.status==='unloading').reduce((n,s)=>n+s.qty,0),outgoing=s.state.shipments.filter(s=>s.status==='loading').reduce((n,s)=>n+s.qty,0);s.setSimulation({speed:15});until(s,()=>s.state.shipments.every(s=>s.status==='delivered'));assert.equal(SITES.reduce((n,c)=>n+totalStock(s.state,c.id),0),before+incoming-outgoing);assert.doesNotThrow(()=>validateState(s.state));});
test('every road route remains outside the building and reaches the correct dock',()=>{for(const cfg of SITES)for(let dock=1;dock<=cfg.docks;dock++){const route=arrivalMotion(cfg,dock);for(let d=0;d<=route.length;d+=.1){const p=sampleMotion(route,d);assert.ok(!(Math.abs(p.x)<cfg.w/2+1&&Math.abs(p.z)<cfg.d/2+1.5));}assert.ok(distance(sampleMotion(route,route.length),dockPose(cfg,dock))<.001);const reverse=sampleMotion(route,route.length-1);assert.equal(reverse.reverse,true);assert.ok(Math.abs(Math.sin(reverse.yaw))<.001);const exit=departureMotion(cfg,dock);assert.ok(distance(sampleMotion(exit,0),dockPose(cfg,dock))<.001);assert.ok(sampleMotion(exit,exit.length).x>cfg.w/2+16);}});
