import {test} from 'node:test';
import assert from 'node:assert/strict';
import {WarehouseStore,seedState,SITES,totalStock,inboundReserved,validateState,operationSite} from '../src/store.js';
import {toWorld,transferMotion,departureMotion,sampleMotion,waitingPose,roadZ,ROAD_WEST,ROAD_EAST} from '../src/traffic.js';
function clean(){const data=seedState();data.shipments=[];data.events=[];for(const site of Object.values(data.sites))for(const f of site.forks){f.status='idle';f.jobId=null;f.battery=90;}return new WarehouseStore(data);}
function until(s,p,limit=4000){for(let i=0;i<limit&&!p();i++)s.tick(.5);assert.ok(p(),'expected transfer stage was not reached');}
const globalPose=sh=>sh.poseSpace==='world'?sh.pose:toWorld(SITES.find(c=>c.id===operationSite(sh)),sh.pose);

test('all directed warehouse routes connect exact endpoints and stay on public roads',()=>{
 for(const a of SITES)for(const b of SITES){if(a===b)continue;const exit=departureMotion(a,1),start=toWorld(a,sampleMotion(exit,exit.length)),route=transferMotion(a,b,start);assert.deepEqual(route.points[0],start);const last=sampleMotion(route,route.length),end=toWorld(b,waitingPose(b));assert.ok(Math.hypot(last.x-end.x,last.z-end.z)<1e-6);
 for(let d=0;d<route.length;d+=.25){const p=sampleMotion(route,d);assert.ok([-20,45].some(z=>p.z>=z-2&&p.z<=z+5)||Math.abs(p.x-ROAD_EAST)<3.5||Math.abs(p.x-ROAD_WEST)<3.5,'truck left road');for(const c of SITES){const center=toWorld(c,{x:0,z:0});assert.ok(!(Math.abs(p.x-center.x)<c.w/2+1&&Math.abs(p.z-center.z)<c.d/2+1),'route entered a building');}}
 }
});
test('one truck physically transports stock between every compatible pair without jumps or duplication',()=>{
 for(const source of SITES)for(const target of SITES){if(source===target)continue;const product=source.products.find(id=>target.products.includes(id));if(!product)continue;const s=clean(),a=totalStock(s.state,source.id),b=totalStock(s.state,target.id),sh=s.createTransfer(source.id,target.id,product,2);let previous=globalPose(sh),roadSeen=false,unloadSeen=false;
 for(let i=0;i<6000&&sh.status!=='delivered';i++){s.tick(.25);const p=globalPose(sh);assert.ok(Math.hypot(p.x-previous.x,p.z-previous.z)<1.6,'truck teleported at a warehouse boundary');previous=p;if(sh.status==='transit'){roadSeen=true;assert.equal(totalStock(s.state,source.id),a-2);assert.equal(totalStock(s.state,target.id),b);assert.equal(inboundReserved(s.state,target.id),2);}if(sh.status==='unloading')unloadSeen=true;validateState(s.state);}
 assert.equal(sh.status,'delivered');assert.ok(roadSeen&&unloadSeen);assert.equal(totalStock(s.state,source.id),a-2);assert.equal(totalStock(s.state,target.id),b+2);assert.equal(inboundReserved(s.state,target.id),0);s.tick(5);assert.equal(totalStock(s.state,target.id),b+2);
 }
});
test('receiving capacity is reserved before dispatch and cancellation releases both sides',()=>{const s=clean(),source=SITES[0],target=SITES[1],item=s.state.sites[target.id].inventory[0];item.qty+=target.capacity-totalStock(s.state,target.id)-2;const sh=s.createTransfer(source.id,target.id,'box',2);assert.equal(inboundReserved(s.state,target.id),2);assert.throws(()=>s.createTransfer(source.id,target.id,'box',1),/容量/);assert.throws(()=>s.replenish(target.id,'box',1),/容量/);s.cancelShipment(sh.id);assert.equal(inboundReserved(s.state,target.id),0);assert.doesNotThrow(()=>validateState(s.state));});
test('truck waits at receiving gate if forklifts are unavailable and later unloads',()=>{const s=clean();for(const f of s.state.sites['WH-02'].forks){f.status='charging';f.battery=0;}const sh=s.createTransfer('WH-01','WH-02','box',1);until(s,()=>sh.status==='waiting');const p={...sh.pose},stock=totalStock(s.state,'WH-02');s.tick(5);assert.equal(sh.status,'waiting');assert.deepEqual(sh.pose,p);assert.equal(totalStock(s.state,'WH-02'),stock);const f=s.state.sites['WH-02'].forks[0];f.status='idle';f.battery=80;until(s,()=>sh.status==='delivered');assert.equal(totalStock(s.state,'WH-02'),stock+1);});
test('cross-map movement pauses and resumes from an exported save with the same destination',()=>{const s=clean(),sh=s.createTransfer('WH-03','WH-04','water',1);until(s,()=>sh.status==='transit');s.tick(4);const saved=structuredClone(s.state),loaded=new WarehouseStore(saved);s.setSimulation({paused:true});const p={...sh.pose};s.tick(3);assert.deepEqual(sh.pose,p);s.setSimulation({paused:false});s.tick(3);loaded.tick(3);assert.deepEqual(loaded.state.shipments[0].pose,sh.pose);until(loaded,()=>loaded.state.shipments[0].status==='delivered');assert.doesNotThrow(()=>validateState(loaded.state));});
test('automatic logistics keeps at most four transfers active and drains after being turned off',()=>{const s=clean();s.setNetwork(true);s.setSimulation({speed:15});for(let i=0;i<150;i++){s.tick(1);assert.ok(s.state.shipments.filter(sh=>!['delivered','cancelled'].includes(sh.status)).length<=4);validateState(s.state);}assert.ok(s.state.shipments.filter(sh=>sh.status==='delivered').length>=5);s.setNetwork(false);until(s,()=>s.state.shipments.every(sh=>sh.status==='delivered'));});
