// App integration test with a deliberately stubbed renderer/DOM. This is not a browser or visual test.
import {FakeAudioContext} from './fake-audio-context.mjs';
const audioContexts=[];class TestAudioContext extends FakeAudioContext{constructor(){super();audioContexts.push(this)}}
import fs from 'node:fs';import vm from 'node:vm';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath,pathToFileURL} from 'node:url';import * as Real from '../vendor/three.module.min.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
class Element{constructor(){this.style={};this.innerHTML='';this.textContent='';this.listeners={};this.classList={add(){},remove(){},toggle(){}}}addEventListener(k,v){this.listeners[k]=v}setAttribute(){}setPointerCapture(){}getBoundingClientRect(){return {left:0,top:0,width:115,height:115}}}
const elems=new Map(),tools=[];const doc={hidden:false,addEventListener(){},querySelector(s){if(!elems.has(s))elems.set(s,new Element());return elems.get(s)},modelContext:{registerTool(t){tools.push(t)}}};class Renderer{constructor(){this.shadowMap={};this.info={memory:{geometries:0,textures:0}}}setPixelRatio(){}setSize(){}render(){}dispose(){}}
const win={addEventListener(){}};const ctx=vm.createContext({AudioContext:TestAudioContext,console,document:doc,window:win,innerWidth:1440,innerHeight:900,devicePixelRatio:1,matchMedia:()=>({matches:false}),performance:{now:()=>0},requestAnimationFrame(){},setTimeout(){},location:{reload(){}},Math,Set,Map});
const cache=new Map();async function get(url){if(cache.has(url))return cache.get(url);let m;if(url.endsWith('/vendor/three.module.min.js')){const values={...Real,WebGLRenderer:Renderer};m=new vm.SyntheticModule(Object.keys(values),function(){for(const[k,v]of Object.entries(values))this.setExport(k,v)},{context:ctx,identifier:url});}else{let src=fs.readFileSync(fileURLToPath(url),'utf8');if(url.endsWith('/game.js'))src+='\nexport {sim,state,loadPlanet,unloadPlanet,world,nextWorld,start,launch,animateTransition,selectUpgrade,events,renderActors,hud,frame,pause,showMap,screen,snapshot,audio,unlockAudio};';m=new vm.SourceTextModule(src,{context:ctx,identifier:url});}cache.set(url,m);await m.link((specifier,ref)=>get(new URL(specifier,ref.identifier).href));return m;}
const app=await get(pathToFileURL(root+'/game.js').href);await app.evaluate();const a=app.namespace;assert.equal(a.snapshot().loadedPlanets,1);a.start(0);await a.unlockAudio();assert.equal(a.audio.snapshot().unlocked,true);assert.equal(a.audio.muted,false);assert.equal(a.snapshot().loadedPlanets,1);a.renderActors(1/60);a.hud();assert.equal(tools.length,2);assert.throws(()=>tools[1].execute({planet:8}));assert.equal(tools[1].execute({planet:1}).level,0);
let elapsed=0,states=[];for(let level=0;level<5;level++){const s=a.sim;for(let k=0;k<30000&&s.phase==='playing';k++){const p=s.player,cf=s.camForward,r=new Real.Vector3().crossVectors(cf,p.n).normalize();let nearest=null,d=Infinity;for(const e of s.enemies){const q=Math.acos(Math.max(-1,Math.min(1,e.n.dot(p.n))))*14;if(q<d){d=q;nearest=e}}let move=new Real.Vector3();if(nearest){const toward=nearest.n.clone().addScaledVector(p.n,-nearest.n.dot(p.n)).normalize();if(d>6)move.copy(toward);else if(d<4)move.copy(toward).negate();else move.crossVectors(toward,p.n).normalize()};audioContexts[0].advance(1/60);s.update(1/60,{x:move.dot(r),y:move.dot(cf),fire:true,dash:p.hp<35&&d<3});a.events();if(k%30===0){a.renderActors(1/60);a.hud()}elapsed+=1/60;}assert.equal(s.phase,'upgrade',`level ${level} should clear through actual combat`);const offered=a.state.upgradeChoices;const pref=['rapid','power','split','health','leech','dash','pierce','speed'];const chosen=pref.map(id=>offered.find(x=>x.id===id)).find(Boolean);a.selectUpgrade(chosen.id);states.push(a.snapshot());if(level<4){assert.equal(s.phase,'route');a.launch(level+1);assert.equal(a.snapshot().loadedPlanets,2);for(let j=0;j<300&&a.state.transition;j++)a.animateTransition(1/60);assert.equal(s.phase,'playing');assert.equal(a.snapshot().loadedPlanets,1);assert.equal(a.snapshot().enemyModels,0);assert.equal(a.snapshot().projectileModels,0);}}
assert.equal(a.sim.phase,'won');const audioResult=a.audio.snapshot();assert.ok(audioResult.played>1000,'Actual game events should produce distinct sound plays');assert.ok(audioResult.maxVoicesSeen<=24);assert.equal(audioResult.ambientLoops,0);assert.equal(a.snapshot().maximumLoadedPlanets,2);a.start(4);assert.equal(a.snapshot().loadedPlanets,1);assert.equal(a.sim.visited.length,0);assert.equal(a.sim.player.hp,100);a.pause();assert.equal(a.state.paused,true);a.pause();assert.equal(a.state.paused,false);for(let i=0;i<5;i++){a.start(i);a.renderActors(.016);assert.equal(a.snapshot().loadedPlanets,1)}
console.log(JSON.stringify({passed:true,kind:'Integration only: renderer and DOM are stubs, not browser gameplay',kills:states.at(-1).kills,elapsedSimulationSeconds:Math.round(elapsed),audioEventsPlayed:audioResult.played,maximumAudioVoices:audioResult.maxVoicesSeen,maximumLoadedPlanets:a.snapshot().maximumLoadedPlanets,disposedPlanets:a.snapshot().disposedPlanets,checks:['initialization','all 5 real combat clears','offered upgrades','4 timed launches','max 2 transition / 1 play','enemy/projectile disposal','starmap all planets','death/reset covered by pure tests','pause/resume','WebMCP valid and invalid inputs']},null,2));
