const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const output=path.resolve(__dirname,'../qa');fs.mkdirSync(output,{recursive:true});
const baseURL=process.env.CUBE_TEST_URL||'http://127.0.0.1:5186/';
(async()=>{
  const browser=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),headless:true,args:['--enable-unsafe-swiftshader','--disable-background-timer-throttling']});
  const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const idle=async()=>{await page.waitForFunction(()=>window.cubeAtelier&&!window.cubeAtelier.busy);};
  const waitSolution=async()=>{await page.waitForFunction(()=>window.cubeAtelier.solution?.length>0,null,{timeout:30000});};
  const clickMove=async(move)=>{await page.locator(`[data-move="${move}"]`).click();await idle();};
  const verifyNet=async()=>{
    const result=await page.evaluate(()=>{
      const faces=['U','R','F','D','L','B'],colors={U:'rgb(247, 243, 232)',R:'rgb(227, 106, 84)',F:'rgb(68, 143, 119)',D:'rgb(238, 201, 91)',L:'rgb(237, 164, 88)',B:'rgb(100, 148, 193)'};
      const net=faces.map(f=>Array.from(document.querySelectorAll(`#cube-net [data-face=${f}] .net-tile`)).map(t=>faces.find(c=>colors[c]===t.style.backgroundColor)).join('')).join('');
      return {net,state:window.cubeAtelier.state,rendered:window.cubeAtelier.renderedState,stickers:window.cubeAtelier.stickerCount};
    });assert.equal(result.net,result.state);assert.equal(result.rendered,result.state);assert.equal(result.stickers,54);
  };
  await page.goto(baseURL,{waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>window.cubeAtelier?.webgl);
  await page.waitForFunction(()=>window.cubeAtelier.solverReady,null,{timeout:30000});
  assert.equal(await page.evaluate(()=>window.cubeAtelier.workerFailed),false);
  await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
  const original=await page.evaluate(()=>window.cubeAtelier.state);
  await clickMove('R');assert.notEqual(await page.evaluate(()=>window.cubeAtelier.state),original);await verifyNet();
  await page.keyboard.press('Shift+r');await idle();assert.equal(await page.evaluate(()=>window.cubeAtelier.state),original);
  await page.locator('#undo').click();await idle();assert.equal(await page.evaluate(()=>window.cubeAtelier.solved),false);
  await page.locator('#redo').click();await idle();assert.equal(await page.evaluate(()=>window.cubeAtelier.solved),true);
  await page.locator('#scramble').click();await idle();assert.equal(await page.evaluate(()=>window.cubeAtelier.solved),false);await verifyNet();
  await page.locator('#mode-guide').click();await waitSolution();
  const wrong=await page.evaluate(()=>['U','R','F','D','L','B'].find(f=>f!==window.cubeAtelier.solution[0][0]));
  await clickMove(wrong);await waitSolution();await verifyNet();
  await page.locator('[data-action=next]').click();await idle();assert.equal(await page.evaluate(()=>window.cubeAtelier.solutionIndex),1);
  await page.waitForTimeout(250);await page.screenshot({path:path.join(output,'guidance.png'),fullPage:true});
  await page.locator('[data-action=play]').click();await page.waitForTimeout(600);
  await page.locator('[data-action=play]').click();await idle();
  if(!(await page.evaluate(()=>window.cubeAtelier.solved))){await page.locator('[data-action=play]').click();await page.waitForFunction(()=>window.cubeAtelier.solved&&!window.cubeAtelier.busy,null,{timeout:30000});}
  assert.equal(await page.evaluate(()=>window.cubeAtelier.solved),true);await verifyNet();
  await page.locator('#mode-free').click();await page.locator('#scramble').click();await idle();
  await clickMove('F');const saved=await page.evaluate(()=>({state:window.cubeAtelier.state,moves:window.cubeAtelier.moves}));
  await page.locator('#nav-formulas').click();await page.locator('[data-formula="4"]').click();
  assert.equal(await page.evaluate(()=>window.cubeAtelier.demo.total),8);
  await page.locator('[data-action=next]').click();await idle();
  await page.locator('[data-action=demo-exit]').click();await idle();
  assert.deepEqual(await page.evaluate(()=>({state:window.cubeAtelier.state,moves:window.cubeAtelier.moves})),saved);
  await page.locator('#nav-formulas').click();await page.locator('[data-formula="0"]').click();await page.locator('[data-action=play]').click();
  await page.waitForFunction(()=>window.cubeAtelier.demo?.index===4&&!window.cubeAtelier.busy);
  assert.equal(await page.evaluate(()=>window.cubeAtelier.solved),true);
  await page.locator('[data-action=demo-exit]').click();await idle();assert.equal(await page.evaluate(()=>window.cubeAtelier.state),saved.state);
  await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.cubeAtelier?.webgl);assert.equal(await page.evaluate(()=>window.cubeAtelier.state),saved.state);await verifyNet();
  await page.locator('[data-view=net]').click();assert.equal(await page.evaluate(()=>window.cubeAtelier.view),'net');
  await page.locator('#large-net [data-face=B]').click();await clickMove("B'");await verifyNet();
  await page.screenshot({path:path.join(output,'unfolded.png'),fullPage:true});
  await page.locator('#nav-help').click();assert.equal(await page.locator('#help-dialog').isVisible(),true);await page.keyboard.press('Escape');
  assert.equal(await page.locator('#help-dialog').isVisible(),false);
  const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
  mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(baseURL,{waitUntil:'domcontentloaded'});await mobile.waitForFunction(()=>window.cubeAtelier?.webgl);
  assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Mobile must not overflow');
  await mobile.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
  await mobile.locator('[data-move=U]').click();await mobile.waitForFunction(()=>!window.cubeAtelier.busy);assert.equal(await mobile.evaluate(()=>window.cubeAtelier.solved),false);
  await mobile.locator('#nav-formulas').click();await mobile.screenshot({path:path.join(output,'mobile-library.png'),fullPage:true});
  assert.deepEqual(errors,[]);
  const report={passed:true,checks:['3D WebGL rendering','54 stickers','facelet and unfolded-view synchronization','manual moves and keyboard inverses','undo and redo','random scramble','solver worker','wrong-move replanning','step guidance','play and pause','full solve','formula demo and snapshot restoration','persistence','expanded net view','help dialog','mobile layout and controls'],errors};
  fs.writeFileSync(path.join(output,'ui-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
