import {World} from './scene.js';
import {STATIONS,GOODS,CONTRACTS,newGame,railPath,planTrack,buildTrack,removeTrack,setRoute,buyTrain,upgradeTrain,repairTrain,claimContract,tick,restore,key} from './model.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],fmt=n=>Math.floor(n).toLocaleString('zh-CN');
const SAVE='canyon-railway-zh-v1';let saved=null;try{saved=restore(localStorage.getItem(SAVE));}catch{}
let state=saved||newGame(),mode='inspect',anchor=null,plan=null,selected={type:'train',id:state.trains[0].id},speed=1,paused=false,sound=false,audio=null,modalType='',routeTrain=null,shopRoute=false,world;
const station=id=>STATIONS.find(s=>s.id===id),train=id=>state.trains.find(t=>t.id===id),selectedTrain=()=>train(selected.id)||state.trains[0];

function toast(message,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('#toast-area').append(el);setTimeout(()=>{el.classList.add('fade');setTimeout(()=>el.remove(),350);},3700);}
function chime(kind='tap'){
  if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const notes=kind==='income'?[523,659,784]:kind==='build'?[220,330,440]:kind==='whistle'?[587,784]:[440];notes.forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type=kind==='build'?'triangle':'sine';o.frequency.value=f;g.gain.setValueAtTime(0,audio.currentTime+i*.07);g.gain.linearRampToValueAtTime(.045,audio.currentTime+i*.07+.015);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+i*.07+.24);o.connect(g);g.connect(audio.destination);o.start(audio.currentTime+i*.07);o.stop(audio.currentTime+i*.07+.28);});}catch{}
}
function save(manual=false){try{localStorage.setItem(SAVE,JSON.stringify(state));$('#save-status').textContent='已保存 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});if(manual)toast('铁路日志已保存，下次打开可继续经营。');}catch{if(manual)toast('浏览器无法保存进度，请检查存储空间。','error');}}
function result(r,success){if(r.error){toast(r.error,'error');return false;}if(success)toast(success,'earned');save();render();return true;}
function setMode(next){mode=next;anchor=null;plan=null;$('#build-confirm').hidden=true;world.showPlan(null,state);world.setBuildMode(mode);$$('[data-tool]').forEach(b=>{b.classList.toggle('active',b.dataset.tool===mode);b.setAttribute('aria-pressed',String(b.dataset.tool===mode));});$('#tool-hint').textContent={inspect:'点击车站或列车，查看运营详情。',rail:'先点起点车站或铁轨，再点终点，预览后确认施工。',bridge:'连接河流两岸。陆地 $60 / 格，水上 $240 / 格。',remove:'点击闲置铁轨拆除，返还一半造价。运营路线会受到保护。'}[mode];}
function pick(p){
  if(mode==='inspect'){
    if(p.train){selected={type:'train',id:p.train};renderDetail();if(innerWidth<=760)panel('trains');chime();return;}
    if(p.station){selected={type:'station',id:p.station.id};renderDetail();world.stationLabels.forEach(({s,el})=>el.classList.toggle('selected',s.id===p.station.id));if(innerWidth<=760)stationModal(p.station);chime();}return;
  }
  if(!Number.isFinite(p.x)||!Number.isFinite(p.z))return;
  if(mode==='remove'){const r=removeTrack(state,p.x,p.z);if(result(r,r.ok?`已拆除轨道，返还 $${r.refund}`:''))world.syncRails(state);return;}
  if(!anchor||plan){anchor={x:p.x,z:p.z};plan=null;world.showPlan(null,state);$('#build-confirm').hidden=true;if(!state.tracks[key(p.x,p.z)]&&!p.station){anchor=null;toast('从现有铁轨或带名称的车站开始铺设。','error');return;}$('#tool-hint').textContent=`起点已选${p.station?`：${p.station.name}`:''}。现在点击终点车站或空地。`;toast('已选起点，点击终点预览路线。');chime();return;}
  const proposed=planTrack(state,anchor,p,mode==='bridge');if(proposed.error){toast(proposed.error,'error');return;}if(!proposed.fresh.length){toast('这段路线已有铁轨，请选择新的终点。');return;}plan=proposed;world.showPlan(plan,state);$('#build-confirm').hidden=false;$('#build-cost').textContent=`$ ${fmt(plan.price)}`;$('#build-length').textContent=`${plan.fresh.length} 格新轨道${plan.bridges?` · ${plan.bridges} 格铁路桥`:''}`;$('#confirm-build').disabled=state.money<plan.price;$('#tool-hint').textContent='绿色轨道为待建路线，确认后即可通车。';
}
function confirmBuild(){const r=buildTrack(state,plan);if(!result(r))return;const length=plan.fresh.length;world.syncRails(state);setMode(mode);toast(`${length} 格铁路铺设完成。去列车面板安排运输吧！`,'earned');chime('build');render();}

const trainArt=(color='#5087a8')=>`<svg viewBox="0 0 220 93" role="img" aria-label="蒸汽机车插图"><ellipse cx="111" cy="80" rx="94" ry="6" fill="#d6c6a0" opacity=".5"/><path d="M17 72h182M17 76h182" stroke="#b5a383" stroke-width="2"/><path d="M31 63h36V42H31z" fill="#756850"/><path d="M30 40h38v5H30zM38 39l3-8 13-2 9 10" fill="#4f5850"/><path d="M72 64h116V54H72z" fill="#575c51"/><path d="M79 25h40v36H79z" fill="${color}"/><path d="M74 20h49v7H74z" fill="#3e6177"/><path d="M85 30h25v18H85z" fill="#f2dc9f"/><path d="M98 29v20" stroke="#557584" stroke-width="3"/><path d="M119 38h49a13 13 0 0 1 0 26h-49z" fill="${color}"/><path d="M132 39v24m22-24v24" stroke="#ccae62" stroke-width="4"/><path d="M157 21h13l-2 18h-8zM153 17h21v7h-21z" fill="#48555b"/><path d="M138 30h10v9h-10z" fill="#d4b365"/><path d="M179 62l15 9h-18z" fill="#aa8652"/><path d="M163 14c-6-3-10-8-5-10 8-4 15 2 15 4s10-3 13 0-2 8-10 6" fill="#fff8e5"/><g fill="#46575b" stroke="#d0b779" stroke-width="3"><circle cx="40" cy="66" r="9"/><circle cx="59" cy="66" r="9"/><circle cx="90" cy="64" r="13"/><circle cx="121" cy="64" r="13"/><circle cx="153" cy="64" r="13"/></g><path d="M90 64h63" stroke="#d2bd88" stroke-width="4"/><g fill="#d4bc84"><circle cx="90" cy="64" r="3"/><circle cx="121" cy="64" r="3"/><circle cx="153" cy="64" r="3"/></g></svg>`;
function renderDetail(){
  const el=$('#detail');if(selected.type==='station'){const s=station(selected.id),connected=!!railPath(state,STATIONS[0],s);el.innerHTML=`<div class="ribbon">${s.name}<span>${s.kind}</span></div><div class="detail-body"><div class="station-detail-icon">${{小镇:'⌂',中心城镇:'⌂',林场:'♧',矿场:'◇',农场:'♧',河畔小镇:'⌂'}[s.kind]}</div><span class="tag ${connected?'':'off'}">${connected?'已接入路网':'等待铁路连接'}</span><div class="supply"><span>出产 ${GOODS[s.makes].name}</span><b id="station-stock">${state.stocks[s.id]} / 80</b></div><p class="station-detail-desc">需要：${s.accepts.map(g=>GOODS[g].name).join('、')}<br>每 5 秒补充 3 份货物。</p><div class="detail-buttons"><button data-detail="build-station">从这里铺轨</button><button data-detail="focus-station" class="blue">前往车站</button></div><div class="detail-secondary"><button data-detail="trains">安排列车运输 →</button></div></div>`;return;}
  const t=selectedTrain();el.innerHTML=`<div class="ribbon">${t.name}<span>${'★'.repeat(t.level)}</span></div><div class="train-art">${trainArt(t.id%2===0?'#a5785d':'#5087a8')}</div><p class="train-type">西部蒸汽机车 · ${t.level===1?'开拓型':t.level===2?'远行型':'先锋型'}</p><div class="detail-body"><div class="gauge-row"><div><span>运行速度</span><strong id="train-speed">${Math.round((1.12+t.level*.24)*28)} 千米 / 时</strong></div><div class="gauge"><i style="width:${45+t.level*16}%"></i></div></div><div class="gauge-row"><div><span>本次行程</span><strong id="train-progress">${Math.round(t.progress*100)}%</strong></div><div class="gauge"><i id="train-progress-bar" style="width:${t.progress*100}%"></i></div></div><div class="gauge-row"><div><span>车况</span><strong id="train-condition">${Math.floor(t.condition)}%</strong></div><div class="gauge green"><i id="train-condition-bar" style="width:${t.condition}%"></i></div></div><div id="train-cargo" class="cargo-row">${cargoHTML(t)}</div><div class="route-strip"><svg><use href="#i-rail"/></svg>${station(t.from).name} ⇄ ${station(t.to).name}</div><div id="train-status" class="status-line">${t.status}</div><div class="detail-buttons"><button data-detail="route">调度路线</button><button data-detail="upgrade" class="blue">${t.level<3?'升级 $'+fmt(t.level*1600):'已满级'}</button></div><div class="detail-secondary"><button data-detail="follow">跟随列车</button><button data-detail="repair">保养</button></div></div>`;
}
function cargoHTML(t){return Array.from({length:3},(_,i)=>`<span class="cargo-box ${t.cargo>i*3?'loaded':''}"></span>`).join('')+`<small>${t.cargo} ${GOODS[t.good]?.name||'货物'}</small>`;}
let lastCargo='';
function render(){
  $('#money').textContent=fmt(state.money);$('#score').textContent=fmt(state.score);$('#day').textContent=`第 ${state.day} 天`;
  const connected=STATIONS.filter(s=>railPath(state,STATIONS[0],s)).length;$('#connected-count').textContent=`${connected} / 6 站`;
  const c=CONTRACTS.find(c=>!state.claimed.includes(c.id));if(c){const n=Math.min(state.contracts[c.id],c.amount);$('#chapter').textContent=`0${CONTRACTS.indexOf(c)+1} / 03`;$('#objective-name').textContent=n>=c.amount?'合同已完成！':{wood:'把森林接入铁路',grain:'给矿工送去粮食',ore:'让铜矿穿越峡谷'}[c.id];$('#objective-description').textContent=c.desc;$('#objective-count').textContent=`${GOODS[c.good].name} ${n} / ${c.amount}`;$('#objective-reward').textContent=`奖励 $ ${fmt(c.reward)}`;$('#objective-progress').style.width=`${n/c.amount*100}%`;$('#objective-action').innerHTML=n>=c.amount?'领取合同奖励 <span>→</span>':'查看运输合同 <span>→</span>';}else{$('#chapter').textContent='03 / 03';$('#objective-name').textContent=connected===6?'西部铁路大亨':'连接最后的车站';$('#objective-description').textContent=connected===6?'所有小镇已连通。继续扩展你的铁路事业吧。':'三份合同已完成，把全部六个车站接入同一条路网。';$('#objective-count').textContent=`车站 ${connected} / 6`;$('#objective-reward').textContent='自由经营';$('#objective-progress').style.width=`${connected/6*100}%`;$('#objective-action').innerHTML='查看合同记录 <span>→</span>';}
  $('#contract-dot').hidden=!CONTRACTS.some(c=>!state.claimed.includes(c.id)&&state.contracts[c.id]>=c.amount);
  if(selected.type==='train'){const t=selectedTrain();if($('#train-progress')){$('#train-progress').textContent=`${Math.round(t.progress*100)}%`;$('#train-progress-bar').style.width=`${t.progress*100}%`;$('#train-condition').textContent=`${Math.floor(t.condition)}%`;$('#train-condition-bar').style.width=`${t.condition}%`;$('#train-status').textContent=paused?'已暂停':`${t.status}${t.cargo?' · '+GOODS[t.good].name:''}`;$('#train-speed').textContent=(t.dwell>0||paused||t.condition<=0?'0':Math.round((1.12+t.level*.24)*(t.condition<20?.65:1)*28))+' 千米 / 时';const cargo=`${t.good}:${t.cargo}`;if(cargo!==lastCargo){$('#train-cargo').innerHTML=cargoHTML(t);lastCargo=cargo;}}}else if($('#station-stock'))$('#station-stock').textContent=state.stocks[selected.id]+' / 80';
  if(plan)$('#confirm-build').disabled=state.money<plan.price;
  $('#simulation-status').textContent=paused?'已暂停':'运营中';$('#pause').textContent=paused?'▶':'Ⅱ';$('#pause').setAttribute('aria-label',paused?'继续游戏':'暂停游戏');
}
function openModal(title,html,type=''){modalType=type;$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();chime();}
function closeModal(){$('#modal').close();modalType='';}
function panel(type){
  if(type==='trains'){openModal('我的列车',`<p class="modal-note">${state.trains.length} 列蒸汽机车正在这片土地上奔忙。安排连接供需的往返路线，货物将在车站自动装卸。</p><div class="cards">${state.trains.map(t=>`<article class="list-card"><h3>${t.name} <span class="tag">${'★'.repeat(t.level)}</span></h3><div style="height:86px">${trainArt(t.id%2===0?'#a5785d':'#5087a8')}</div><p>${station(t.from).name} ⇄ ${station(t.to).name}<br>${t.status} · 容量 ${4+t.level*2} · 已完成 ${t.deliveries} 次运输</p><div class="card-foot"><button class="soft-button" data-action="follow" data-id="${t.id}">跟随</button><button class="primary-button blue" data-action="route" data-id="${t.id}">调度路线</button></div></article>`).join('')}</div><div class="form-actions"><button class="primary-button" data-action="shop">购买新列车 →</button></div>`,'trains');}
  else if(type==='network'){const connected=STATIONS.filter(s=>railPath(state,STATIONS[0],s)).length;openModal('西部铁路网',`<div class="network-summary"><div><strong>${connected}<small> / 6 座车站</small></strong></div><div><strong>${Object.keys(state.tracks).length}<small> 格轨道</small></strong></div><div><strong>${state.deliveries}<small> 份货物已送达</small></strong></div></div><div class="cards">${STATIONS.map(s=>`<article class="list-card"><div class="station-card-heading"><h3>${s.name}</h3><span class="tag ${railPath(state,STATIONS[0],s)?'':'off'}">${railPath(state,STATIONS[0],s)?'已连通':'未连通'}</span></div><p>出产 ${GOODS[s.makes].name} · 库存 ${state.stocks[s.id]}<br>需要 ${s.accepts.map(g=>GOODS[g].name).join('、')}</p><div class="card-foot"><button class="soft-button" data-action="station-focus" data-id="${s.id}">前往</button><button class="primary-button blue" data-action="station-build" data-id="${s.id}">从这里铺轨</button></div></article>`).join('')}</div>`,'network');}
  else if(type==='contracts'){openModal('边境运输合同',`<p class="modal-note">先铺设铁路连接车站，再为列车安排运输路线。目标货物送达后，合同进度会自动增加。</p>${CONTRACTS.map(c=>{const done=state.claimed.includes(c.id),ready=state.contracts[c.id]>=c.amount;return `<article class="list-card contract-card"><div><h3>${c.name}</h3><p>${c.desc}</p><div class="progress"><i style="width:${Math.min(100,state.contracts[c.id]/c.amount*100)}%"></i></div><p>${GOODS[c.good].name} ${Math.min(c.amount,state.contracts[c.id])} / ${c.amount} · 目的地 ${station(c.to).name}</p></div><div class="reward"><small>完成奖励</small>$ ${fmt(c.reward)}<button class="primary-button" data-action="claim" data-id="${c.id}" ${done||!ready?'disabled':''}>${done?'已领取':ready?'领取奖励':'运输中'}</button></div></article>`;}).join('')}`,'contracts');}
  else if(type==='shop'){openModal('西部机车工场',`<p class="modal-note">新列车可自动往返运输。升级增加载货量与速度，保养让机车保持良好状态。</p><div class="cards"><article class="list-card"><span class="tag">可靠的第一选择</span><h3 style="margin-top:12px">开拓者蒸汽机车</h3><div style="height:110px">${trainArt()}</div><p>载货量 6 份 · 速度 38 千米 / 时<br>附煤水车与货车，购入后选择运营路线。</p><div class="card-foot"><b>$ ${fmt(1800+Math.max(0,state.trains.length-1)*600)}</b><button class="primary-button" data-action="buy" ${state.trains.length>=6?'disabled':''}>${state.trains.length>=6?'车库已满':'购入列车'}</button></div></article><article class="list-card"><span class="tag">你的车队</span><h3 style="margin-top:12px">机车升级与保养</h3>${state.trains.map(t=>`<p style="margin:16px 0 4px">${t.name} · ${'★'.repeat(t.level)} · 车况 ${Math.floor(t.condition)}%</p><div class="card-foot" style="margin-top:7px"><button class="soft-button" data-action="repair" data-id="${t.id}">保养 $${Math.ceil((100-t.condition)*8)}</button><button class="primary-button blue" data-action="upgrade" data-id="${t.id}" ${t.level>=3?'disabled':''}>${t.level>=3?'已满级':'升级 $'+fmt(t.level*1600)}</button></div>`).join('')}</article></div>`,'shop');}
}
function routeModal(t,buy=false){routeTrain=t;shopRoute=buy;const from=t?.from||'pine',to=t?.to||'canyon';openModal(buy?'为新列车选择路线':'调度 '+t.name,`<p class="modal-note">列车会自动往返；只装载对方需要的货物。更换路线将把列车调回起点，车上未交付货物会被清空。</p><form id="route-form" class="route-form"><label>始发车站<select id="route-from" aria-label="始发车站">${STATIONS.map(s=>`<option value="${s.id}" ${s.id===from?'selected':''}>${s.name} · 出产${GOODS[s.makes].name}</option>`).join('')}</select></label><label>到达车站<select id="route-to" aria-label="到达车站">${STATIONS.map(s=>`<option value="${s.id}" ${s.id===to?'selected':''}>${s.name} · 需要${s.accepts.map(g=>GOODS[g].name).join(' / ')}</option>`).join('')}</select></label><div id="route-preview" class="route-preview"></div><div id="route-error" class="form-error" role="status"></div><div class="form-actions"><button type="button" class="soft-button" data-action="trains">返回</button><button class="primary-button blue" type="submit">${buy?'购买并发车':'确认路线'}</button></div></form>`,'route');routePreview();}
function routePreview(){const a=station($('#route-from').value),b=station($('#route-to').value),path=railPath(state,a,b);let text='';if(a.id===b.id)text='请选择不同的两个车站。';else if(!path)text='尚未接通：请先用铁轨或铁路桥连接这两座车站。';else{text=`已连通 · ${path.length} 格路程<br>`;const forward=b.accepts.includes(a.makes),backward=a.accepts.includes(b.makes);text+=forward?`${a.name} → ${b.name}：${GOODS[a.makes].name}，每份 $${GOODS[a.makes].price}`:'去程没有可交付的货物';text+='<br>';text+=backward?`${b.name} → ${a.name}：${GOODS[b.makes].name}，每份 $${GOODS[b.makes].price}`:'回程为空车返回';}$('#route-preview').innerHTML=text;}
function stationModal(s){openModal(s.name,`<p class="modal-note">${s.kind} · ${railPath(state,STATIONS[0],s)?'已连接铁路':'尚未连接铁路'}</p><div class="supply"><span>出产 ${GOODS[s.makes].name}</span><b>库存 ${state.stocks[s.id]} / 80</b></div><p class="station-detail-desc">需要：${s.accepts.map(g=>GOODS[g].name).join('、')}<br>每 5 秒补充 3 份货物。</p><div class="form-actions"><button class="soft-button" data-action="station-focus" data-id="${s.id}">前往车站</button><button class="primary-button" data-action="station-build" data-id="${s.id}">从这里铺轨</button></div>`,'station');}
function help(){openModal('欢迎来到峡谷铁路',`<p class="modal-note">1886 年，西部的六座聚落正在等待第一声汽笛。铺设铁路，连接供需，让一列小火车开出你的铁路事业。</p><div class="guide-grid"><div class="guide-step"><span class="guide-number">01</span><b>铺下第一段铁轨</b><p>选择「铁轨」，依次点击起点和终点车站。绿色路线是预览，点「铺设铁路」完成施工。跨河时使用「铁路桥」。</p></div><div class="guide-step"><span class="guide-number">02</span><b>让货物动起来</b><p>打开「列车」→「调度路线」。木场产木材、牧场产粮食、矿场产铜矿。车站装卸和返程都会自动完成。</p></div><div class="guide-step"><span class="guide-number">03</span><b>完成边境合同</b><p>送 12 份木材到红岩镇、16 份粮食到铜溪矿场、18 份铜矿到银泉镇。领取奖励，再将六站全部连通。</p></div><div class="guide-step"><span class="guide-number">04</span><b>慢慢经营这片西部</b><p>拖动平移，滚轮缩放，右键旋转。手机支持单指平移与双指缩放。空格暂停，1–4 打开菜单，Esc 取消建造。</p></div></div><p class="modal-note" style="margin-top:15px">你的第一列车已经在松谷镇与红岩镇之间运送粮食。下一步，试着连接地图左上方的松林木场。</p><div class="help-footer"><button data-action="reset-confirm">重新开始这片荒野</button><button class="primary-button blue" data-action="close">出发，开拓西部 →</button></div>`,'help');}

async function start(){
  try{world=new World($('#world'),$('#map-labels'),pick);world.syncRails(state);renderDetail();render();$('#loading').classList.add('hidden');setTimeout(()=>$('#loading').remove(),700);toast(saved?'欢迎回来，铁路日志已恢复。':'欢迎来到西部！第一列火车已经启程。');
    let last=performance.now(),uiTime=0,saveTime=0;const frame=now=>{const dt=Math.min((now-last)/1000,.08);last=now;const simDt=paused||$('#modal').open||document.hidden?0:dt*speed;const events=tick(state,simDt);for(const e of events){if(e.type==='delivery'){toast(`${station(e.to).name}收到 ${e.amount} 份${GOODS[e.good].name} · + $${fmt(e.income)}`,'earned');chime('income');}else if(e.type==='win'){openModal('你让整个西部连在一起',`<p class="modal-note">六座车站，三份合同，无数次汽笛。你的铁路已经成为这片荒野的新脉搏。</p><div class="network-summary"><div><strong>${fmt(state.revenue)}</strong><small>累计运输收入</small></div><div><strong>${state.deliveries}</strong><small>货物送达</small></div><div><strong>${state.day}</strong><small>开拓天数</small></div></div><div class="form-actions"><button class="primary-button" data-action="close">继续自由经营</button></div>`,'win');save();}}world.update(state,dt,simDt);uiTime+=dt;saveTime+=dt;if(uiTime>.22){render();world.minimap($('#minimap'),state);uiTime=0;}if(saveTime>15){save();saveTime=0;}requestAnimationFrame(frame);};requestAnimationFrame(frame);
  }catch(error){console.error(error);$('#loading').innerHTML='<h2>地图暂时未能启动</h2><p>请使用支持 WebGL 的现代浏览器，并开启硬件加速。</p><button class="primary-button" onclick="location.reload()">重新加载</button>';}
}
$$('[data-tool]').forEach(b=>b.onclick=()=>{setMode(b.dataset.tool);chime();});$$('[data-panel]').forEach(b=>b.onclick=()=>panel(b.dataset.panel));$$('[data-speed]').forEach(b=>b.onclick=()=>{speed=Number(b.dataset.speed);paused=false;$$('[data-speed]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});render();});
$('#confirm-build').onclick=confirmBuild;$('#cancel-build').onclick=()=>setMode(mode);$('#pause').onclick=()=>{paused=!paused;render();};$('#save').onclick=()=>save(true);$('#help').onclick=help;$('#objective-action').onclick=()=>panel('contracts');$('#close-modal').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
$('#sound').onclick=()=>{sound=!sound;$('#sound').classList.toggle('muted',!sound);$('#sound').setAttribute('aria-label',sound?'关闭声音':'开启声音');$('#sound').title=sound?'关闭声音':'开启声音';toast(sound?'声音已开启':'声音已关闭');chime('whistle');};$('#daylight').onclick=()=>{const dusk=world.setNight();toast(dusk?'暮色降临，铁路照常运营。':'新的一天，阳光洒满峡谷。');};$('#zoom-in').onclick=()=>world.zoom(1.2);$('#zoom-out').onclick=()=>world.zoom(1/1.2);$('#recenter').onclick=()=>world.recenter();$('#minimap').onclick=e=>{const r=e.target.getBoundingClientRect();world.mapFocus(((e.clientX-r.left)/r.width-.5)*42,((e.clientY-r.top)/r.height-.5)*26.04);};
$('#detail').onclick=e=>{const action=e.target.closest('[data-detail]')?.dataset.detail;if(!action)return;const t=selectedTrain();if(action==='route')routeModal(t);if(action==='trains')panel('trains');if(action==='upgrade'){if(result(upgradeTrain(state,t),'列车升级完成，载货量和速度已提升。')){renderDetail();chime('build');}}if(action==='repair'){if(result(repairTrain(state,t),'列车已完成保养。'))renderDetail();}if(action==='follow'){world.follow=t.id;toast('镜头正在跟随 '+t.name);}if(action==='focus-station')world.focusStation(station(selected.id));if(action==='build-station'){const s=station(selected.id);setMode('rail');pick({x:s.x,z:s.z,station:s});}};
$('#modal-body').addEventListener('change',e=>{if(e.target.matches('#route-from, #route-to'))routePreview();});
$('#modal-body').addEventListener('submit',e=>{if(e.target.id!=='route-form')return;e.preventDefault();const from=$('#route-from').value,to=$('#route-to').value;const r=shopRoute?buyTrain(state,from,to):setRoute(state,routeTrain,from,to);if(r.error){$('#route-error').textContent=r.error;chime();return;}selected={type:'train',id:shopRoute?r.train.id:routeTrain.id};closeModal();save();renderDetail();render();toast(shopRoute?'新机车已入列，汽笛响起！':'新路线已启用，列车正在装货。','earned');chime('whistle');});
$('#modal-body').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;if(['trains','network','contracts','shop'].includes(a)){panel(a);return;}if(a==='close'){closeModal();return;}if(a==='route'){routeModal(train(Number(id)));return;}if(a==='follow'){selected={type:'train',id:Number(id)};world.follow=Number(id);renderDetail();closeModal();return;}if(a==='buy'){routeModal(null,true);return;}if(a==='claim'){if(result(claimContract(state,id),'合同奖励已到账！')){chime('income');panel('contracts');}return;}if(a==='upgrade'||a==='repair'){const t=train(Number(id)),r=a==='upgrade'?upgradeTrain(state,t):repairTrain(state,t);if(result(r,a==='upgrade'?'机车升级完成！':'机车保养完成！')){panel('shop');renderDetail();}return;}if(a==='station-focus'||a==='station-build'){const s=station(id);closeModal();selected={type:'station',id};world.focusStation(s);renderDetail();if(a==='station-build'){setMode('rail');pick({x:s.x,z:s.z,station:s});}return;}if(a==='reset-confirm'){openModal('重新开始经营',`<p class="modal-note">这会清除当前浏览器中这款游戏的进度，恢复初始铁路、第一列机车和 6,800 金币。</p><div class="form-actions"><button class="soft-button" data-action="close">继续当前游戏</button><button class="primary-button" data-action="reset">重新开始</button></div>`,'reset');return;}if(a==='reset'){state=newGame();selected={type:'train',id:1};speed=1;paused=false;$$('[data-speed]').forEach(x=>{x.classList.toggle('active',x.dataset.speed==='1');x.setAttribute('aria-pressed',String(x.dataset.speed==='1'));});closeModal();world.syncRails(state);world.recenter();setMode('inspect');save();renderDetail();render();toast('新的铁路故事开始了。');}});
document.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea'))return;if(e.key==='Escape'){if(!$('#modal').open)setMode('inspect');return;}if($('#modal').open)return;if(e.code==='Space'){e.preventDefault();paused=!paused;render();}if(['1','2','3','4'].includes(e.key))panel(['trains','network','contracts','shop'][Number(e.key)-1]);if(e.key.toLowerCase()==='b')setMode('rail');if(e.key.toLowerCase()==='h')help();});document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});window.addEventListener('pagehide',()=>save());
start();
